### ISSUE TITLE
Automatically choose `--from_safetensors` when appropriate

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lit-gpt#1008]
If you forget to set `--from_safetensors True` when downloading models, you get:

```
ValueError: Expected 'checkpoints/google/gemma-2b' to contain .bin files
```

We assume that users perfectly follow the download tutorial guides where `--from_safetensors True` for some commands. But intuitively, I feel like the download scripts could probably choose this automatically. Some need it, some don't.

**Comment by rasbt** [comment]
Yeah, I think we originally added it for mistral and only few others need it (like Gemma). 

I wonder if we should make `--safetensors true` the new default for the new user experience. It's actually safer :). And if a safetensor format is not available, we throw a warning and say "download the model with --safetensors false`. What do you think?

**Comment by Andrei-Aksionov** [comment]
There should be a way to check are there any files in the repo with `.safetensors` extension.

**Comment by rasbt** [comment]
This looks reasonable to me. We already import from `huggingface_hub` so that wouldn't add an additional dependency
