### ISSUE TITLE
Expose batch size and gpu device in `eval/lm_eval_harness.py`

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#1011]
In my opinion these are important settings for a user but they are currently missing

**Comment by carmocca** [comment]
@rasbt We don'' support batched generation. The device you could control today with `CUDA_VISIBLE_DEVICES`

**Comment by rasbt** [comment]
Ah yes, makes sense. Since we currently also only support generation on single devices, `CUDA_VISIBLE_DEVICES` should be sufficient (that's how I was using it until know)
