### ISSUE TITLE
Feature Request: add support for fine-tuned (Falcon) models

### ISSUE THREAD

**Issue by ChristianPala** [Lightning-AI/lit-gpt#144]
Hi folks,
I'm trying to use a LoRA fine-tuning of Falcon with multilingual support with your pipeline, but it's not natively supported, would be a good addition to the project!
Thanks for the attention

**Comment by carmocca** [comment]
What error are you getting?

LoRA suport for Falcon is landing with #141. You can install that branch to give it a try

**Comment by ChristianPala** [comment]
Hi!
After converting the weights from the repository: OpenAssistant/falcon-7b-sft-top1-696, via hugging face, to the lit-parrot format, when I try generating, using base.py I get the following runtime size mismatch error:
`RuntimeError: Error(s) in loading state_dict for Parrot:
        size mismatch for lm_head.weight: copying a param with shape torch.Size([65040, 4544]) from checkpoint, the shape in current model is torch.Size([65024, 
4544]).
        size mismatch for transformer.wte.weight: copying a param with shape torch.Size([65040, 4544]) from checkpoint, the shape in current model is 
torch.Size([65024, 4544]).
`
