### ISSUE TITLE
Not an issue but a question: How do I pre-train Falcon on completely new language ?

### ISSUE THREAD

**Issue by thusinh1969** [Lightning-AI/lit-gpt#160]
Hi,

I have been pre-training and fine-tuning Vietnamese language on LlaMA-7B, so far so good, we just do not yet have enough computational capacity to move on. We extended the vocab to 50k so that it covers adequately Vietnamese dictionary and such. We pre-train with large Vietnamese corpus nearly 1B tokens (raw text), and then fine-tuning with LoRA using translated Alpaca and a few other downstream tasks.

Can we do the same with Falcon and other model using Lit-Parrot ? Is there any script that we can refer to for this journey.

Thanks,
Steve

**Comment by carmocca** [comment]
The same technique should work on Falcon, there's nothing substantially different in how the model is pre-trained.

**Comment by jaykasundra2** [comment]
Hi @thusinh1969 , I am also trying the similar approach for Hindi Language with Open-LLaMA 3B. It would be really great if you can point me to your implementation. I am specifically looking on how to continue the pre-training with another language dataset from the llama3B checkpoint rather than the PEFT or Pre-training from scratch.

**Comment by someshfengde** [comment]
Hey @thusinh1969, I've tried previously to finetune with the falcon7b. 
For the `lora.py` with some modifications everything works fine. 
But for the `adapter.py` and `adapter-v2.py` I'm getting out-of-memory errors does anyone previously tried and faced the same? 

I'm listing some modifications I've done to `lora.py`
* used mixed precision float 16 
* reduced macro batch size 
* increased no of iterations ( there's no epoch options but you can increase the iterations for better results ) 
* reduced batch size 

### Hardware used for training 
1x A100 GPU ( lora.py doesn't support multiple GPUs)

**Comment by thusinh1969** [comment]
Hi guys, sorry being busy lately.
- I extend the vocab using Google's sentencepiece, nothing special really.
- Use PEFT is the only way I tried for now, with training all LoRA key's weights and also 
q_proj, v_proj, k_proj, o_proj, gate_proj, down_proj, up_proj, embed_tokens, lm_head" which is about +500M params
- LoRA rank 8/alpha 32
- global batch 128 with deepspeeds.
- lr 2e-4

Trained on 4 A100 40G for 16 days :) as a base for all other downstream task.

I use pretty much the repo from https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/README_EN.md with some modification.

Contact me nguyen@hatto.com so we can work out more things. I am learning everyday, still new to me.

Cheers,
Steve
