### ISSUE TITLE
4bit and 8bit precision finetuning support

### ISSUE THREAD

**Issue by ThiagoViek** [Lightning-AI/lit-gpt#176]
I would like to know if I can run finetuning (LoRA) using quantized models. Is there any documentation on that?

**Comment by carmocca** [comment]
This is not implemented and not explored at the moment.

**Comment by louisoutin** [comment]
+1

**Comment by patrickhwood** [comment]
Submitted PR https://github.com/Lightning-AI/lit-gpt/pull/275, but it fails the tests and I'm not familiar with the testing workflow here and can't run the tests locally, so I'm stumped.
