### ISSUE TITLE
Issues With generate.adapter_v2 Script

### ISSUE THREAD

**Issue by gmongaras** [Lightning-AI/lit-gpt#179]
I was able to finetune a model on a custom dataset. However, I've been running into quite a few issues when trying to generate a sample from the generation script using llm.int8. Normal generation with the chat script appears to use Linear8bitLt. When it does a linear layer, it uses bnb linear leading to no issues. However, the adapter v2 script changes the implementation of the linear layer so the adapters can be used, but now instead of using Linear8bitLt, they use the normal torch linear function. 

If I change the function to Linear8bitLt in the adapter layers, I run into issue such that the outputs of the linear layer are massive and the network results in nonsensical output. If I convert the weights to a bfloat16 before passing it through the normal torch linear layer, I run into the same issue. I was thinking the network was only being initialized with random weights, but that would mean the adapter weights are 1 scale and 0 bias, but after loading in the checkpoints, this is not the case.

I'm a little stuck on how I could go about fixing these errors. Any help would be appreciated!

**Comment by carmocca** [comment]
I belive this is fixed now
