### ISSUE TITLE
Fine tune last step doesn't work, config.json required

### ISSUE THREAD

**Issue by cosmin-z** [Lightning-AI/lit-gpt#196]
Hi, 

I have tried to fine-tune my personal dataset according to this guide: https://github.com/Lightning-AI/lit-gpt/blob/main/howto/finetune_adapter.md

But when I try to do the last step, it tells me that "there is no config.json file in my_data". But I didn't understand what this config.json is and how to set up. 

Thank for your help

**Comment by carmocca** [comment]
The most recent updates removed the use of this config file. Did you pull `main`?

**Comment by cosmin-z** [comment]
Hi @carmocca. Yes, I did
