### ISSUE TITLE
Add support for MPT

### ISSUE THREAD

**Issue by debackerl** [Lightning-AI/lit-gpt#199]
It would be interesting to add support for MPT models. They are maybe the only one with ALiBi encoding, and the new MPT-30B model supports 8k context length.

Thanks!

**Comment by louisoutin** [comment]
+1

**Comment by carmocca** [comment]
I looked into implementing this ([branch](https://github.com/Lightning-AI/lit-gpt/compare/carmocca/mpt?expand=1)). The missing pieces are:
- ALiBi
- Low precision LayerNorm

And to reproduce training, they also do
- Tied embeddings weights with lm_head
- kaiming normal initialization
