### ISSUE TITLE
Port finetuning from Lit-LLaMA

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lit-gpt#20]
- [ ] full #117 
- [x] LoRA #128 
- [x] Adapter #31

**Comment by joseph35533553** [comment]
hi is fine tuning from lit-Llama file available yet? For now it seems 1 time training but if we can continue fine tuning form lit-LLama It would be quite helpful

**Comment by carmocca** [comment]
@joseph35533553 We have adapter merged (https://github.com/Lightning-AI/lit-parrot/blob/main/howto/finetune_adapter.md), and Lora on its way: #128
