### ISSUE TITLE
Full fine-tuning code for Falcon

### ISSUE THREAD

**Issue by Amshaker** [Lightning-AI/lit-gpt#201]
Hi Authors,

Thank you so much for releasing this awesome work, it is really helpful!

Could you please guide me on how to run full fine-tuning for Falcon 7B without using any adapters?

[Here](https://lightning.ai/pages/community/finetuning-falcon-efficiently/) you wrote the same script as Lora.

<img width="1025" alt="image" src="https://github.com/Lightning-AI/lit-gpt/assets/108531886/94ab9aef-1685-4450-859a-977d079e3a59">

Your fast response is highly appreciated.

Best regards,
Abdelrahman.

**Comment by Amshaker** [comment]
@carmocca your input is highly appreciated.

**Comment by carmocca** [comment]
Hi @Amshaker. Just merged support for this, please see the guide in https://github.com/Lightning-AI/lit-gpt/blob/main/howto/finetune_full.md.

Hope that helps!

**Comment by Amshaker** [comment]
Hi @carmocca ,

Thank you for merging this request, it is quite helpful.

However, I am not able to do full-finetuning for Falcon-7B using 8 AMD MI250x with 64GB VRAM due to OOM issues. I tried all the tips you mentioned [here](https://github.com/Lightning-AI/lit-gpt/blob/681a078949908e789ee4fcdb7ecbeff2e588e9a4/howto/oom.md?plain=1) but still can't fit the model into the memory. The total memory is 64x8=512GB. You mentioned that Falcon-7B needs around 240GB. Could you please let me know the reason or your proposals to do this full fine-tuning?

Thank you so much.
Abdelrahman.
