### ISSUE TITLE
Multi-node training issue for full fine-tuning

### ISSUE THREAD

**Issue by Amshaker** [Lightning-AI/lit-gpt#203]
Hi @carmocca ,

I have one issue regarding running the full fine-tuning using multi-node training. The code hangs during initializing deepspeed distributed after this output:
`initializing deepspeed distributed: GLOBAL_RANK: 0, MEMBER: 1/8`

What I changed to the finetune/full.py is calling Fabric as follows:
`fabric = L.Fabric(devices=4, num_nodes=2, strategy=DeepSpeedStrategy(config=ds_config) if devices > 1 else "auto", precision=precision)`

And the following is the node information in the SLURM file:

```
#!/bin/sh
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=16
#SBATCH --gres=gpu:4

python finetune/full.py
```

Shall I change anything else to run the full fine-tuning using distributed nodes?

Your fast response is highly appreciated.

Best regards,
Abdelrahman.

**Comment by carmocca** [comment]
I am not a SLURM expert unfortunately, but we have a SLURM guide here https://lightning.ai/docs/pytorch/latest/clouds/cluster_advanced.html
