### ISSUE TITLE
Finetune Falcon-7B with custom dataset

### ISSUE THREAD

**Issue by chinwh2019** [Lightning-AI/lit-gpt#204]
Hi, I am trying to finetune Falcon-7B with alpaca japanese dataset. the dataset sample as follows:
`{"instruction":  "「ディクディク属」の綴りを言ってください。",
  "input":"",
  "output":"X-Y-L-0-P-H-0-N-E(航空機)\n"
},
{"instruction":  "特定の分野で影響力のある5人のリストを作成し、各人物の簡単な説明を加えます。",
  "input":"芸術\n",
  "output":"1.レオナルド・ダ・ヴィンチ-イタリア・ルネサンス期の巨匠であり、優れた芸術作品で知られる。2.ミケランジェロ-壮大なフレスコ画や彫像を作ることで知られる彫刻家であり画家。3.レンブラント-オランダの画家であり、製図技師であり、版画家であり、美術史上最も重要な人物の一人。4.パブロ・ピカソ-スペインの著名な画家であり、彫刻家であり、陶芸家であり、20世紀に芸術に革命を起こした。5.フィンセント・ファン・ゴッホ-後期印象派の画家で、没後その名声は絶頂に達した。\n"
},
{"instruction":  "与えられたタスク記述にどのタイプの機械学習技術が適用可能かを特定する。",
  "input":"画像の大規模なデータセットがある場合は、画像を正確に分類できるモデルを作成します。\n",
  "output":"このタスクに適用可能な機械学習技術は、畳み込みニューラルネットワーク(CNN)である。CNNは通常、画像分類タスクに使用され、ビジュアルデータ内のパターンを検出できる。\n"
},
`
Since the format of the dataset is same as alpaca, so I use the `prepare_alpaca.py` to prepare the dataset for finetuning. However, I encounter the error as follows:
`  File "C:\Users\weiho\PycharmProjects\lit-gpt\scripts\prepare_alpaca.py", line 162, in <module>
    CLI(prepare)
  File "C:\Users\weiho\anaconda3\envs\llm-light\Lib\site-packages\jsonargparse\_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\weiho\anaconda3\envs\llm-light\Lib\site-packages\jsonargparse\_cli.py", line 147, in _run_component
    return component(**cfg)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\weiho\PycharmProjects\lit-gpt\scripts\prepare_alpaca.py", line 67, in prepare
    train_set = [
                ^
  File "C:\Users\weiho\PycharmProjects\lit-gpt\scripts\prepare_alpaca.py", line 68, in <listcomp>
    prepare_sample(
  File "C:\Users\weiho\PycharmProjects\lit-gpt\scripts\prepare_alpaca.py", line 124, in prepare_sample
    full_prompt = generate_prompt(example)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\weiho\PycharmProjects\lit-gpt\scripts\prepare_alpaca.py", line 146, in generate_prompt
    if example["input"]:
       ~~~~~~~^^^^^^^^^
KeyError: 'input'`

Could you please help how can I fix this error?

Thank you in advanced.

**Comment by cipher982** [comment]
Looking through the guide here: [https://github.com/Lightning-AI/lit-gpt/blob/main/howto/finetune_adapter.md#tune-on-your-dataset](https://github.com/Lightning-AI/lit-gpt/blob/main/howto/finetune_adapter.md#tune-on-your-dataset) do each of the json blobs in your file have the three required keys: `instruction`, `input`, and `output`?

**Comment by andjoer** [comment]
There is no "input" in the json blob that gives the error. The error is in line 146 `if example["input"]:` 
You could add the following lines before this line: 
`if "input" not in example.keys():
        print(example)`
This should print you the json blob that causes the error.

**Comment by cipher982** [comment]
For anyone else reading this, here is a small script I wrote to reformat my langchain llm logs to this required format. Keep in mind I am using json-lines because of some special formatting that was breaking regular json. You just want to extract the inputs (system/context/instructions and human-input) and the outputs (AI messages) into those three keys mentioned above (`instruction`, `input`, `output`). This gave me a file that worked with `prepare_alpaca.py`.

```python
import json

DATA_PATH = "../data/my_project/my_data.jsonl"

with open(DATA_PATH, "r") as file:
    data = file.readlines()
    data = [json.loads(line) for line in data]

print(f"Data has {len(data):,} samples")

system_input = data[0]["Question"].split("System: ")[1].split("Human: ")[0]
human_input = data[0]["Question"].split("System: ")[1].split("Human: ")[1]
response = data[0]["Response"]

formatted_dataset = []
for sample in data:
    system_input = sample["Question"].split("System: ")[1].split("Human: ")[0]
    human_input = sample["Question"].split("System: ")[1].split("Human: ")[1]
    response = sample["Response"]
    formatted_dataset.append(
        {
            "instruction": system_input,
            "input": human_input,
            "output": response,
        }
    )

print(f"Formatted dataset has {len(formatted_dataset):,} samples")

# Save the formatted dataset as json lines
with open("../data/my_project/formatted_my_data.jsonl", "w") as file:
    for sample in formatted_dataset:
        file.write(json.dumps(sample) + "\n")
```
