### ISSUE TITLE
OutOfMemory error when finetuning Falcon7b on custom dataset 

### ISSUE THREAD

**Issue by someshfengde** [Lightning-AI/lit-gpt#210]
## Hardware used 
A100x 2 
also did the experiment with single A100 ( thought it might be because of distributed nature) 

## Adapters used 
I've tried with adapter.py and adapter_v2.py for both it's not working ( getting out of memory error) while the same thing works with lora.py

**Comment by sylviachency** [comment]
Hi. Lora distributed is not implemented. How did you train with lora with 2 A100?

**Comment by someshfengde** [comment]
I've used device=2 and strategy='deepspeed' it was training with 2xA100 but causing OOM error

**Comment by sylviachency** [comment]
Did you see memory occupation on both GPUs? If you look into it’s source
code for Lora, there’s a “NotImplemented Error” when device > 1. So to my
understanding in this repo Lora does not support multi gpu training now.

**Comment by someshfengde** [comment]
Yes I saw memory occupation on both the GPUs the strategy='deepspeed' did the thing ig
