### ISSUE TITLE
Fine-tuning error after the training: probability tensor contains either inf', "nan or element < 0`

### ISSUE THREAD

**Issue by cosmin-z** [Lightning-AI/lit-gpt#221]
Hi, 

I am trying to do a fine-tuning based on this guide: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/finetune_adapter.md. 

I've lunched this command:
`python finetune/adapter.py \
    --data_dir data/mydata/ \
    --checkpoint_dir checkpoints/stabilityai/stablelm-base-alpha-3b \
    --out_dir data/mydata-finetuned`

with precision : `--precision 16-true`

And I got this error: 

`iter 9599 step 600: loss nan, iter time: 65.33ms (optimizer.step)
Validating
Recommend a movie for me to watch during the weekend and explain the reason.
Traceback (most recent call last):
File "/home/c zaharia/lit-gpt/finetune/adapter.py", line 299, in <module>
CLI (setup) 
File "/opt /conda/lib/python3.10/site-packages/jsonargparse/_cli.py",line 85, in CLI return run component (component, cfg init)
File " /opt/conda/lib/python3.10/site-packages/jsonargparse/_cli.py",line147,in_run_component
return component (**c§g)
File "/home/c _zaharia/lit-gpt/finetune/adapter.py", line 77, in setup
fabric. launch (main, data dir, checkpoint dir, out dir)
File "/opt /conda/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 781, in launch
return self. wrap and launch(function, self,
*args,**kwargs) <br>
File "/opt/conda/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 863, in _wrap_and_launch
return to run (*args,
**kwargs)
File "/opt /conda/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 868, in _wrap with setup return to run (*args, **kwargs)
File "/home/c zaharia/lit-gpt/finetune/adapter.py", line 115, in main
train (fabric, model, optimizer, train data, val_data, checkpoint_dir, out_ dir, speed monitor)
File "/home/c _zaharia/lit-gpt/finetune/adapter.py", line 202, in train
val loss = validate (fabric, model, val data, tokenizer, longest seq length)
File W/opt/conda/lib/python3.10/site-packages/torch/utils/contextlib.py",line115,indecoratecontext return func (*args,
**kwargs)
File "/home/c zaharia/lit-gpt/finetune/adapter.py", line 233, in validate
output = generate (
File "/opt /conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func (*args, **kwargs)
File "/home/c zaharia/lit-gpt/generate/base.py", line 75, in generate
idx next = torch. multinomial (probs, num samples=1) .to (type=type)
runt imeError: probability tensor contains either inf', "nan or element < 0`

I don't understand how to solve this problem, 
thanks for your help

**Comment by someshfengde** [comment]
I was also getting the same error #213

**Comment by zbapt** [comment]
Hello, 
I got the exact same error #221, here are the details:

I am actually trying to fine tune stabilityai/StableLM-Base-Alpha from hugging face, with the adapter.py file, using tha command line:

> python finetune/adapter.py --checkpoint_dir checkpoints/stabilityai/stablelm-base-alpha-3b --precision 16-true

I followed all the steps from this tutorial: Lightning-AI/lit-gpt/blob/main/tutorials/finetune_adapter.md and launched my finetuning.

It started correctly, for the 3 first iterations I got loss values. But then the loss was displayed as "nan". It did not cause trouble until the finetuning switch to the next epoch. I then got the error: 

      RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

The last printed lines in my terminal were: 

      iter 9598 step 599: loss nan, iter time: 76.30ms
      iter 9599 step 600: loss nan, iter time: 57.71ms (optimizer.step)
      Validating ...
      Recommend a movie for me to watch during the weekend and explain the reason.

Here is the full error:

/lit-gpt/finetune/adapter.py:314 in <module>
❱ 314 │   CLI(setup) 

/jsonargparse/_cli.py:85 in CLI 
❱  85 │   │   return _run_component(component, cfg_init) 

/jsonargparse/_cli.py:147 in _run_componen
❱ 147 │   │   return component(**cfg) 

/lit-gpt/finetune/adapter.py:77 in setup
❱  77 │   fabric.launch(main, data_dir, checkpoint_dir, out_dir) 

lightning/fabric/fabric.py:788 in launch 
❱ 788 │   │   return self._wrap_and_launch(function, self, *args, **kwargs) 

lightning/fabric/fabric.py:870 in  _wrap_and_launch
❱ 870 │   │   return to_run(*args, **kwargs)   

lightning/fabric/fabric.py:875 in  _wrap_with_setup
❱ 875 │   │   │   return to_run(*args, **kwargs)

/lit-gpt/finetune/adapter.py:115 in main 
❱ 115 │   train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)

/lit-gpt/finetune/adapter.py:216 in train 
❱ 216 │   │   │   val_loss = validate(fabric, model, val_data, tokenizer, longest_seq_length)

/torch/utils/_contextlib.py:115 in  decorate_contex
❱ 115 │   │   │   return func(*args, **kwargs) 

/lit-gpt/finetune/adapter.py:247 in validate 
❱ 247 │   output = generate(model, idx=encoded, max_returned_tokens=max_returned_tokens, max_seq_length=max_ )

/torch/utils/_contextlib.py:115 in  decorate_contex
❱ 115 │   │   │   return func(*args, **kwargs)

/lit-gpt/generate/base.py:75 in generate   
❱  75 │   │   idx_next = torch.multinomial(probs, um_samples=1).to(dtype=dtype)


Thanks you very much

**Comment by carmocca** [comment]
16-true precision has a very limited dynamic range and is prone to instabilities (NaNs, infs). You'll need to change the precision setting

**Comment by someshfengde** [comment]
@carmocca what should I change it to? I want to fit it into the limited memory

**Comment by carmocca** [comment]
The memory requirements depend on a lot of variables (https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/oom.md). You can try `bf16-true`, and if that's still unstable, then you'd want to use the mixed settings (`bf16-mixed`, `16-mixed`) which will take more memory. See this guide for more info: https://lightning.ai/docs/fabric/stable/fundamentals/precision.html

**Comment by someshfengde** [comment]
Thanks :)

**Comment by zbapt** [comment]
yes, thank you very much it worked perfectly for me !
