### ISSUE TITLE
ValueError: Precision 'bf16-true' is invalid. Allowed precision values: ('16-mixed', 'bf16-mixed', '32-true', '64-true', 64, 32, 16, '64', '32', '16', 'bf16')

### ISSUE THREAD

**Issue by seonglae** [Lightning-AI/lit-gpt#241]
I tried to run `generate/base.py` and followed [this readme](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/inference.md#run-a-large-model-on-one-smaller-device) with my RTX3080
My command is like this using `gptq.int4`

```bash
python generate/base.py --prompt "Hello, my name is" --checkpoint_dir checkpoints/openlm-research/open_llama_3b --quantize gptq.int4
```

This error happens.
```
\lit-gpt\.venv\Lib\site-packages\lightning\fabric\connector.py", line 549, in _convert_precision_to_unified_args
    raise ValueError(f"Precision {repr(precision)} is invalid. Allowed precision values: {supported_precision}")
ValueError: Precision 'bf16-true' is invalid. Allowed precision values: ('16-mixed', 'bf16-mixed', '32-true', '64-true', 64, 32, 16, '64', '32', '16', 'bf16')
```

What should I check more to run this script?

**Comment by carmocca** [comment]
What is your `lightning` version? This shouldn't happen using master.

You can upgrade it by doing:

`pip uninstall -y lightning; pip install -r requirements.txt`
