### ISSUE TITLE
Does/will lit-parrot support qlora?

### ISSUE THREAD

**Issue by thanhnew2001** [Lightning-AI/lit-gpt#243]
Qlora requires much less GPU, currently lit-parrot only supports lora. Is there any plan for supporting qlora as well?
It would be a huge advantage for users like us.

**Comment by carmocca** [comment]
Tracking in https://github.com/Lightning-AI/lit-gpt/issues/176! Thanks for the suggestion

**Comment by rasbt** [comment]
@thanhnew2001  should be supported now via #275 :)
