### ISSUE TITLE
Missing link to the blog post

### ISSUE THREAD

**Issue by ayulockin** [Lightning-AI/lit-gpt#244]
In the [Finetuning with LoRA](https://github.com/ayulockin/neurips-llm-efficiency-challenge/blob/main/tutorials/finetune_lora.md) markdown file there's a text pointing to a blog post but lacks the link tot he same.

The text:

`(See [this blog article](How To Finetune GPT Like Large Language Models on a Custom Dataset) for how to prepare and use custom datasets.)`

Thanks.

**Comment by carmocca** [comment]
Good catch! I think it was meant to link to https://lightning.ai/blog/how-to-finetune-gpt-like-large-language-models-on-a-custom-dataset

Would you like to open a PR with the fix?
