### ISSUE TITLE
Longchat input context length

### ISSUE THREAD

**Issue by louisoutin** [Lightning-AI/lit-gpt#256]
Hello,
I see that the longchat model is supported (cf: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/download_longchat.md).
However, I see that longchat block_size is 2048 (cf: https://github.com/Lightning-AI/lit-gpt/blob/main/lit_gpt/config.py#L373).
If I want to finetune longchat on sequence of more than 2048, should I just overwrite this block_size parameter?
Thanks

**Comment by louisoutin** [comment]
cf: https://github.com/Lightning-AI/lit-gpt/blob/main/lit_gpt/model.py#L74

**Comment by carmocca** [comment]
Thank you for reporting this. I just pushed a commit that should fix this.

**Comment by louisoutin** [comment]
Thanks! Looks great!
