### ISSUE TITLE
bnb.nf4, bnb.nf4-dq, bnb.fp4, bnb.fp4-dq don't work with lora.py

### ISSUE THREAD

**Issue by patrickhwood** [Lightning-AI/lit-gpt#261]
python3 generate/lora.py --checkpoint_dir checkpoints/tiiuae/falcon-7b --lora_path out/lora/alpaca/lit_model_lora_finetuned-falcon-7b.pth --quantize bnb.nf4
fails at:
│ /home/pwood/.local/lib/python3.10/site-packages/torch/nn/modules/linear.py:101 in __init__       │
│                                                                                                  │
│    98 │   │   │   self.bias = Parameter(torch.empty(out_features, **factory_kwargs))             │
│    99 │   │   else:                                                                              │
│   100 │   │   │   self.register_parameter('bias', None)                                          │
│ ❱ 101 │   │   self.reset_parameters()                                                            │
│   102 │                                                                                          │
│   103 │   def reset_parameters(self) -> None:                                                    │
│   104 │   │   # Setting a=sqrt(5) in kaiming_uniform is the same as initializing with            │
│                                                                                                  │
│ /mnt/nvme/src/ai/lit-gpt/lit_gpt/lora.py:206 in reset_parameters                                 │
│                                                                                                  │
│   203 │                                                                                          │
│   204 │   def reset_parameters(self):                                                            │
│   205 │   │   """Reset all the weights, even including pretrained ones."""                       │
│ ❱ 206 │   │   nn.Linear.reset_parameters(self)                                                   │
│   207 │   │   if hasattr(self, "lora_A"):                                                        │
│   208 │   │   │   # initialize A the same way as the default for nn.Linear and B to zero         │
│   209 │   │   │   # Wondering why 'a' is equal to math.sqrt(5)?: https://github.com/pytorch/py   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'functools.partial' object has no attribute 'reset_parameters'

Is fine with bnb.int8 and bfloat16.

$ python3 generate/lora.py --checkpoint_dir checkpoints/tiiuae/falcon-7b --lora_path out/lora/alpaca/lit_model_lora_finetuned-falcon-7b.pth
Loading model 'checkpoints/tiiuae/falcon-7b/lit_model.pth' with {'org': 'tiiuae', 'name': 'falcon-7b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.0, 'parallel_residual': True, 'bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 18176, 'condense_ratio': 1, 'r': 8, 'alpha': 16, 'dropout': 0.05}
Time to instantiate model: 0.08 seconds.
Time to load the model weights: 5.24 seconds.
Lamas typically eat grasses, leaves, and other vegetation. They are also known to eat insects such as ants and beetles.

Time for inference: 0.60 sec total, 41.83 tokens/sec
Memory used: 14.66 GB

$ python3 generate/lora.py --checkpoint_dir checkpoints/tiiuae/falcon-7b --lora_path out/lora/alpaca/lit_model_lora_finetuned-falcon-7b.pth --quantize bnb.int8
Loading model 'checkpoints/tiiuae/falcon-7b/lit_model.pth' with {'org': 'tiiuae', 'name': 'falcon-7b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.0, 'parallel_residual': True, 'bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 18176, 'condense_ratio': 1, 'r': 8, 'alpha': 16, 'dropout': 0.05}
bin /home/pwood/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
Time to instantiate model: 0.60 seconds.
Time to load the model weights: 6.35 seconds.
Lamas typically eat grasses, leaves, and shrubs. They also eat small animals such as insects, lizards, and small birds.

Time for inference: 0.92 sec total, 29.25 tokens/sec
Memory used: 9.39 GB

**Comment by carmocca** [comment]
Thanks for reporting. Can you try the changes in #262?

**Comment by patrickhwood** [comment]
Yup.  262 fixes it for all 4-bit float formats.
