### ISSUE TITLE
OOM when trying to tune falcon-7b as per tutorial example on single 24G GPU

### ISSUE THREAD

**Issue by d1abbolo** [Lightning-AI/lit-gpt#263]
I followed what described in 
https://lightning.ai/blog/falcon-a-guide-to-finetune-and-inference/
and my goal is to fine tune falcon-7b

I do this in the amazon sagamaker studio environemnt

when I run 

```
#Fine tune the model 

!python finetune/adapter_v2.py \
    --data_dir data/alpaca  \
    --checkpoint_dir checkpoints/tiiuae/falcon-7b \
    --out_dir out/adapter/alpaca 
```
I get the following error
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 316.00 MiB. GPU 0 has a total capacty of 22.20 GiB of which 144.12 MiB is free. Process 573 has 22.06 GiB memory in use. Of the allocated memory 21.23 GiB is allocated by PyTorch, and 57.37 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
I tried with `micro_batch_size = 1` and using also     `--precision 16-true`

but even though the script went a bit further, it still not complete. I just managed to reach 
```
Estimated TFLOPs: 96.02
Measured TFLOPs: 92.44
starting, max iterations: 250000
```

before getting the OOM error. 

Any thoughts? what suggestions to solve the issue? anyone using AWS sagemaker could have the model fine tuned, or are theere any other sagemaker environment I shall try?

**Comment by carmocca** [comment]
You can find other techniques to reduce memory usage here: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/oom.md

**Comment by d1abbolo** [comment]
I tried them all for a single GPU, unsuccesfully though. 
I have now access to multiple (4) GPUs machine and trying to run that. So far no error messages. but it looks like it is very slow...

**Comment by d1abbolo** [comment]
also the test on 4 GPU ended up with a OOM error 
```
File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 792.00 MiB. GPU 0 has a total capacty of 22.20 GiB of which 63.12 MiB is free. Process 26916 has 22.13 GiB memory in use. Of the allocated memory 19.25 GiB is allocated by PyTorch, and 1.73 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by patrickhwood** [comment]
I was unable to get adapter_v2 to fine tune the Falcon 7B model on a 24GB GPU, even with a smaller max_seq_length; however, I can get lora.py and adapter.py to fine tune with --precision bf16-true on the command line and micro_batch_size = 1 in the scripts.

Training speed seems to be reasonable.  I can fine tune with lora.py and the Alpaca set in < 1 hr on a 4090.  I was also able to fine tune with the Dolly 15K training set from this blog post: https://lightning.ai/blog/how-to-finetune-gpt-like-large-language-models-on-a-custom-dataset

I see

Estimated TFLOPs: 96.05
Measured TFLOPs: 89.63

at startup with micro_batch_size = 1, and 4x these values with micro_batch_size = 4 (which makes me wonder whether the calculation is correct -- they multiply the results of lit_gpt.speed_monitor.estimate_flops and lit_gpt.speed_monitor.measure_flops by micro_batch_size).

**Comment by patrickhwood** [comment]
Ah, you're running sagemaker on AWS.  The GPU isn't a true 24GB device:

> GPU 0 has a total capacty of 22.20 GiB

nvidia-smi -q reports this for my RTX 4090:

    FB Memory Usage
        Total                             : 24564 MiB

The alpaca dataset just barely works on my 4090 with lora.py and adapter.py.

**Comment by d1abbolo** [comment]
that is helpful! 

I will dig deeper and maybe try some other gpu available in AWS

**Comment by YangTakeshi** [comment]
> also the test on 4 GPU ended up with a OOM error
> 
> ```
> File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 204, in backward
>     Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 792.00 MiB. GPU 0 has a total capacty of 22.20 GiB of which 63.12 MiB is free. Process 26916 has 22.13 GiB memory in use. Of the allocated memory 19.25 GiB is allocated by PyTorch, and 1.73 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> ```

The multi-card acceleration strategy in lit-gpt's finetune code uses FSDP by default, which incurs a huge communication overhead in graphics cards that do not use NVLink (e.g. RTX3090 communicating via PCI), so it is recommended to manually add code to switch to the DDP strategy.

**Comment by carmocca** [comment]
@YangTakeshi The DDP's reducer will take as much memory as the model. This is prohibitively expensive in a memory-constrained environment (the usual case with LLMs).

**Comment by YangTakeshi** [comment]
> @YangTakeshi The DDP's reducer will take as much memory as the model. This is prohibitively expensive in a memory-constrained environment (the usual case with LLMs).

You are right, the advice I gave was for when the compute server GPU communication bandwidth is not enough, when the communication bandwidth is enough is when FSDP is definitely preferred.
