### ISSUE TITLE
Training with finetune/lora.py takes longer with larger micro_batch_size

### ISSUE THREAD

**Issue by patrickhwood** [Lightning-AI/lit-gpt#265]
Fine tuning with micro_batch_size set to 4 takes just a little less than 4x the time with micro_batch_size set to 1.  I was under the impression that micro_batch_size should only impact the internal training (reducing storage as a trade off to slightly longer training), but it looks like the number of iterations is the same regardless of the micro_batch_size setting, resulting in vastly different amounts of training.  Should max_iters be set to

  max_iters = 50000  / micro_batch_size # train dataset size

EDIT: 11464.66s vs. 3111.51s for micro_batch_size = 4 and 1, respectively on an RTX 4090.  No other changes from main branch of finetune/lora.py.

I only tested lora.py, but it appears that adapter.py and adapter_v2.py do the same thing.

**Comment by carmocca** [comment]
I don't have an easy answer here. This probably depends on your hardware and model size. If you are compute-bound then this would be expected. If you want to debug at this, I suggest profiling the code. Here's a guide: https://www.youtube.com/watch?v=qRZrVNNe3gQ
