### ISSUE TITLE
Are there LLMs suitable for text classification and summarisation?

### ISSUE THREAD

**Issue by Dee-Ma** [Lightning-AI/lit-gpt#271]
Hi, 

Many thanks for releasing this repo for using LLMs locally!

We are just wondering if there are any LLMs that are good for text classification and summarisation tasks (just for inference)?

Many thanks!

**Comment by carmocca** [comment]
All the models that are supported are trained for text generation. You might be able to prompt them so that they can perform those tasks. You can find some literature about this online.

**Comment by Dee-Ma** [comment]
Thanks, @carmocca!

1. We just have found useful tutorials about model usage from `tutorials` folder. But it seems that they are about using `--prompt` command to do `next token prediction` task. Could we know if there are command examples/tutorials for text classification and summarisation? Or we have to find them from the model's website, for example, we need to  Falcon LLM website to find those commands/literature? - we just didn't quite get your comment `You can find some literature about this online.`.
2. Could we know if there are any supported models that can run locally on CPU rather than GPU for inference?

Many thanks for your kind help!

**Comment by patrickhwood** [comment]
Take a look at this: https://github.com/imartinez/privateGPT  It first runs a search query through a sentence transformer to get the semantic embedding vector, searches a DB of documents for matching phrases, and then runs those results through a LLM for summarization.  Not exactly what you're looking to do, but some of the elements may map onto your problem.
