### ISSUE TITLE
Can I finetune falcon-7b with lora on ColabPro?

### ISSUE THREAD

**Issue by ian00000** [Lightning-AI/lit-gpt#277]
I tried to finetune lora with my own dataset by following "finetune_lora.md"(https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/finetune_lora.md).
It all went well until I run "!python finetune/lora.py --data_dir data/mydata/ --out_dir out/myexperiment".
The cell report 2 Error.
One is :

Traceback (most recent call last):
  File "/content/lit-gpt/lit_gpt/speed_monitor.py", line 97, in get_flops_available
    return int(GPU_AVAILABLE_FLOPS[device_name][precision])
KeyError: 'bf16-mixed'

Another is:
Traceback (most recent call last):
  File "/content/lit-gpt/finetune/lora.py", line 309, in <module>
    CLI(setup)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/content/lit-gpt/finetune/lora.py", line 76, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 805, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 887, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lightning/fabric/fabric.py", line 892, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/content/lit-gpt/finetune/lora.py", line 82, in main
    speed_monitor = SpeedMonitor(fabric, window_size=50, time_unit="seconds")
  File "/content/lit-gpt/lit_gpt/speed_monitor.py", line 281, in __init__
    flops_available = get_flops_available(fabric.device, fabric._connector._precision_input)
  File "/content/lit-gpt/lit_gpt/speed_monitor.py", line 99, in get_flops_available
    raise KeyError(
KeyError: 'flop count not found for t4 with precision: bf16-mixed; MFU cannot be calculated and reported.'

Has anyone else encountered this error? If so, how can I solve this? Thanks a lot!

**Comment by Andrei-Aksionov** [comment]
Hello
It depends on what GPU do you use.
I believe Pro version of Google Colab allows to chose out of:
- T4
- A100
- V100

It looks like only `A100` supports `bf-16` precision (default precision for lora fine-tune). And based on the error you used T4. So need either chose A100 (which might be pricey), or provide supported precision:
```python
!python finetune/lora.py --data_dir data/mydata/ --out_dir out/myexperiment --precision 32-true
```

List of supported precisions per GPU type can be found here:
https://github.com/Lightning-AI/lit-gpt/blob/2ddb1df8ed6d201bcd1996306a7e77513f1cb48b/lit_gpt/speed_monitor.py#L39-L55

**Comment by Andrei-Aksionov** [comment]
By the way here is an article where you can find a couple of notes about precisons (if you are not familiar with the concept): https://lightning.ai/pages/community/tutorial/pytorch-memory-vit-llm/

**Comment by Andrei-Aksionov** [comment]
Apparently there is not enough memory for the model that you've tried to use.

There might be couple of options:
1. Try `16-mixed` if you used something else
2. Try smaller model. By default `finetune/lora.py` uses the model with 3 billion of parameters:
https://github.com/Lightning-AI/lit-gpt/blob/77b49da22ac8e840cf344a98571b54b4735aba94/finetune/lora.py#L55
which looks like the smallest one from stablelm family. You can try to use `pythia` - there are models that even starts from 70 million of parameters:
https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/download_pythia.md
Start maybe with `pythia-1b` and if goes well - try a bigger one.
3. There is a work on fine-tuning with even a smaller precision:
https://github.com/Lightning-AI/lit-gpt/pull/275
You can track it and as soon as it's implemented - you will be able to train even larger models.

**Comment by ian00000** [comment]
Thanks a lot!

**Comment by patrickhwood** [comment]
> 3. There is a work on fine-tuning with even a smaller precision:
>    [Enable fine tuning with QLORA 4-bit floating point and bitsandbytes int8 types. #275](https://github.com/Lightning-AI/lit-gpt/pull/275)
>    You can track it and as soon as it's implemented - you will be able to train even larger models.
If you haven't already, try setting micro_batch_size = 1.  This makes a significant difference in the amount of memory used.

You can try the QLORA 4-bit types with my fork here: https://github.com/patrickhwood/lit-gpt  It's up-to-date with the latest commits (77b49da) in the Lightning-AI/lit-git repo.  I also just tested fine tuning with bnb.nf4-dq on the Llama 2 7B model and the Alpaca dataset with a 24GB GPU (uses about 17GB) and bnb.int8 (uses a little under 21GB, and produces slightly lower losses).
