### ISSUE TITLE
iter time as high as 9000ms

### ISSUE THREAD

**Issue by sreeprasannar** [Lightning-AI/lit-gpt#280]
for falcon-7b, adapter tuning, I have high iter times, around 9000ms. 
[Looks like the contributors have as low as 200ms](https://github.com/Lightning-AI/lit-gpt/issues/191#issuecomment-1612500870). 
I'm using an NVIDIA RTX A6000, if that matters. 
is there any way I could figure out what the bottleneck is?

**Comment by carmocca** [comment]
Your best bet would be using the PyTorch profiler. Here's a video that shows you how https://www.youtube.com/watch?v=qRZrVNNe3gQ
