### ISSUE TITLE
does lora finetuning for llama2 models work?

### ISSUE THREAD

**Issue by mimumo** [Lightning-AI/lit-gpt#281]
I tried to convert llama2 13B hf model to lit-gpt but script fails
is llama2 supported for lora finetune with lit-gpt?

**Comment by carmocca** [comment]
Yes it is! What error did you get?

**Comment by mimumo** [comment]
i got this error:
```
OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops6conv1d4callERKNS_6TensorES4_RKN3c108optionalIS2_EENS5_8ArrayRefIlEESB_SB_l
```
for this command
```
!python scripts/convert_hf_checkpoint.py --checkpoint_dir /content/lit-gpt/checkpoints/llama2/13B
```

**Comment by carmocca** [comment]
Try this: https://github.com/Lightning-AI/lit-gpt/issues/254#issuecomment-1632473883. Lit-gpt doesn't need torchaudio

**Comment by mimumo** [comment]
Thank worked thank you!

**Comment by mimumo** [comment]
However i can't train llama2 7B model on colab 1xA100 40GB gpu. in lit-llama with llama1 7B it worked. there was an option to truncate data. i truncated to 512 while creating dataset.

Would you share an example on how to fine tune llama7b with lig-gpt?
