### ISSUE TITLE
Using adapter-v2 finetune llama2-7b costs 64GB GPU mem

### ISSUE THREAD

**Issue by eshoyuan** [Lightning-AI/lit-gpt#282]
I didn't install Flash Attention 2.
I set micro_batch_size = 1 and others are default. If micro_batch_size is set to 2, OOM happens.
The maximum input length is less than 1000.
Given these circumstances, I believe the resource consumption for this process is excessively high. I would appreciate any guidance or suggestions on how to optimize these settings to reduce the resource usage.

**Comment by patrickhwood** [comment]
Adapter_v2 uses more memory than lora and adapter.  Running with stablelm-base-alpha-3b, micro_batch_size = 1 uses ~12GB and micro_batch_size = 2 uses ~16GB, with --precision bf16-true.  Without --precision bf16-true, adapter_v2.py micro_batch_size = 1 fails on a 4090 with 24GB of DRAM (so do lora.py and adapter.py).

**Comment by eshoyuan** [comment]
Thank you!
