### ISSUE TITLE
Could you specify the exact memory requirements for Lora/adapter on Llama2-7b?

### ISSUE THREAD

**Issue by zengpeng629** [Lightning-AI/lit-gpt#301]
I attempted to fine-tune Llama2-7b using Lora on a 48G A6000, but failed due to an Out Of Memory  error. Could you provide a table detailing the memory requirements for each popular model?

**Comment by zengpeng629** [comment]
Just successfully using adapter to fine-tune llama2-7b on 40G A100.

Could anyone tell me why it cannot work with lora.py?

**Comment by zengpeng629** [comment]
Fixed the problem by modify the max_length parameter in prepare_alpaca.py according to lit-llama repo.

**Comment by hjeon2k** [comment]
I had a same issue with this. Do you mean block size of 4096 (default in lit_config.json inside llama 2 7B) to 256? Thank you.
