### ISSUE TITLE
Merge lora weights

### ISSUE THREAD

**Issue by zl-liu** [Lightning-AI/lit-gpt#306]
I have:

LoRA weights stored at "lit_model_lora_finetuned.pth"

Base model stored at "checkpoints/meta-llama/Llama-2-7b-chat-hf"

Could you please help explain how to merge the lora weights with the base model to produce the desired combined model? Thank you very much for your help!

**Comment by awaelchli** [comment]
@zl-liu There is currently no such utility. One could be made though, it's relatively easy. You would basically run everything up to this line here: https://github.com/Lightning-AI/lit-gpt/blob/fc4c14d89e62799eeae162548b6aec24f1ab901a/generate/lora.py#L114C1-L114C1
and then `torch.save(filepath, model.state_dict())` to save the merged weights. 

Here is a sketch:
```py
model = GPT(config)
with lazy_load(checkpoint_path) as checkpoint, lazy_load(lora_path) as lora_checkpoint:
    checkpoint.update(lora_checkpoint.get("model", lora_checkpoint))
    model.load_state_dict(checkpoint)
merge_lora_weights(model)

# drop lora params from checkpoint
state_dict = {k: v for k, v in model.state_dict() if "lora" not in key}
# save the merged checkpoint
torch.save("lora_merged_weights", state_dict)
```

**Comment by zl-liu** [comment]
@awaelchli Thank you! I will try to do it based on your suggestions. If it works I will share the code here.

**Comment by timothylimyl** [comment]
@zl-liu I actually made this PR to `lit-llama` awhile ago, I just spotted this repo and will focus on contributing here instead now. You can check it out: https://github.com/Lightning-AI/lit-llama/pull/310

**Comment by awaelchli** [comment]
The code was a sketch. You can just add the missing `.items()` when iterating over the state dict :)

**Comment by carmocca** [comment]
Added in #495
