### ISSUE TITLE
Interactive inference with LoRA

### ISSUE THREAD

**Issue by zl-liu** [Lightning-AI/lit-gpt#307]
I have:

LoRA weights stored at "lit_model_lora_finetuned.pth"

Base model stored at "checkpoints/meta-llama/Llama-2-7b-chat-hf"

I am aware that chat/base.py allows interactive generation. 

How can we do that with LoRA? 

Thank you very much!

**Comment by carmocca** [comment]
You can now merge lora weights into a regular checkpoint: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/finetune_lora.md#merging-lora-weights. Then you'd be able to use the chat script
