### ISSUE TITLE
convert_lit_checkpoint with adapter issue

### ISSUE THREAD

**Issue by zbapt** [Lightning-AI/lit-gpt#313]
Hello, 

I have been trying to fine-tune falcon-7b with your adapter script and my own dataset for more than a week. 
The fine-tuning step seems to be working as it should, as I am getting the lit_model_adapter_finetuned.pth in the out/adapter/ directory in the end.
However, when I tried to make inferences, no differences were observed; meaning that the the answers the questions I asked were exactly the same. Here are the steps I did: 

 ` 1/ python scripts/prepare_my_dataset.py --destination_path data/my_dataset/`

 ` 2/ python finetune/adapter.py --data_dir data/my_dataset/ --checkpoint_dir checkpoints/tiiuae/falcon-7b --out_dir out/adapter/my_dataset/lit_model_adapter_finetuned.pth --precision 16-mixed`

Then I moved the lit_model_adapter_finetuned.pth model into checkpoints/tiiuae/falcon-7b directory, renamed it as lit_model.pth, and did:

  `3/ python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/tiiuae/falcon-7b
`
Finally I made inferences with: 

  `4/ python generate/base.py --prompt "My question here" --checkpoint_dir checkpoints/tiiuae/falcon-7b --strategy fsdp --devices 4 --max_new_tokens 300`

**Question 1**: do you know why my inferences results were always the same?

However, since then, you uploaded a new script: convert_lit_checkpoint.py, to convert a Lit-GPT formatted fodel to its original format. My guess is that it should be replacing my step 3. So I tried:

  `3bis/ python scripts/convert_lit_checkpoint.py --checkpoint_dir=checkpoints/tiiuae/falcon-7b --checkpoint_name=lit_model_adapter_finetuned.pth`

Prior to that last command, I put my lit_model_adapter_finetuned.pth file in checkpoints/tiiuae/falcon-7b, I did not rename it and kept the files that were corresponding to the original falcon checkpoints. But, it does not work, it gets me "error: Unrecognized arguments" for checkpoint_name argument.

**Question 2**: would you have a solution for me to be able to convert the checkpoint with your script, and make inferences (that I hope would be different) ?

Thank you very much

**Comment by carmocca** [comment]
To do inference with the adapter finetuned model, you should use this script: https://github.com/Lightning-AI/lit-gpt/blob/main/generate/adapter.py

**Comment by carmocca** [comment]
It seems like it hanged on launching processes. There might be an issue with your hardware setup. Have you run any distributed scripts before?

7b is not that large, the easiest thing to do would be not to use fsdp. How much GPU memory do you have?

**Comment by zbapt** [comment]
Yes, every inference I made with model (without adapters) was done with distributed scripts, that is why I was confused. 
But thanks, removing the` --strategy fsdp ` worked for me.

**Comment by JustinGoheen** [comment]
@zbapt is this still working for you? if yes, I will close the issue.

**Comment by MrJungle1** [comment]
> To do inference with the adapter finetuned model, you should use this script: https://github.com/Lightning-AI/lit-gpt/blob/main/generate/adapter.py

@zbapt @carmocca @JustinGoheen hello, I have a question, If you need to specify --adapter_path and --checkpoint_dir separately, then what is scripts/convert_lit_checkpoint.py used for? I understand that the base model has added new weights, which is equivalent to a finetuned new model, which can be directly It is used for reasoning, and lit_model_adapter_finetuned.pth should not be needed?

**Comment by zbapt** [comment]
@JustinGoheen yes, it is, thanks

**Comment by MrJungle1** [comment]
@zbapt Do you have a way to combine their weights together，equivalent to a finetuned new model.

**Comment by carmocca** [comment]
Closing since the original issue was resolved.
