### ISSUE TITLE
Unwrap state_dict if the `model` key is present

### ISSUE THREAD

**Issue by JustinGoheen** [Lightning-AI/lit-gpt#322]
As mentioned in https://github.com/Lightning-AI/lit-gpt/issues/318#issuecomment-1652723519, 

> StableLM is gpt-neox based. The issue (#318) arises from converting a checkpoint trained by fabric, where the structure is
> {model: ordinary_state_dict}

the fix is:

> We should unwrap that dict if the "model" key is present

**Comment by carmocca** [comment]
This isn't specific to StableLM, it needs to be done for all checkpoints.

For instance, we load with the reverse logic:

https://github.com/Lightning-AI/lit-gpt/blob/main/generate/base.py#L151

**Comment by awaelchli** [comment]
Forgive me for the question, I'm a bit confused. Shouldn't our convert script put the checkpoints in Fabric's format such that all scripts can either load the converted pretrained models OR a checkpoint from an earlier fabric training? This would seem like the obvious solution to me, but I could be missing something.

**Comment by awaelchli** [comment]
I am mistaken, the convert_lit_checkpoint is for converting away from lit, I confused it with the other direction.
