### ISSUE TITLE
Adding Windows native support

### ISSUE THREAD

**Issue by cristianestojeda** [Lightning-AI/lit-gpt#323]
Currently, the "bitsandbytes" library lacks native Windows support, leading to compatibility issues. We kindly request the development team to address this and enable seamless integration on Windows systems. Users would greatly benefit from a fix that allows them to utilize the library's functionality across different platforms.

Systems runs on Windows 11 with a single gpu RTX 4090.

<img width="1464" alt="bitsandbytes_issue" src="https://github.com/Lightning-AI/lit-gpt/assets/47193156/b07d2d75-2042-4c67-b80a-d88786bea40d">

**Comment by Andrei-Aksionov** [comment]
This is a `bitsandbytes` issue: https://github.com/TimDettmers/bitsandbytes/issues/30
You should try WSL2 and perhaps manually override PyTorch CUDA binaries like in this [comment](https://github.com/Lightning-AI/lit-gpt/issues/278#issuecomment-1645520255).
