### ISSUE TITLE
Error: cutlassF: no kernel found to launch

### ISSUE THREAD

**Issue by PaulCristina** [Lightning-AI/lit-gpt#327]
Encounter an error while trying to run Vicuna model:

`
:~/workspace/lit-gpt$ python chat/base.py --checkpoint_dir checkpoints/lmsys/vicuna-7b-v1.3
Loading model 'checkpoints/lmsys/vicuna-7b-v1.3/lit_model.pth' with {'org': 'lmsys', 'name': 'vicuna-7b-v1.3', 'block_size': 2048, 'vocab_size': 32000, 'padding_multiple': 64, 'padded_vocab_size': 32000, 'n_layer': 32, 'n_head': 32, 'n_embd': 4096, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'n_query_groups': 32, 'shared_attention_norm': False, '_norm_class': 'RMSNorm', 'norm_eps': 1e-06, '_mlp_class': 'LLaMAMLP', 'intermediate_size': 11008, 'condense_ratio': 1}
>> Prompt: how is the weather?
>> Reply: Traceback (most recent call last):
  File "/home/jovyan/workspace/lit-gpt/chat/base.py", line 302, in <module>
    CLI(main)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/home/jovyan/workspace/lit-gpt/chat/base.py", line 190, in main
    tokens_generated = decode(fabric, tokenizer, y)
  File "/home/jovyan/workspace/lit-gpt/chat/base.py", line 109, in decode
    for token in token_stream:
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/home/jovyan/workspace/lit-gpt/chat/base.py", line 61, in generate
    logits = model(idx.view(1, -1), max_seq_length, input_pos)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/lightning/fabric/wrappers.py", line 116, in forward
    output = self._forward_module(*args, **kwargs)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/workspace/lit-gpt/lit_gpt/model.py", line 107, in forward
    x, self.kv_caches[i] = block(x, (cos, sin), max_seq_length, mask, input_pos, self.kv_caches[i])
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/workspace/lit-gpt/lit_gpt/model.py", line 168, in forward
    h, new_kv_cache = self.attn(n_1, rope, max_seq_length, mask, input_pos, kv_cache)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/saturncloud/envs/saturn/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/jovyan/workspace/lit-gpt/lit_gpt/model.py", line 247, in forward
    y = self.scaled_dot_product_attention(q, k, v, mask=mask)
  File "/home/jovyan/workspace/lit-gpt/lit_gpt/model.py", line 273, in scaled_dot_product_attention
    return torch.nn.functional.scaled_dot_product_attention(
RuntimeError: cutlassF: no kernel found to launch!`

Maybe is related to some installation issue?
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
s3fs 2022.3.0 requires fsspec==2022.3.0, but you have fsspec 2023.6.0 which is incompatible.`

**Comment by ValeKnappich** [comment]
Same problem here. Strictly followed the installation steps in a fresh conda env with Python 3.10. The error occurs in chat/base.py aswell as generate/base.py and across models. 

Here is my pip list:
```bash
Package             Version
------------------- -----------------------
aiohttp             3.8.5
aiosignal           1.3.1
annotated-types     0.5.0
anyio               3.7.1
arrow               1.2.3
async-timeout       4.0.2
attrs               23.1.0
backoff             2.2.1
beautifulsoup4      4.12.2
bitsandbytes        0.41.0
blessed             1.20.0
certifi             2023.7.22
charset-normalizer  3.2.0
click               8.1.6
croniter            1.4.1
datasets            2.14.1
dateutils           0.6.12
deepdiff            6.3.1
dill                0.3.7
docstring-parser    0.15
exceptiongroup      1.1.2
fastapi             0.100.1
filelock            3.9.0
frozenlist          1.4.0
fsspec              2023.4.0
h11                 0.14.0
huggingface-hub     0.16.4
idna                3.4
importlib-resources 6.0.0
inquirer            3.1.3
itsdangerous        2.1.2
Jinja2              3.1.2
jsonargparse        4.23.0
lightning           2.1.0.dev0
lightning-cloud     0.5.37
lightning-utilities 0.9.0
markdown-it-py      3.0.0
MarkupSafe          2.1.2
mdurl               0.1.2
mpmath              1.2.1
multidict           6.0.4
multiprocess        0.70.15
networkx            3.0rc1
numpy               1.25.1
ordered-set         4.1.0
packaging           23.1
pandas              2.0.3
pip                 23.2.1
psutil              5.9.5
pyarrow             12.0.1
pydantic            2.0.3
pydantic_core       2.3.0
Pygments            2.15.1
PyJWT               2.8.0
python-dateutil     2.8.2
python-editor       1.0.4
python-multipart    0.0.6
pytorch-lightning   2.0.6
pytorch-triton      2.1.0+9e3e10c5ed
pytz                2023.3
PyYAML              6.0.1
readchar            4.0.5
requests            2.31.0
rich                13.4.2
scipy               1.11.1
sentencepiece       0.1.99
setuptools          68.0.0
six                 1.16.0
sniffio             1.3.0
soupsieve           2.4.1
starlette           0.27.0
starsessions        1.3.0
sympy               1.11.1
tokenizers          0.13.3
torch               2.1.0.dev20230728+cu118
torchmetrics        1.0.1
tqdm                4.65.0
traitlets           5.9.0
typeshed-client     2.3.0
typing_extensions   4.7.1
tzdata              2023.3
urllib3             2.0.4
uvicorn             0.23.1
wcwidth             0.2.6
websocket-client    1.6.1
websockets          11.0.3
wheel               0.38.4
xxhash              3.2.0
yarl                1.9.2
zstandard           0.21.0
```

**Comment by Andrei-Aksionov** [comment]
I also noticed that yesterday. I think it's an issue in PyTorch itself as we are installing the latest nightly version.
We need a nightly because torch 2.1 (which is not yet out) contains desired functionality (like flash attention if I'm not mistaken). 

As a quick fix try to install previous versions of PyTorch nightly:
```bash
pip install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch==2.1.0.dev20230703'
```
This is the version that is installed on my machine. Or you can try a different one (as you can see the version is a date).


@carmocca @awaelchli  I think it should be addressed. Blindly relying on a nightly version is not a good thing in my opinion.

**Comment by bkowshik** [comment]
Do we have a solution for this?

Had this error today with the Llama 2 model: https://github.com/Lightning-AI/lit-gpt/issues/354

**Comment by gn64** [comment]
In my environment, set
torch.backends.cuda.enable_mem_efficient_sdp(False)
in addition to
torch.backends.cuda.enable_flash_sdp(False)
improved situation.

**Comment by carmocca** [comment]
https://github.com/pytorch/pytorch/issues/102029#issuecomment-1560071148 suggests that it is related to using bf16 precision. Can somebody try precision 32?

**Comment by Andrei-Aksionov** [comment]
With `bf16` it works without raising that error. The problem is that the code tries to use `bf16` even with `Nvidia T4` which doesn't support it.
On `A10G` chat works without errors, but the quality of the generated text has dropped significantly:

```python
main ~/repos/lit-gpt python chat/base.py --checkpoint_dir checkpoints/EleutherAI/pythia-410m --precision bf16-true
Loading model 'checkpoints/EleutherAI/pythia-410m/lit_model.pth' with {'org': 'EleutherAI', 'name': 'pythia-410m', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 128, 'padded_vocab_size': 50304, 'n_layer': 24, 'n_head': 16, 'n_embd': 1024, 'rotary_percentage': 0.25, 'parallel_residual': True, 'bias': True, 'n_query_groups': 16, 'shared_attention_norm': False, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 4096, 'condense_ratio': 1}
>> Prompt: hello
>> Reply: ": :mock_request,
                        "json_errors": "Error response from server: 500 (Internal Server Error)",
                        "error_messages": [
                          "Upgrade: JWT issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk issuer: jwk: jwk issuer:jwk: jwk issuerwk:jwk:jwkjwk:jjkjwkjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj^C
```

The above text was generated on `A10G` with `torch==2.1.0.dev20230810+cu118`.
And this what I get with the older version `torch==2.1.0.dev20230703+cu118`:

```python
main ~/repos/lit-gpt python chat/base.py --checkpoint_dir checkpoints/EleutherAI/pythia-410m --precision bf16-true          
Loading model 'checkpoints/EleutherAI/pythia-410m/lit_model.pth' with {'org': 'EleutherAI', 'name': 'pythia-410m', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 128, 'padded_vocab_size': 50304, 'n_layer': 24, 'n_head': 16, 'n_embd': 1024, 'rotary_percentage': 0.25, 'parallel_residual': True, 'bias': True, 'n_query_groups': 16, 'shared_attention_norm': False, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 4096, 'condense_ratio': 1}
>> Prompt: hello
>> Reply: ," I thought, although my breath was short and shallow, I was suddenly in a world of pain and adrenaline.
 I was a do not touch kind of girl who often left my father in the drivers seat.
She was a nice girl when she was a little girl, but she is now a very happy woman because she no longer is afraid of the dark and wants to be near a light.
I can't take her out with me. . . .

I turned on the TV to watch a show about small pets, and watched the screen to my embarrassment. There was a moment of shame in my heart, but I pushed away the words, and pulled the covers up to my chin. My eyes drooped. I felt sick.

"It's okay, I'll be right back." The strange feeling that I got when she was with me was gone. In a way, it made me feel happy to hear her voice, but it made me realize that I didn't want to see her again.

"Mom, you're getting better. And I have a feeling it can only help you."

"You're not the first one."

"You've had a rough life, but you don't have to worry about what's going to happen to you. You have your mother, and we have your Dad. You're going to be okay."
```

**Comment by carmocca** [comment]
@Andrei-Aksionov Can you try a larger (3B+) instruction finetuned model? I don't trust the output of the smaller pretrained pythia models, they often output garbage. I recommend using a simple testing prompt like "The letters of the alphabet in order are:" instead of a prompt like "hello", especially with pretrained models

**Comment by Andrei-Aksionov** [comment]
Model: Pythia-2.8b
Seed: fixed
Precision: bf16-true

----

Pytorch: `20230811` (the newest one)

```python
⚡ main ~/repos/lit-gpt python chat/base.py --checkpoint_dir checkpoints/EleutherAI/pythia-2.8b --precision bf16-true           
Global seed set to 1337
Loading model 'checkpoints/EleutherAI/pythia-2.8b/lit_model.pth' with {'org': 'EleutherAI', 'name': 'pythia-2.8b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 128, 'padded_vocab_size': 50304, 'n_layer': 32, 'n_head': 32, 'n_embd': 2560, 'rotary_percentage': 0.25, 'parallel_residual': True, 'bias': True, 'n_query_groups': 32, 'shared_attention_norm': False, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 10240, 'condense_ratio': 1}
>> Prompt: The letters of the alphabet in order are:
>> Reply: 

A B C D E F G H I J K L M N O P Q R S T U V W X Y Z

The years of the Zodiac are:

Aries: April 20 - May 20

Taurus: May 21 - June 21

Gemini: June 22 - July 22

Cancer: July 23 - August 22

Leo: August 23 - September 22

Virgo: September 23 - October 22

Libra: October 23 - November 21

Scorpio: November 22 - December 21

Sagittarius: December 22 - January 20

Capricorn: January 21 - February 18

Aquarius: February 19 - March 20

Pisces: March 21 - April 20

Each year has twelve months, each of which is divided into the number of days it contains (for instance, one year is divided into 12 months, and 12 of these are divided into the number of days in each month).

Sometimes in everyday life we use "year" to mean a whole number, rather than using the word "day" to mean the amount of time in a day. For example, "This is the year three hundred and seven."
```

---

Pytorch: `20230703`

```python
⚡ main ~/repos/lit-gpt python chat/base.py --checkpoint_dir checkpoints/EleutherAI/pythia-2.8b --precision bf16-true          
Global seed set to 1337
Loading model 'checkpoints/EleutherAI/pythia-2.8b/lit_model.pth' with {'org': 'EleutherAI', 'name': 'pythia-2.8b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 128, 'padded_vocab_size': 50304, 'n_layer': 32, 'n_head': 32, 'n_embd': 2560, 'rotary_percentage': 0.25, 'parallel_residual': True, 'bias': True, 'n_query_groups': 32, 'shared_attention_norm': False, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 10240, 'condense_ratio': 1}
>> Prompt: The letters of the alphabet in order are:
>> Reply: 

A.

B.

C.

D.

E.

F.

G.

H.

I.

J.

K.

L.

M.

N.

O.

P.

Q.

R.

S.

T.

U.

V.

W.

X.

Y.

Z.

ADDITIONAL NOTES:

As a sign of good luck, a well-placed "C" will make it easier for you to find what you're looking for.

For the same reason, a well-placed "Q" is better than a "W" or "J."

According to some people, the "U" represents the number 7, and it's good luck when you find it on a mail box, or in a newspaper, book, or certificate.

Often there's more than one "Q" symbol on a letter or word.

When you know what letter it is and what it means, call it by its name:

A.



B.


C.

D.

E.

F.

G.

H.

I.

J.
K.
L
M
N.
O.
P.
Q.
R.
S.T.U
V.W.X.Y.
Z.


ADDITIONAL NOTES:


As a sign of good luck, a well-placed "C" will make it easier for you to find what you're looking for.

For the same reason, a well-placed "Q" is better than a "W" or "J."



According to some people, the "U" represents the number 7, and it's good luck when you find it on a mail box, or in a newspaper, book, certificate.


Often there's more than one "Q" symbol on a letter or word.


When you know what letter it is and what it means, call it by its name:
A.
B.



C.


D.

E.

F.

G.
H
I.
J.K.
L
M.N.O
P.
Q.R.R.S.T.U
V.WX.Y.Z.


ADDITIONALSO
```

---

So as you can see the response with the newest version to my eye looks even better.
The only question: why with previous (a month old) version of PyTorch generation with `bf16-true` on a Nvidia T4 (that doesn't support this precision) is possible, while with the newest one - not?

**Comment by carmocca** [comment]
(Copy pasting @Andrei-Aksionov's answere from #408 here)

Actually it seems like the problem is in the precision (it's `bf16-true` by default) which is not supported by many popular graphics cards like T4 or V100.
And previous versions of PyTorch-nightly for some reason didn't care about wrongly provided precision at all.

So try to solve it in that order:
1. Use the proper precision for your graphics card. [Here](https://github.com/Lightning-AI/lit-gpt/blob/96d66b4845ebe287b5dd57b45e584b38d4f660e7/lit_gpt/speed_monitor.py#L17-L57) you can find what precisions are supported. 
    Hint: use `--precision` CLI argument in order to use it:
    ```bash
    python generate/base.py --prompt "Hello, my name is" --checkpoint_dir ./stablelm-base-alpha-3b --precision 32-true
    ```
3. If the above didn't help try to install the previous version of PyTorch-nightly (perhaps try with a clean venv):
    ```bash
    pip install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch==2.1.0.dev20230703'
    ```

**Comment by JerryDaHeLian** [comment]
However, there is still the following error:
RuntimeError: Expected x1.dtype() == cos.dtype() to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
who can help me?

**Comment by linxOD** [comment]
> ```shell
> .1.0.dev20230728+cu118
> ```

I had the same issue even with torch nightly v2.1.3.
Fixed by adding the above lines.

**Comment by ApolloRay** [comment]
> ```shell
> pip install --index-url https://download.pytorch.org/whl/nightly/cu118 --pre 'torch==2.1.0.dev20230703'
> ```

but cuda oom
