### ISSUE TITLE
[TPU] generate scripts are not working

### ISSUE THREAD

**Issue by gkroiz** [Lightning-AI/lit-gpt#334]
Currently, if you run the generate scripts on TPUs the code will error out with the following:
```
Traceback (most recent call last):
  File "generate/base.py", line 212, in <module>
    CLI(main)
  File "/home/gersonkroiz/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 82, in CLI
    return _run_component(component, cfg_init)
  File "/home/gersonkroiz/.local/lib/python3.8/site-packages/jsonargparse/cli.py", line 147, in _run_component
    return component(**cfg)
  File "generate/base.py", line 183, in main
    y = generate(
  File "/home/gersonkroiz/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "generate/base.py", line 88, in generate
    xm.mark_step()
  File "/home/gersonkroiz/.local/lib/python3.8/site-packages/torch_xla/core/xla_model.py", line 806, in mark_step
    torch_xla._XLAC._xla_step_marker(
RuntimeError: Error while lowering: [] aten::mul, xla_shape=f32[1,32,5,32]{3,2,1,0}
Error: torch_xla/csrc/convert_ops.cpp:86 : Unsupported XLA type 10
Frames:
```
 Unsupported XLA type 10 is `FP16`, meaning this is related to precision. I know in other scripts, such as finetuning [`full.py`](https://github.com/Lightning-AI/lit-gpt/blob/main/finetune/full.py#L52-L53) we will automatically convert the precision to `32-true` when using TPUs. I tested `32-true` precision for the generate script and it was able to run as expected.

Also tried changing model's precision before generate loop happens via `model = model.to(torch.float32)`. This did not resolve the issue.

What doesn't work:
```
PJRT_DEVICE=TPU python3 generate/base.py
XLA_USE_BF16=1 PJRT_DEVICE=TPU python3 generate/base.py
```
What works:
```
XLA_USE_BF16=1 PJRT_DEVICE=TPU python3 generate/base.py --precision 32-true
```

Noteable features of work environment:
Hardware: TPU v4-8
Pytorch & Pytorch XLA versions: nightly

**Comment by gkroiz** [comment]
I tested whether this issue exists when using an older commit I am more familiar with, `e38704e6d1fdeda2d84d53e8f29b2b28d4fb7d84`. After adding `org`, `name`, and `bias` to the Config file, the older commit worked out of the box without the issue above. I also changed https://github.com/Lightning-AI/lit-gpt/blob/e38704e6d1fdeda2d84d53e8f29b2b28d4fb7d84/generate.py#L118 so that dtype=`torch.bfloat16` even on tpu. Even with the precision change here, the generate worked without any issue with lowering ops.

**Comment by gkroiz** [comment]
This is not reproducible on main, will close for now. Sorry for the confusion

**Comment by carmocca** [comment]
@gkroiz I sthis also why you did https://github.com/Lightning-AI/lit-gpt/compare/main...gkroiz:lit-gpt:benchmarking_clean#diff-1b095803517cb7e7f659416dc185cdf79abb0c05b68e1ac3601d4c4f77c921c8R265-R269 or is that a separate problem?

**Comment by gkroiz** [comment]
> @gkroiz Is this also why you did [main...gkroiz:lit-gpt:benchmarking_clean#diff-1b095803517cb7e7f659416dc185cdf79abb0c05b68e1ac3601d4c4f77c921c8R265-R269](https://github.com/Lightning-AI/lit-gpt/compare/main...gkroiz:lit-gpt:benchmarking_clean#diff-1b095803517cb7e7f659416dc185cdf79abb0c05b68e1ac3601d4c4f77c921c8R265-R269) or is that a separate problem?

At the time I added this I was seeing precision issues with q,k,v. I'm not sure if they are still there since there were a lot of moving pieces, this will need to be double checked.

**Comment by carmocca** [comment]
https://github.com/Lightning-AI/lit-gpt/pull/480 with sequential loading and `precision bf16-true` is still not showing this issue

**Comment by carmocca** [comment]
Closing until further evidence of a bug appears
