### ISSUE TITLE
[Question] Concatenation of input_ids across documents/data points for training

### ISSUE THREAD

**Issue by jaykasundra2** [Lightning-AI/lit-gpt#338]
I see that the encoded input_ids of the training corpus is concatenated to create one large array and then broken into chunks of equal sizes which could include multiple documents/data points. My question is, wouldn’t this confuse model while doing next token prediction because the context could be spanning across multiple documents in a chunk (even though the boundaries are marked with ‘bos’ or ‘eos’ tokens)

**Comment by carmocca** [comment]
The assumption is that the model will learn to attend to those tokens within the relevant chunk by recognizing the boundaries. But I don't know of any papers that have validated this.
