### ISSUE TITLE
Wrong starlette version (BUG in setup)

### ISSUE THREAD

**Issue by kripper** [Lightning-AI/lit-gpt#339]
### Bug description

I installed from scratch on a OL8 following README and got this error:

`ContextualVersionConflict: (starlette 0.31.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('starlette<0.28.0,>=0.27.0'), {'fastapi'}). HINT: Try running `pip install -U 'lightning>=2.1.0.dev0'`
`

The hint doesn't work, but also replaces `lightning` module installed via `lit-gpt/requirements.txt`

To solve, I used:

`pip3.8 install "starlette<0.28.0,>=0.27.0"`

Besides, you should make clear that only Python 3.8 is supported (Python 3.9 doesn't have some required versions, at least on OL8).

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
Follow README
```

### Error messages and logs

```
ContextualVersionConflict: (starlette 0.31.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('starlette<0.28.0,>=0.27.0'), {'fastapi'}). HINT: Try running `pip install -U 'lightning>=2.1.0.dev0'`
```

**Comment by carmocca** [comment]
We will soon avoid installing `starlette` in lit-gpt: https://github.com/Lightning-AI/lightning/pull/18386

Closing this issue, since the changes will happen in `lightning`
