### ISSUE TITLE
How can we provide custom embeddings to falcon 40 b on a  new dataset

### ISSUE THREAD

**Issue by Kaustha** [Lightning-AI/lit-gpt#342]
what type of word embeddings falcon 40b uses?. How can we provide custom embeddings to falcon 40 b on new dataset

Can you provide any eg / link it will be useful as i m new to this field

**Comment by lynngao** [comment]
I have tried with using falcon 40b with semantic search, and it doesn't matter what embeddings you use. I gave tried with both text-ada-embedding-002 and instructor-large they both work fine.
