### ISSUE TITLE
Conversion Lit GPT (Llama-2-7b-chat-hf) to original model

### ISSUE THREAD

**Issue by solablue** [Lightning-AI/lit-gpt#347]
Hi! Thanks for the new commits on the issue #340 . I ran the code as you suggested, but got this error.

`TypeError: copy_weights_llama() got multiple values for argument 'saver'
`

I tried with another checkpoint files but it is still the same. Please let me know what I should do. Thank you!

**Comment by JustinGoheen** [comment]
Thank you for raising this issue @solablue. This will be fixed in the linked PR.

**Comment by solablue** [comment]
Hi, thanks for the update. But still facing the error below.

```
Traceback (most recent call last):
  File "/content/lit-parrot/scripts/convert_lit_checkpoint.py", line 237, in <module>
    CLI(convert_lit_checkpoint, as_positional=False)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 85, in CLI
    return _run_component(component, cfg_init)
  File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 147, in _run_component
    return component(**cfg)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/lit-parrot/scripts/convert_lit_checkpoint.py", line 229, in convert_lit_checkpoint
    copy_fn(sd, lit_weights, saver=saver)
  File "/content/lit-parrot/scripts/convert_lit_checkpoint.py", line 135, in copy_weights_llama
    to_name = weight_map[from_name]
KeyError: 'transformer.h.{}.attn.gating_factor'

```

I think someone else on [Discord](https://discordapp.com/channels/1077906959069626439/1105501395207065802/1136615548990533642) is also facing the same issue.

**Comment by JustinGoheen** [comment]
Hi @solablue have you updated to the most recent commit on main?

I ask because I retrieved Llama-2-7b-chat-hf, converted it to Lit-GPT format, and then ran the following on the [fix-347 branch](https://github.com/Lightning-AI/lit-gpt/tree/justin/fix-347) and it was okay.

```sh
python3 scripts/convert_lit_checkpoint.py \                                                                       
    --checkpoint_name lit_model.pth \
    --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-chat-hf 
```

**Comment by JustinGoheen** [comment]
opening a new issue for this

> Hi, thanks for the update. But still facing the error below.
> 
> ```
> Traceback (most recent call last):
>   File "/content/lit-parrot/scripts/convert_lit_checkpoint.py", line 237, in <module>
>     CLI(convert_lit_checkpoint, as_positional=False)
>   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 85, in CLI
>     return _run_component(component, cfg_init)
>   File "/usr/local/lib/python3.10/dist-packages/jsonargparse/_cli.py", line 147, in _run_component
>     return component(**cfg)
>   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/content/lit-parrot/scripts/convert_lit_checkpoint.py", line 229, in convert_lit_checkpoint
>     copy_fn(sd, lit_weights, saver=saver)
>   File "/content/lit-parrot/scripts/convert_lit_checkpoint.py", line 135, in copy_weights_llama
>     to_name = weight_map[from_name]
> KeyError: 'transformer.h.{}.attn.gating_factor'
> ```
> 
> I think someone else on [Discord](https://discordapp.com/channels/1077906959069626439/1105501395207065802/1136615548990533642) is also facing the same issue.
