### ISSUE TITLE
Quantization doesn't work for LoRA layers

### ISSUE THREAD

**Issue by Andrei-Aksionov** [Lightning-AI/lit-gpt#352]
Right now the code uses monkey patching in order to replace the link to `torch.nn.Linear` with `Linear4bit` (from bitsandbytes) inside context managed ([code](https://github.com/Lightning-AI/lit-gpt/blob/cf5542a166d71c0026b35428113092eb41029a8f/lit_gpt/utils.py#L27-L83)) so every time, inside context manager, when a new layer is created from `nn.Linear` actually it's a `Linear4bit`.

But in LoRA layers instead of calling `torch.nn.Linear` directly a `super()` method is [used](https://github.com/Lightning-AI/lit-gpt/blob/main/lit_gpt/lora.py#L122). I believe `super` stores links to the bases classes and these links are populated during import time, so monkey patching doesn't affect them. 
As a result despite using quantize context manager all LoRA layers use regular `nn.Linear` layers.

**Comment by Andrei-Aksionov** [comment]
Right now if to print out dtypes (on a machine with a GPU) while running `finetune/lora.py` with default parameters this is what you get:

```text
_forward_module.lm_head.weight ------------------------------ torch.float16
_forward_module.transformer.wte.weight ---------------------- torch.float16
_forward_module.transformer.h.0.norm_1.weight --------------- torch.float16
_forward_module.transformer.h.0.norm_1.bias ----------------- torch.float16
_forward_module.transformer.h.0.attn.attn.weight ------------ torch.float16
_forward_module.transformer.h.0.attn.attn.bias -------------- torch.float16
_forward_module.transformer.h.0.attn.attn.lora_A ------------ torch.float16
_forward_module.transformer.h.0.attn.attn.lora_B ------------ torch.float16
_forward_module.transformer.h.0.attn.proj.weight ------------ torch.float16
_forward_module.transformer.h.0.attn.proj.bias -------------- torch.float16
_forward_module.transformer.h.0.norm_2.weight --------------- torch.float16
_forward_module.transformer.h.0.norm_2.bias ----------------- torch.float16
_forward_module.transformer.h.0.mlp.fc.weight --------------- torch.uint8
_forward_module.transformer.h.0.mlp.fc.bias ----------------- torch.float16
_forward_module.transformer.h.0.mlp.proj.weight ------------- torch.uint8
_forward_module.transformer.h.0.mlp.proj.bias --------------- torch.float16
```
Only `fc` and `proj` parameters from MLP layer are quantized and this is because by default LoRA is not applied to MLP and thus regular MLP from `lit_gpt/model.py` is used. As soon as you set `to_mlp=True` weights will not be quantized too.

**Comment by Andrei-Aksionov** [comment]
So the solution might be to call `nn.Linear` directly in `LoRALayer` instead of [super](https://github.com/Lightning-AI/lit-gpt/blob/cf5542a166d71c0026b35428113092eb41029a8f/lit_gpt/lora.py#L122) and this will call [QuantizedLinear](https://github.com/Lightning-AI/lit-gpt/blob/cf5542a166d71c0026b35428113092eb41029a8f/lit_gpt/utils.py#L56) class (as inside quantize context manager the link `torch.nn.Linear` now leads to `QuantizedLinear`) but this leads to another problem in [this line](https://github.com/Lightning-AI/lit-gpt/blob/cf5542a166d71c0026b35428113092eb41029a8f/lit_gpt/utils.py#L58):
> super(type, obj): obj must be an instance or subtype of type

And if to stop during debugging at the [line](https://github.com/Lightning-AI/lit-gpt/blob/cf5542a166d71c0026b35428113092eb41029a8f/lit_gpt/utils.py#L58) to print out:
```python
1. > self
<lit_gpt.lora.LoRALinear object at 0x11eea1e70>
2. > for base in self.__class__.__bases__: print(base): 
<class 'torch.nn.modules.linear.Linear'>
<class 'lit_gpt.lora.LoRALayer'>
3. > for _mro in self.__class__.mro(): print(_mro)
<class 'lit_gpt.lora.LoRALinear'>
<class 'torch.nn.modules.linear.Linear'>
<class 'torch.nn.modules.module.Module'>
<class 'lit_gpt.lora.LoRALayer'>
<class 'object'>
```

which is pretty weird for me. `self` inside QuantizedLinear class is from another class.
Monkey patching is a an uncharted territory for me so any help if highly welcomed.

**Comment by awaelchli** [comment]
In lit-llama, we did it like this:
https://github.com/Lightning-AI/lit-llama/blob/da71adea0970d6d950fb966d365cfb428aef8298/lit_llama/lora.py#L134-L135
Someone must have updated it to super(). 

Can you give this a try?

**Comment by Andrei-Aksionov** [comment]
> Someone must have updated it to super().

I know that [someone](https://github.com/Lightning-AI/lit-gpt/pull/262) 😄.
So the fix essentially turned off quantization for LoRALinear so that explains why there were no error.

---

if you call `nn.Linear.__init__(...)` then you get the error I described in the previous comment.

**Comment by carmocca** [comment]
@rasbt This bug is probably impacting #275 so I would expect that memory usage decreases after #388 lands
