### ISSUE TITLE
Progress bar dump during download of weights

### ISSUE THREAD

**Issue by bkowshik** [Lightning-AI/lit-gpt#353]
Running the command inside a Jupyter notebook will pollute with lots of progress bar logs.

```bash
python scripts/download.py --repo_id meta-llama/Llama-2-7b-chat-hf --token your_hf_token
```

<img width="1280" alt="Screenshot 2023-08-04 at 01 12 39" src="https://github.com/Lightning-AI/lit-gpt/assets/2899501/ebbdf5c6-cec1-4681-8170-e964fe38b4fa">

<img width="1280" alt="Screenshot 2023-08-04 at 01 12 22" src="https://github.com/Lightning-AI/lit-gpt/assets/2899501/63ae4c70-3651-454b-a03e-4ac70bb2766e">

**Comment by carmocca** [comment]
Thanks @aniketmaurya! I don't think we need to make this a command line option.
