### ISSUE TITLE
reset_cache() Decrease the Generation Quality of Consecutive Inputs

### ISSUE THREAD

**Issue by HenryPengZou** [Lightning-AI/lit-gpt#365]
When conducting generation for multiple consecutive inputs on a LoRA fine-tuned LLaMA, I noticed that using 'reset_cache' after each generation for one input will affect the generation quality on the next input. However, if you load the model again after each generation, the quality of generated contents stays good. But reloading consumes lots of time. Could you help provide some explanation why 'reset_cache' will decrease the performance of the generation on the next consecutive inputs?

Code: I modified the code of 'generate/lora.py' to enable consecutive generation on multiple inputs. Basically, just add a for loop and model.reset_cache()

``` python
  # support multiple inference 
  outputs = []
  num_samples = len(input)
  for i in range(num_samples):
      sample = {"instruction": prompt[i], "input": input[i]}
      prompt = generate_prompt(sample)
      encoded = tokenizer.encode(prompt, bos=True, eos=False, device=model.device)

      t0 = time.perf_counter()
      output = generate(
          model,
          idx=encoded,
          max_new_tokens=max_new_tokens,
          temperature=temperature,
          top_k=top_k,
          eos_id=tokenizer.eos_id
      )
      t = time.perf_counter() - t0

      model.reset_cache()
      output = tokenizer.decode(output)
      output = output.split("### Response:")[1].strip()
      print(output)
      print(f"Time for inference: {t:.02f} sec total, {max_new_tokens / t:.02f} tokens/sec", file=sys.stderr)
      outputs.append(output)
```

**Comment by carmocca** [comment]
`model.reset_cache()` every sample generation should be faster than recreating the model plus loading its state dict. If you are not seeing this, I would suggest that you [profile](https://www.youtube.com/watch?v=qRZrVNNe3gQ) the code to find out where the slowdown is coming from

**Comment by HenryPengZou** [comment]
Thanks for the quick reply. Yes, using model.reset_cache() for every sample generation avoids loading model every time and  is indeed much faster. However, what I noticed is that the quality of generated texts is only good for the first input but very bad for the second, third, ..., inputs. But if I reload the model after each generation, the quality of generated contents is great for each input. 

Besides, my prompts has to be changed with different inputs, so each input has a different prompt. Is this changing prompt causing the generation quality issue?

**Comment by carmocca** [comment]
That's strange. Can you share some steps for us to reproduce the issue?
