### ISSUE TITLE
llama2-7b finetune/lora.py fails

### ISSUE THREAD

**Issue by MrJungle1** [Lightning-AI/lit-gpt#366]
When I execute finetune/lora.py on llama2-7b and set the devices to 8, I get the following error
![企业微信截图_16913941378847](https://github.com/Lightning-AI/lit-gpt/assets/43968255/bad556be-11b3-4787-90af-8a510525091f)

**Comment by carmocca** [comment]
What's the error if you set `CUDA_LAUNCH_BLOCKING=1` as the error stacktrace suggests?

**Comment by MrJungle1** [comment]
@carmocca hello，Below are the errors when I set CUDA_LAUNCH_BLOCKING=1, they are too long so I pasted part of them
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/329bf414-b43c-4a9c-886a-0df02bacbcf0)
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/a3c6f111-a03c-4d78-ac82-e8460c829fb0)

**Comment by carmocca** [comment]
I believe I've seen this error if the data was tokenized with a different tokenizer. Are you using `prepare_alpaca.py`? Does this error not happen with a single device?

**Comment by MrJungle1** [comment]
Yes, I execute python scripts/prepare_alpaca.py first

**Comment by MrJungle1** [comment]
@carmocca Thanks for your reply, I re-executed the python scripts/prepare_alpaca.py --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf/ to solve this problem, because the --checkpoint_dir I used before is checkpoints/meta -llama/Llama-2-7b-hf/checkpoints/EleutherAI/pythia-1b
