### ISSUE TITLE
convert_lit_checkpoint with full issue

### ISSUE THREAD

**Issue by MrJungle1** [Lightning-AI/lit-gpt#371]
I use finetune/full.py to finetune llama2-7b, get lit_model_finetuned.pth, and copy it to checkpoints/meta-llama/Llama-2-7b-hf, but when I execute python scripts/convert_lit_checkpoint.py - -checkpoint_name lit_model_finetuned.pth --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf/, the following error occurs. and my environment follows the tutorial step by step.
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/b3f3fe7f-4770-4ab2-afb8-c3c933352494)

**Comment by carmocca** [comment]
Can you share the output of `pip list`?

**Comment by MrJungle1** [comment]
@carmocca 
hello this is the pip list
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/0742f8c7-4609-4579-bdcf-35bc6790bf72)
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/23c9dc7d-e658-44b5-997f-7661b1aee992)
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/7fb9e7b5-6512-4881-88e8-ecebd92a4ca9)

**Comment by carmocca** [comment]
Thanks. Something might've broken with the latest PyTorch nightly. I'll try to reproduce it with your precise torch installation
