### ISSUE TITLE
Converting models to original format after finetuning wit LoRA and QLoRA

### ISSUE THREAD

**Issue by JustinGoheen** [Lightning-AI/lit-gpt#374]
User raised issued regarding KeyError after finetuning with LoRA in the following comment: https://github.com/Lightning-AI/lit-gpt/issues/355#issuecomment-1668854378

**Comment by MrJungle1** [comment]
Hello! @JustinGoheen  May I ask if there is any new development, I have been concerned about the latest developments about it, because it is very important to me.

**Comment by JustinGoheen** [comment]
@MrJungle1 @solablue a new model must be created. as mentioned here -> https://github.com/Lightning-AI/lit-gpt/issues/183#issuecomment-1618843317 and here -> https://github.com/Lightning-AI/lit-gpt/issues/183#issuecomment-1619103370

**Comment by JustinGoheen** [comment]
@MrJungle1 @solablue can each of you please let me know which features of HF models you are interested in using after converting back to the original format. thank you.

**Comment by MrJungle1** [comment]
@JustinGoheen Thank you for your patient reply. For example, I want to evaluate the ability of different base models and fine-tuned models. Hugging face has a corresponding leaderboard, which needs to use hf format.

**Comment by solablue** [comment]
@JustinGoheen I would like upload my finetuned model based on Llama-2-7b-chat-hf on Huggingface to create a web demo.

**Comment by MrJungle1** [comment]
@JustinGoheen LGTM! looking forward to your realization

**Comment by zl-liu** [comment]
@JustinGoheen Thank you! That would be wonderful.

**Comment by zl-liu** [comment]
I agree with @MrJungle1 and @solablue that this is a very important feature because the majority of users in the community need to interact with the Hugging Face eco system.

**Comment by carmocca** [comment]
@JustinGoheen The lora weights need to be loaded (they are in the lora checkpoint file) into the model before calling merge. See for instance my snippet in https://github.com/Lightning-AI/lit-gpt/pull/362#discussion_r1298694156

**Comment by JustinGoheen** [comment]
@solablue @MrJungle1 I am going to implement an option to merge while converting in PR https://github.com/Lightning-AI/lit-gpt/pull/362

**Comment by JustinGoheen** [comment]
PR https://github.com/Lightning-AI/lit-gpt/pull/362 enables conversion. Please be sure to read the [convert_lit_models](https://github.com/Lightning-AI/lit-gpt/blob/justin/update-tutorial/tutorials/convert_lit_models.md) tutorial on the associated working branch.

**Comment by Vinter8848** [comment]
I have merged the lora weights  before conversion. like this: 

> lit-gpt/out/lora/Llama-2-7b-hf/lora_model_merged.pth（25.12GB）

After I ran the commnd:
`python /home/Zhengwt/lit-gpt/scripts/convert_lit_checkpoint.py`
`--checkpoint_name lora_model_merged.pth \`
`--out_dir /home/Zhengwt/lit-gpt/out/lora/Llama-2-7b-hf \`
`--model_name Llama-2-7b-hf`

> Traceback (most recent call last):
  File "/home/Zhengwt/lit-gpt/scripts/convert_lit_checkpoint.py", line 246, in <module>
    CLI(convert_lit_checkpoint, as_positional=False)
  File "/home/Zhengwt/anaconda3/envs/llama2/lib/python3.10/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/home/Zhengwt/anaconda3/envs/llama2/lib/python3.10/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/home/Zhengwt/anaconda3/envs/llama2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/Zhengwt/lit-gpt/scripts/convert_lit_checkpoint.py", line 237, in convert_lit_checkpoint
    check_conversion_supported(lit_weights)
  File "/home/Zhengwt/lit-gpt/scripts/convert_lit_checkpoint.py", line 205, in check_conversion_supported
    raise ValueError("Model weights must be merged using `lora.merge_lora_weights()` before conversion.")
ValueError: Model weights must be merged using `lora.merge_lora_weights()` before conversion.

But it will produce  a file soon:

> /home/Zhengwt/lit-gpt/out/lora/Llama-2-7b-hf/lora_model_merged.bin（704 Bytes）

I am very confused about this.Why is there an error? Why does the converted file turn out to be so small? How can I generate two .bin files like the ones on Hugging Face, one being 3GB and the other being 9GB?
I would greatly appreciate it if you could answer my questions.

**Comment by carmocca** [comment]
@Vinter8848 The conversion script is not functional at the moment. You'll be able to try again once this issue is resolved

**Comment by Vinter8848** [comment]
Thank you very much for your response.  Looking forward to the early resolution of this issue !

**Comment by Vinter8848** [comment]
I have successfully used the [scripts/merge_lora.py](url) and [scripts/convert_lit_checkpoint.py](url) scripts to convert `lit_model.pth` to `lit_model.bin (13.58GB)`. Thank you very much for your efforts!
   I would like to know how to modify the conversion process to generate two .bin files from `lit_model.pth`, for example: `lit_model1.bin (9.58GB)` and `lit_model2.bin (4GB)`. I would greatly appreciate your response!

**Comment by carmocca** [comment]
@Vinter8848 You could `torch.load("lit_model.pth")`, split the dictionary into multiple dictionaries and save them to different filenames.

Since the `script/merge_lora.py` has landed (#495), this can now be closed.
