### ISSUE TITLE
Conditional installation of CPU/CUDA version of PyTorch

### ISSUE THREAD

**Issue by Andrei-Aksionov** [Lightning-AI/lit-gpt#380]
Hi there 👋 

In order to use this repo a proper version of PyTorch needs to be installed (depending on the Nvidia GPU availability).
It is described in the Readme file.
But it's also possible to make this installation in a more [automatized way](https://github.com/Andrei-Aksionov/lit-gpt/blob/install_script/install.py).

So the question is: is it any useful or it's just a good old over-complication?

**Comment by carmocca** [comment]
My opinion is that this isn't worth adding, but others might think differently

**Comment by carmocca** [comment]
Closing since this is not really necessary
