### ISSUE TITLE
Eval Harness does not work on Truthful MC / single task

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#385]
Was trying out the evaluation harness, and it doesn't seem to work on the Truthful MC yet. On that note, maybe it doesn't work on a single task? 

Via

```python
python eval/lm_eval_harness.py \
        --checkpoint_dir "checkpoints/openlm-research/open_llama_7b/" \
        --precision "bf16-true" \
        --eval_tasks "[truthful_mc]" \
        --batch_size 4 \
        --save_filepath "results.json"
```

CC @aniketmaurya 
<img width="1025" alt="Screenshot 2023-08-10 at 2 04 51 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/5618407/43bfacbb-b5e6-4cbc-b1d1-a18e256f4c29">

**Comment by aniketmaurya** [comment]
hi @rasbt, eval-harness lists `truthfulqa_mc` and `truthfulqa_gen` in their [tasks list](https://github.com/EleutherAI/lm-evaluation-harness/blob/master/docs/task_table.md). Maybe you're looking for that?

**Comment by rasbt** [comment]
Ooops sorry, I must be blind 🤦‍♂️. Thanks!
