### ISSUE TITLE
Import errors for lm_eval_harness_lora.py

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#386]
The regular `lm_eval_harness.py` works fine, but given the instructions in https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/evaluation.md, the LoRA version (`lm_eval_harness_lora.py`) currently fails with a

```python
    from scripts.prepare_alpaca import generate_prompt
ModuleNotFoundError: No module named 'scripts.prepare_alpaca'
```

I think there are at least two options to fix this. E.g., 

- the `scripts` subdirectory would need to become a module, e.g.,  getting an `__init__.py` file. 
- Or we maybe implement the `generate_prompt` version in `lit-gpt/generate.py` and import in both cases (prepare_alpaca script and evaluation script) from there.

What do you think?

CC @aniketmaurya

**Comment by aniketmaurya** [comment]
yes, I agree. In this case, since different fineuned model can have different `generate_prompt` output so we can have a template `generate_method` and users should be able to customize that based on their need.

**Comment by rasbt** [comment]
What would be the easiest way to address this issue since users are currently not able to use the script as is? Also @carmocca may have some good ideas here perhaps.

By the way a third option is to bring back the `python scripts/convert_lora_weights.py` script from lit-llama so that we don't need to separate eval_harness scripts.

**Comment by carmocca** [comment]
I don't understand why this error is happening now. What's even stranger is that I tried checking out older commits and it's there.

**Comment by carmocca** [comment]
`git clean -fxd` seems to have fixed this for me (beware of lost untracked files)

**Comment by rasbt** [comment]
Hm, this issue seems to still persist. I think there's definitely an `__init__.py` or something missing?

**Comment by aniketmaurya** [comment]
this issue is still there for me too. It goes away when I add a `__init__.py` to scripts

**Comment by carmocca** [comment]
Have you tried running `git clean` as suggested?

**Comment by aniketmaurya** [comment]
yes, I did run `git clean -fxd`

**Comment by bryfry** [comment]
I needed these two steps to avoid this error:
- `touch scripts/__init__.py`
- `cd finetune; ln -s ../scripts`

**Comment by rasbt** [comment]
Thanks for sharing. Actually, we recently removed this script to simplify the code (and lower the maintenance efforts).

I.e., we added a new `merge_lora.py` script to merge the LoRA weights back into the checkpoint file (described in more detail [here](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/finetune_lora.md#merging-lora-weights).).

After merging the weights, the resulting model behaves just like a regular checkpoint file, so you can use the regular [lm_eval_harness.py](https://github.com/Lightning-AI/lit-gpt/blob/main/eval/lm_eval_harness.py) script for this.

Let us know if you have any questions or concerns!

**Comment by bryfry** [comment]
@rasbt I had the same error on `finetune/lora.py` which still exists. Should I open a separate issue?

**Comment by rasbt** [comment]
Hm, sorry to hear there are more issues. Btw I am personally cloning the repo regularly and haven't bumped into this yet. Yeah, perhaps open a new issue for this. Maybe someone has an idea of what could be going on there.

**Comment by jimdowling** [comment]
I just cloned the repo using these instructions
https://lightning.ai/pages/community/lora-insights/?utm_medium=social&utm_source=twitter&utm_campaign=Education_10132023

. Had the same problem.
This fixed it
touch scripts/__init__.py
cd finetune; ln -s ../scripts
