### ISSUE TITLE
Adding databricks-dolly-15k

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#394]
I have a local version for Dolly 15k on my other computer; it's a useful dataset for the NeurIPS challenge. Just adding it here so I won't forget to add this on Monday/Tuesday.

**Comment by aniketmaurya** [comment]
can be ported from Lit-LLaMA - https://github.com/Lightning-AI/lit-llama/blob/main/scripts/prepare_dolly.py
