### ISSUE TITLE
"UnicodeEncodeError: 'charmap' codec can't encode characters 

### ISSUE THREAD

**Issue by jeetendraabvv** [Lightning-AI/lit-gpt#400]
Following error encounter during finetuning falcon-lb using LORA
on Windows and Anaconda with 48GB GPU

['C:\\ProgramData\\anaconda3\\envs\\lit_test\\lib\\site-packages\\pydantic\\_migration.py:283: UserWarning: `pydantic.utils:Representation` has been removed. We are importing from `pydantic.v1.utils:Representation` instead.See the migration guide for more details: https://docs.pydantic.dev/latest/migration/',
 '  warnings.warn(',
 'Using bfloat16 Automatic Mixed Precision (AMP)',
 'Global seed set to 1337',
 'Global seed set to 1337',
 "{'eval_interval': 100, 'save_interval': 100, 'eval_iters': 100, 'log_interval': 1, 'devices': 1, 'learning_rate': 0.0003, 'batch_size': 128, 'micro_batch_size': 4, 'gradient_accumulation_iters': 32, 'max_iters': 50000, 'weight_decay': 0.01, 'lora_r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05, 'lora_query': True, 'lora_key': False, 'lora_value': True, 'lora_projection': False, 'lora_mlp': False, 'lora_head': False, 'warmup_steps': 100}",
 "Loading model 'checkpoints\\\\tiiuae\\\\falcon-7b\\\\lit_model.pth' with {'org': 'tiiuae', 'name': 'falcon-7b', 'block_size': 2048, 'vocab_size': 50254, 'padding_multiple': 512, 'padded_vocab_size': 65024, 'n_layer': 32, 'n_head': 71, 'n_embd': 4544, 'rotary_percentage': 1.0, 'parallel_residual': True, 'bias': False, 'n_query_groups': 1, 'shared_attention_norm': True, '_norm_class': 'LayerNorm', 'norm_eps': 1e-05, '_mlp_class': 'GptNeoxMLP', 'intermediate_size': 18176, 'condense_ratio': 1, 'r': 8, 'alpha': 16, 'dropout': 0.05, 'to_query': True, 'to_key': False, 'to_value': True, 'to_projection': False, 'to_mlp': False, 'to_head': False}",
 'Number of trainable parameters: 3,506,176',
 'Number of non trainable parameters: 7,217,189,760',
 'Validating ...',
 'Recommend a movie for me to watch during the weekend and explain the reason.',
 'Traceback (most recent call last):',
 '  File "C:\\Users\\Administrator\\Downloads\\lit-gpt-main\\finetune\\lora.py", line 316, in <module>',
 '    CLI(setup)',
 '  File "C:\\ProgramData\\anaconda3\\envs\\lit_test\\lib\\site-packages\\jsonargparse\\_cli.py", line 85, in CLI',
 '    return _run_component(component, cfg_init)',
 '  File "C:\\ProgramData\\anaconda3\\envs\\lit_test\\lib\\site-packages\\jsonargparse\\_cli.py", line 147, in _run_component',
 '    return component(**cfg)',
 '  File "C:\\Users\\Administrator\\Downloads\\lit-gpt-main\\finetune\\lora.py", line 81, in setup',
 '    fabric.launch(main, data_dir, checkpoint_dir, out_dir)',
 '  File "C:\\ProgramData\\anaconda3\\envs\\lit_test\\lib\\site-packages\\lightning\\fabric\\fabric.py", line 834, in launch',
 '    return self._wrap_and_launch(function, self, *args, **kwargs)',
 '  File "C:\\ProgramData\\anaconda3\\envs\\lit_test\\lib\\site-packages\\lightning\\fabric\\fabric.py", line 920, in _wrap_and_launch',
 '    return to_run(*args, **kwargs)',
 '  File "C:\\ProgramData\\anaconda3\\envs\\lit_test\\lib\\site-packages\\lightning\\fabric\\fabric.py", line 925, in _wrap_with_setup',
 '    return to_run(*args, **kwargs)',
 '  File "C:\\Users\\Administrator\\Downloads\\lit-gpt-main\\finetune\\lora.py", line 132, in main',
 '    train(fabric, model, optimizer, train_data, val_data, checkpoint_dir, out_dir, speed_monitor)',
 '  File "C:\\Users\\Administrator\\Downloads\\lit-gpt-main\\finetune\\lora.py", line 153, in train',
 '    validate(fabric, model, val_data, tokenizer, longest_seq_length)  # sanity check',
 '  File "C:\\ProgramData\\anaconda3\\envs\\lit_test\\lib\\site-packages\\torch\\utils\\_contextlib.py", line 115, in decorate_context',
 '    return func(*args, **kwargs)',
 '  File "C:\\Users\\Administrator\\Downloads\\lit-gpt-main\\finetune\\lora.py", line 254, in validate',
 '    fabric.print(output)',
 '  File "C:\\ProgramData\\anaconda3\\envs\\lit_test\\lib\\site-packages\\lightning\\fabric\\fabric.py", line 499, in print',
 '    print(*args, **kwargs)',
 '  File "C:\\ProgramData\\anaconda3\\envs\\lit_test\\lib\\encodings\\cp1252.py", line 19, in encode',
 '    return codecs.charmap_encode(input,self.errors,encoding_table)[0]',
 "UnicodeEncodeError: 'charmap' codec can't encode characters in position 220-221: character maps to <undefined>"]

**Comment by carmocca** [comment]
Unfortunately Windows doesn't use utf-8 by default. How did you prepare your data? You are probably missing an `open(..., encoding="utf-8")` somewhere
