### ISSUE TITLE
convert_hf_checkpoint.py does not support llama1?

### ISSUE THREAD

**Issue by MrJungle1** [Lightning-AI/lit-gpt#426]
convert_hf_checkpoint.py does not support llama1? I want to convert llama1 to lit_gpt format but I get the following error.
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/12598b21-1df5-49a0-b4f2-d7bf135979ec)

**Comment by MrJungle1** [comment]
hello @carmocca  If I have official weights, add llama1 dict like llama2 in config.py, should the block_size in dict be set to 4096 like llama2 or 2048 like open_llama, will there be any impact here?
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/a71f7766-39fd-4592-9a3c-081f8305443f)
![image](https://github.com/Lightning-AI/lit-gpt/assets/43968255/39f15be5-8640-461e-8c40-43add19d5150)

**Comment by carmocca** [comment]
Our conversion scripts do not support Facebook's Llama 1 architecture. However, Lit-LLaMA does as I mentioned in my previous comment. You can try that repository and it won't require any code changes

**Comment by Vinter8848** [comment]
Can I use the  convert_checkpoint.py  in  lit-llama( https://github.com/Lightning-AI/lit-llama)  to  convert llama2(official weights) into  lit_gpt format?

**Comment by carmocca** [comment]
Llama 1 official weights are supported by lit-llama
Llama 1 HF weights (open-llama and similar checkpoints) are supported by lit-gpt
Llama 2 official weights are not supported by either of the projects
Llama 2 HF weights are supported by lit-gpt

So the answer to your question is no, @Vinter8848. Code changes to the conversion logic on lit-llama would be required.

**Comment by Vinter8848** [comment]
Thank you very much for your response. Your answer has been very helpful to me.

**Comment by carmocca** [comment]
Closing in favor of #463
