### ISSUE TITLE
[help wanted][easy] Support the latest trending checkpoints

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lit-gpt#427]
A simple and fun way to contribute to this project is to add support for newly released checkpoints. https://huggingface.co/models?pipeline_tag=text-generation&sort=trending contains a list of the trendiest checkpoints and most of them could be easily supported.

Here's an example PR that did exactly this: https://github.com/Lightning-AI/lit-gpt/pull/302

Some examples of configurations that could be easily added are:
- [x] https://huggingface.co/togethercomputer/LLaMA-2-7B-32K
- [ ] https://huggingface.co/stabilityai/StableBeluga2
- [x] https://huggingface.co/lmsys/vicuna-13b-v1.5-16k
- [x] https://huggingface.co/NousResearch/Nous-Hermes-Llama2-13b
- [x] https://huggingface.co/stabilityai/stablecode-completion-alpha-3b
- [x] https://platypus-llm.github.io

---

I will try to keep this issue up-to-date. Feel free to pick one from the list and add support

**Comment by m0saan** [comment]
Hello @carmocca, which of these still need configurations to be added? Thank you!
