### ISSUE TITLE
Better error if someone uses a model-incompatible prepare_dataset.py script call

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#428]
We require preparing the dataset with a model-specific tokenizer. The workflow is typically

```
python scripts/prepare_alpaca.py --checkpoint_dir model1
python finetune/lora.py  --checkpoint_dir model1
```

Then, if someone wants to use a different model, they have to run

```
python scripts/prepare_alpaca.py --checkpoint_dir model2
python finetune/lora.py  --checkpoint_dir model2
```

but it is easy to forget to run `python scripts/prepare_alpaca.py` again. And this can then lead to failures with uninformative errors. 

We need to think of a way to make it more obvious what's wrong when someone runs

```
python scripts/prepare_alpaca.py --checkpoint_dir model1
python finetune/lora.py  --checkpoint_dir model1
python finetune/lora.py  --checkpoint_dir model2
```

**Comment by awaelchli** [comment]
This is essentially solved now in the wip branch 🎉
