### ISSUE TITLE
Explore Flash Attention Like Feature for MPS Backend

### ISSUE THREAD

**Issue by JustinGoheen** [Lightning-AI/lit-gpt#429]
## Overview 
An individual discussed implementing a flash attention like optimization for PyTorch's MPS backend. This issue thread serves to continue discussion on this idea. Please see image and link for additional context.

https://twitter.com/sujantkumarkv/status/1691422635551547392?s=20
<img width="608" alt="Screenshot 2023-08-16 at 12 08 43 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/26209687/0a6a9a2c-53da-46be-8862-2ca2bd3f3c65">

## Additional Resources

- [Adding Op for MPS Backend](https://github.com/pytorch/pytorch/wiki/MPS-Backend#adding-op-for-mps-backend)
- [PyTorch MPS Profiler](https://github.com/pytorch/pytorch/wiki/MPS-Backend#pytorch-performance-profiling-using-mps-profiler)
- [MPS docs](https://developer.apple.com/documentation/metalperformanceshaders)
- [Optimizing GPU performance](https://developer.apple.com/documentation/xcode/optimizing-gpu-performance) (Metal debugger)

## Primary Thoughts, Questions, Ideas
- How does computation take place on MPS? Is it even necessary to create a flash-attention like feature for MPS, or have Apple engineers already optimized for the issues discussed in the flash attention papers.
- Will this require some combination of C++ and Swift to target MPS and [Swift::Accelerate](https://developer.apple.com/documentation/accelerate)
- How would setting `PYTORCH_ENABLE_MPS_FALLBACK=1` affect ops

**Comment by JustinGoheen** [comment]
See the following implemention if interested: 

https://github.com/philipturner/metal-flash-attention

**Comment by LeaveNhA** [comment]
Any news on this fellas? We need it. 🥲

**Comment by signalprime** [comment]
Agreed, it seems in so many downstream tasks that MPS users get stopped due to this missing lane.  Was noticing how long ago this was opened.  Maybe it's been implemented and we don't know where?
