### ISSUE TITLE
Issue with torchaudio version in Google colab!!

### ISSUE THREAD

**Issue by puneethegde** [Lightning-AI/lit-gpt#441]
Im trying to run the code on Google colab tried CPU and GPU but

getting this error
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastai 2.7.12 requires torch<2.1,>=1.7, but you have torch 2.1.0.dev20230819+cu118 which is incompatible.
torchaudio 2.0.2+cu118 requires torch==2.0.1, but you have torch 2.1.0.dev20230819+cu118 which is incompatible.
torchdata 0.6.1 requires torch==2.0.1, but you have torch 2.1.0.dev20230819+cu118 which is incompatible.
torchtext 0.15.2 requires torch==2.0.1, but you have torch 2.1.0.dev20230819+cu118 which is incompatible.
torchvision 0.15.2+cu118 requires torch==2.0.1, but you have torch 2.1.0.dev20230819+cu118 which is incompatible.

Also
OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN2at4_ops6conv1d4callERKNS_6TensorES4_RKN3c108optionalIS2_EENS5_8ArrayRefIlEESB_SB_l

The torchaudio that the code is using is not compatible with torch2.1.0dev!!!

**Comment by richardsun-voyager** [comment]
Hi Puneethegde! How did you solve this issue? Thanks!

**Comment by richardsun-voyager** [comment]
Hi @carmocca . Got it! Thanks a lot! By the way, both lit-llama and lit-gpt are very useful, efficient and friendly to me!
