### ISSUE TITLE
safetensor files

### ISSUE THREAD

**Issue by patrickhwood** [Lightning-AI/lit-gpt#450]
Has anyone managed to get models saved as safetensor files to work?

**Comment by patrickhwood** [comment]
Ok, well converting to .bin is just a few lines of code, so I guess it's not a big deal.

**Comment by windprak** [comment]
> Ok, well converting to .bin is just a few lines of code, so I guess it's not a big deal.

Can you at least tell us how you convert them?

**Comment by carmocca** [comment]
@windprak You can use `python scripts/download.py --repo_id ... --from_safetensors true`
