### ISSUE TITLE
Solution to loading Llama 2 70B on 8 GPUs?

### ISSUE THREAD

**Issue by lifengjin** [Lightning-AI/lit-gpt#456]
I am trying to load llama 2 70B using FSDP onto 8 GPUs on a node. It appears that 8 processes responsible for FSDP all try to load the full model, causing the CPU memory usage pike to over 1T. Is there any quick and direct way to counter this?

**Comment by carmocca** [comment]
Not at the moment, but this is on my TODO list. Thanks for the feature request.

How much RAM do you have?

**Comment by lifengjin** [comment]
I have around 1T of memory. I can use FSDP to load 70B onto 6 cards, but no more than that.

**Comment by carmocca** [comment]
Are you interested in finetuning or pretraining?

**Comment by lifengjin** [comment]
Currently I am just trying to do inference. I have plans for finetuning and pretraining, but pretraining probably comes first.

**Comment by carmocca** [comment]
Thanks for the info. Do you know where you go OOM? Is it at https://github.com/Lightning-AI/lit-gpt/blob/d5d371417ecb3d3b6c4f30837d8bb7cf2b5310ae/generate/base.py#L153 when each model loads the checkpoint?

**Comment by lifengjin** [comment]
Yes, that's right.

**Comment by carmocca** [comment]
Can you try applying the following changes to that script?

```python
    with fabric.init_module(empty_init=True), torch.device("meta"), quantization(quantize):
        model = GPT(config)
    fabric.print(f"Time to instantiate model: {time.perf_counter() - t0:.02f} seconds.", file=sys.stderr)

    t0 = time.perf_counter()
    checkpoint = torch.load(str(checkpoint_path), mmap=True)
    model.load_state_dict(checkpoint.get("model", checkpoint), strict=quantize is None, assign=True)
```

You might need to reinstall torch to use a more recent nightly version. You might also need to call `convert_hf_checkpoint.py` with `--dtype ...` set to the correct dtype depending on your `--precision ...` value, for instance `--dtype bfloat16` for `--precision bf16-true`.

**Comment by lifengjin** [comment]
Nothing changed so far. Loading with 8 GPUs still caused the server to not respond to anything, presuambly swapping like crazy.

**Comment by carmocca** [comment]
Thanks. What about this?

```python
    with fabric.init_module(empty_init=True), quantization(quantize):
        model = GPT(config)
    fabric.print(f"Time to instantiate model: {time.perf_counter() - t0:.02f} seconds.", file=sys.stderr)

    model.eval()
    model = fabric.setup_module(model)
    fabric.load_raw(checkpoint_path, model)
```

It will need the latest lightning features: `pip uninstall -y lightning; pip install -r requirements.txt`

**Comment by lifengjin** [comment]
The `AttributeError: <class 'lit_gpt.utils.NotYetLoadedTensor'> does not have is_meta` exists with the newest lightning.

**Comment by kevinfengcu** [comment]
> Can you try applying the following changes to that script?
> 
> ```python
>     with fabric.init_module(empty_init=True), torch.device("meta"), quantization(quantize):
>         model = GPT(config)
>     fabric.print(f"Time to instantiate model: {time.perf_counter() - t0:.02f} seconds.", file=sys.stderr)
> 
>     t0 = time.perf_counter()
>     checkpoint = torch.load(str(checkpoint_path), mmap=True)
>     model.load_state_dict(checkpoint.get("model", checkpoint), strict=quantize is None, assign=True)
> ```
> 
> You might need to reinstall torch to use a more recent nightly version. You might also need to call `convert_hf_checkpoint.py` with `--dtype ...` set to the correct dtype depending on your `--precision ...` value, for instance `--dtype bfloat16` for `--precision bf16-true`.

Can confirm that bleeding edge torch and lightning works with the snippet above, no CPU memory peak.

**Comment by PandaBoi** [comment]
> Can confirm that bleeding edge torch and lightning works with the snippet above, no CPU memory peak.

Im currently trying to replicate this, but CPU mem keeps climbing. Wont each of the 8 processes try to load the state dict. it should cause the same issue as before correct? @kevinfengcu

**Comment by babytdream** [comment]
@lifengjin 
Hi, in #469, I run this command in my 16 gpus:
`python generate/base.py --checkpoint_dir /data/model/Llama-2-70b-chat-hf/ --strategy fsdp --devices 12`

But it runs more than 1 hour, this doesn't seem normal.There are logs:
```
Loading model '/data/model/Llama-2-70b-chat-hf/lit_model.pth' with {'org': 'meta-llama', 'name': 'Llama-2-70b-chat-hf', 'block_size': 4096, 'vocab_size': 32000, 'padding_multiple': 64, 'padded_vocab_size': 32000, 'n_layer': 80, 'n_head': 64, 'n_embd': 8192, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'n_query_groups': 8, 'shared_attention_norm': False, '_norm_class': 'RMSNorm', 'norm_eps': 1e-05, '_mlp_class': 'LLaMAMLP', 'intermediate_size': 28672, 'condense_ratio': 1}
Time to instantiate model: 0.05 seconds.
Time to load the model weights: 546.27 seconds.
[rank: 11] Global seed set to 1234
[rank: 1] Global seed set to 1234
[rank: 0] Global seed set to 1234
[rank: 5] Global seed set to 1234
[rank: 3] Global seed set to 123
```
![image](https://github.com/Lightning-AI/lit-gpt/assets/74184102/c4206d74-23cc-4245-bcb5-2685774cc623)
Have you ever encountered such a situation？

**Comment by lifengjin** [comment]
@babytdream Yes. What I observed with 8 GPUs is that all of the children started to load the whole model. At some point the memory become not enough, and the OS killed two threads to allow the rest to load. Here what you post seems to suggest that 5 of the threads loaded successfully, and the rest got killed due to CPU OOM. The main thread doesn't tend to error out, but the program is definitely not running.

**Comment by babytdream** [comment]
@lifengjin @carmocca Would it be helpful to split the model,like 00001-00015model.bin?

**Comment by lifengjin** [comment]
@carmocca Hi, is there any update on this issue? Thanks!

**Comment by carmocca** [comment]
Not yet, I think I will be able to continue this line of work next week. Sorry for the wait

**Comment by richardsun-voyager** [comment]
> Thanks for the info. Do you know where you go OOM? Is it at
> 
> https://github.com/Lightning-AI/lit-gpt/blob/d5d371417ecb3d3b6c4f30837d8bb7cf2b5310ae/generate/base.py#L153
> 
> when each model loads the checkpoint?

This works for me to load the model llama-2-70B for inference (generate/base.py). But it did not work for fine-tuning (lora.py).

**Comment by MrJungle1** [comment]
@PandaBoi @richardsun-voyager @lifengjin @kevinfengcu @carmocca , Hello, I would like to ask if there is any new progress on this issue. I have 480g memory and encountered the same problem, so I would like to ask how much memory is needed to use llama2-70b for inference.

**Comment by richardsun-voyager** [comment]
> Can you try applying the following changes to that script?
> 
> ```python
>     with fabric.init_module(empty_init=True), torch.device("meta"), quantization(quantize):
>         model = GPT(config)
>     fabric.print(f"Time to instantiate model: {time.perf_counter() - t0:.02f} seconds.", file=sys.stderr)
> 
>     t0 = time.perf_counter()
>     checkpoint = torch.load(str(checkpoint_path), mmap=True)
>     model.load_state_dict(checkpoint.get("model", checkpoint), strict=quantize is None, assign=True)
> ```
> 
> You might need to reinstall torch to use a more recent nightly version. You might also need to call `convert_hf_checkpoint.py` with `--dtype ...` set to the correct dtype depending on your `--precision ...` value, for instance `--dtype bfloat16` for `--precision bf16-true`.

Is it possible to load one copy of the pre-trained weights across multiple GPUs and fine-tune them? For example, I have 4 A100 GPUs (40G each), each of which cannot load the whole LLama2 pre-trained weights alone. In this case, how can I modify  finetune/lora.py to fine-tune the weights? Thanks!

**Comment by jiaaoc** [comment]
Any updates on the RAM issues with multiple GPUs?

**Comment by carmocca** [comment]
@jiaaoc #564 should have decreased the RAM requirement for the lora.py and full.py finetuning scripts

**Comment by jiaaoc** [comment]
Thanks for the pointer! I will refer to #564

**Comment by carmocca** [comment]
Multi-GPU inference is now supported: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/inference.md#run-a-large-model-on-multiple-smaller-devices
