### ISSUE TITLE
Support original Llama 2 weights from Meta

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#463]
Currently, we use Llama 2 weights hosted on Hugging Face. However, as discussed on [this thread Twitter/X here](https://twitter.com/jeremyphoward/status/1694434157882175698?s=20) there HF weights are converted from bfloat16 to float16 so there may be problems with the training in certain precisions. 

We maybe want to also support the original Meta weights to avoid this issue.

**Comment by m0saan** [comment]
If decided to go wit this proposal I'd like to give this a shot, and so, maybe introduce a function for direct Meta weights download. 

Before proceeding, I'd appreciate your insights:
- Should we integrate this function into [`download_from_hub`](https://github.com/Lightning-AI/lit-gpt/blob/d5d371417ecb3d3b6c4f30837d8bb7cf2b5310ae/scripts/download.py#L11) or keep it separate?
- Are there specific considerations for downloading Meta weights, such as authentication (as users need to already have access to the model weights available). or usage of Meta's download script?

**Comment by carmocca** [comment]
@m0saan You should assume that the weights are already locally available. And you can create a new `scripts/convert_meta_checkpoint.py` file that does the conversion
