### ISSUE TITLE
Support for Code Llama

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#464]
Meta just released Coda Llama today -- Llama 2 finetuned on code. It'd be awesome to support it, of course :)

Reference:
- https://ai.meta.com/blog/code-llama-large-language-model-coding
- https://github.com/facebookresearch/codellama

**Comment by m0saan** [comment]
Hello @rasbt  Can I work on this!?

**Comment by rasbt** [comment]
Sure @m0saan  :)

**Comment by rasbt** [comment]
I just saw the weights are here: https://huggingface.co/codellama

**Comment by m0saan** [comment]
@rasbt  @carmocca I've created a branch, and added these checkpoints, but while testing them, the models keep generating some weird stuff!

**Comment by m0saan** [comment]
for example, I gave it this prompt: `import socket\\n\\ndef ping_exponential_backoff(host: str):`

it generates this: 
<img width="753" alt="Screenshot 2023-08-25 at 19 19 11" src="https://github.com/Lightning-AI/lit-gpt/assets/50895527/ef0de951-fe6d-4f73-a8e2-21598e1fe154">

**Comment by rasbt** [comment]
@m0saan Hmm, I am wondering if it could be related to this: https://twitter.com/abacaj/status/1695334296792264792?s=20

<img width="496" alt="Screenshot 2023-08-26 at 9 55 47 AM" src="https://github.com/Lightning-AI/lit-gpt/assets/5618407/ae3d2693-cccf-4282-b8b7-6a1c4a7b246f">

**Comment by m0saan** [comment]
@rasbt, could be, I am still investigating why are we getting these weird outputs.
