### ISSUE TITLE
Solution to loading and finetune  Llama 2 70B on 16 GPUs?

### ISSUE THREAD

**Issue by babytdream** [Lightning-AI/lit-gpt#473]
Like #456 , I have 16 gpus(16 * A10) in one machine. I want to finetune  Llama 2 70B on 16 GPUs.
![image](https://github.com/Lightning-AI/lit-gpt/assets/74184102/843716b0-0c22-4628-9668-015acb9cb6af)
Is there FSDP to finetune  Llama 2 70B on 16 GPUs?

**Comment by richardsun-voyager** [comment]
I want to do it too. But it seems each card tries to load all the weights and go OOM, instead of getting a portion of the weights.

**Comment by carmocca** [comment]
@richardsun-voyager #564 should avoid that for the `finetune/full.py` and `finetune/lora.py` scripts

@babytdream You just need to call the script after modifying https://github.com/Lightning-AI/lit-gpt/blob/main/finetune/lora.py#L36 to `devices=16`
