### ISSUE TITLE
Save the model config in the training scripts

### ISSUE THREAD

**Issue by jxtngx** [Lightning-AI/lit-gpt#483]
while testing conversion of LoRA finetuned checkpoints to their original format, it was found that having a `lora_config.json` saved to `out/lora/` would be beneficial when creating a new model with `model = GPT.from_name(model_name, **lora_config_during_finetuning)` or `model = GPT(**lora_config_during_finetuning)`.

intended changes in `finetune.lora.py` are:

```python
import json
from dataclasses import asdict

def save_lora_config(fabric, model, out_dir: Path):
    fabric.print(f"Saving LoRA config to {str(out_dir)!r}")
    config_payload = {k: v for k, v in asdict(model.config).items() if k != "org"}
    with open(out_dir / "lit_lora_config.json", "w") as config_path:
        json.dump({"config": config_payload}, config_path, indent=4))
```

example output

```json
{
    "config": {
        "name": "Llama-2-7b-hf",
        "block_size": 1,
        "vocab_size": 1,
        "padding_multiple": 64,
        "padded_vocab_size": 64,
        "n_layer": 1,
        "n_head": 4,
        "n_embd": 8,
        "rotary_percentage": 1.0,
        "parallel_residual": false,
        "bias": false,
        "n_query_groups": 4,
        "shared_attention_norm": false,
        "_norm_class": "RMSNorm",
        "norm_eps": 1e-05,
        "_mlp_class": "LLaMAMLP",
        "intermediate_size": 11008,
        "condense_ratio": 1,
        "r": 1,
        "alpha": 8,
        "dropout": 0.1,
        "to_query": true,
        "to_key": false,
        "to_value": true,
        "to_projection": false,
        "to_mlp": false,
        "to_head": false
    }
}
```

**Comment by carmocca** [comment]
I don't get the motivation. When using LoRA, the LoRA config is the model config: https://github.com/Lightning-AI/lit-gpt/blob/main/lit_gpt/lora.py#L427. It's not a separate object

**Comment by carmocca** [comment]
Actually, maybe I know what you mean. Is your point that when you finetune with LoRA and then do inference with the generated checkpoints, you have to copy over the LoRA config?

If so, I agree that the generated checkpoints could come with the config used to generate them.

**Comment by JustinGoheen** [comment]
yes.

> Actually, maybe I know what you mean. Is your point that when you finetune with LoRA and then do inference with the generated checkpoints, you have to copy over the LoRA config?
> 
> If so, I agree that the generated checkpoints could come with the config used to generate them.

**Comment by skramer-dev** [comment]
To all my fellow finetuners that stumble across this (probably from the size mismatch error if non-default hyperparameters are used): This solution does work but needs some more adjustments to work if you want to merge the lora before running inference/benchmarking with it. In the spirit of this project i hacked together something that works (but is probably not ideal).

In 'finetune/lora.py' i added the new function as described in here
```python
def save_lora_config(fabric, model, out_dir: Path):
    fabric.print(f"Saving LoRA config to {str(out_dir)!r}")
    config_payload = {k: v for k, v in asdict(model.config).items() if k != "org"}
    with open(out_dir / "lit_lora_config.json", "w") as config_path:
        json.dump({"config": config_payload}, config_path, indent=4)
```
In the same file i extend the main function with the extra call:
```python
# Save the final LoRA checkpoint at the end of training
save_path = out_dir / "lit_model_lora_finetuned.pth"
save_lora_checkpoint(fabric, model, save_path)
save_lora_config(fabric, model, out_dir)
```

To then use that config file i changed 'scripts/merge_lora':
If the config file is present it reads the values from it and if not it uses the default values that were previously at the top of the file.
```python
    if os.path.exists(Path(os.path.dirname(lora_path)) / "lit_lora_config.json"):
        with open(Path(os.path.dirname(lora_path)) / "lit_lora_config.json", 'r') as f:
            data = json.load(f)
        config = data["config"]
        lora_r = config["r"]
        lora_alpha = config["alpha"]
        lora_dropout = config["dropout"]
        lora_query = config["to_query"]
        lora_key = config["to_key"]
        lora_value = config["to_value"]
        lora_projection = config["to_projection"]
        lora_mlp = config["to_mlp"]
        lora_head = config["to_head"]
    else:
        lora_r = 8
        lora_alpha = 16
        lora_dropout = 0.05
        lora_query = True
        lora_key = False
        lora_value = True
        lora_projection = False
        lora_mlp = False
        lora_head = False
```
