### ISSUE TITLE
do the scripts have some sample examples on how to run

### ISSUE THREAD

**Issue by andysingal** [Lightning-AI/lit-gpt#487]
Hi,
    Thanks for the amazing repo, i see there are alot of scripts for datasets but no README for implementation... i understand they are all alpaca based but have links for data that are already in the alpaca dataset format. Is it possible to share the use case for implementation on custom dataset.

Looking forward to hearing from you.
Thanks,
Andy Singal

**Comment by rasbt** [comment]
I can add a short section to the [prepare_dataset.md](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/prepare_dataset.md) file later today @andysingal. 

But in short, even though the code may look pretty intimidating, it's pretty simple: You copy one of the existing data prep files like [`prepare_lima.md`](https://github.com/Lightning-AI/lit-gpt/blob/main/scripts/prepare_lima.py) and modify the `prepare` function such that the `train_set` and `test_set` are lists of dictionary entries, for example

```
[
{'instruction': 'What is the likely outcome of a jury trial?',
 'input': '',
 'output': 'The likely outcome of a jury trial is a verdict or a hung jury, in which the jury is unable to come to a majority decision.'},
{'instruction': 'What is the result of 2x2',
 'input': '',
 'output': '4'},
]
```

**Comment by andysingal** [comment]
Thank you, i guess I need to do the conversion to alpaca format before I
run the script?.

**Comment by rasbt** [comment]
@andysingal Yes, but you can decide how you want to do the conversion. Besides that everything below line 67 you can then basically copy & paste
