### ISSUE TITLE
FSDP generation question

### ISSUE THREAD

**Issue by lifengjin** [Lightning-AI/lit-gpt#490]
I have a simple question regarding generation with FSDP. Say we have a Model on 4 cards with FSDP. Now we send one prompt to the model to do inference. Is this prompt run on all cards or just one card? And which card?

If a batch of 4 prompts is sent to the model, will Fabric split it into 4 microbatches, or will this single batch get executed on one card?

**Comment by lifengjin** [comment]
I have figured it out.

**Comment by MF-FOOM** [comment]
> I have figured it out.

Do tell!
