### ISSUE TITLE
Finetuning Llama-2-70B-chat-hf: Missing key(s) in state_dict

### ISSUE THREAD

**Issue by richardsun-voyager** [Lightning-AI/lit-gpt#492]
I tried to finetune LLama-2-70B-chat-hf with LoRA, but found there was an error when loading the pre-trained weights:
"checkpoint = torch.load(str(checkpoint_path), mmap=True)"
Error message:
"Missing key(s) in state_dict: "transformer.h.0.attn.attn.lora_A", "transformer.h.0.attn.attn.lora_B", "transformer.h.1.attn.attn.lora_A", "transformer.h.1.attn.attn.lora_B", "transformer.h.2.attn.attn.lora_A", "transformer.h.2.attn.attn.lora_B", "transformer.h.3.attn.attn.lora_A", "transformer.h.3.attn.attn.lora_B", "transformer.h.4.attn.attn.lora_A", "transformer.h.4.attn.attn.lora_B", "transformer.h.5.attn.attn.lora_A", "transformer.h.5.attn.attn.lora_B", "transformer.h.6.attn.attn.lora_A", "transformer.h.6.attn.attn.lora_B", "transformer.h.7.attn.attn.lora_A", "transformer.h.7.attn.attn.lora_B", "transformer.h.8.attn.attn.lora_A", "transformer.h.8.attn.attn.lora_B", "
Anybody can look into this issue? Thanks!

**Comment by JustinGoheen** [comment]
Hi @richardsun-voyager 👋   I have a couple of questions:

1. Does this error occur while loading here, or after this operation while loading the checkpoint to a model? 
2. If the error occurs exactly at `checkpoint = torch.load(str(checkpoint_path), mmap=True)`: What happens when `mmap` is left as `None`?

**Comment by carmocca** [comment]
@richardsun-voyager What script did you run exactly? `finetune/lora.py` loads with `strict=False` by default: https://github.com/Lightning-AI/lit-gpt/blob/main/finetune/lora.py#L125

Looks like you missed passing the filepath to the lora weights. You could anternatively set `strict=False` depending on what's your intention

**Comment by richardsun-voyager** [comment]
> Hi @richardsun-voyager 👋 I have a couple of questions:
> 
> 1. Can you post the full stack trace, please.
> 2. Does this error occur while loading `checkpoint = torch.load(str(checkpoint_path), mmap=True)`, or after this operation while loading the checkpoint to a model?
> 3. If the error occurs exactly at `checkpoint = torch.load(str(checkpoint_path), mmap=True)`: What happens when `mmap` is left as `None`?
Thanks for your reply!
It seems the issue is gone. I replaced the original code (loading wweights) in finetune/lora.py with the following.
"    with fabric.init_module(empty_init=True), quantization(quantize):
        model = GPT(config)#.bfloat16()
    checkpoint = torch.load(str(checkpoint_path), mmap=True)
    model.load_state_dict(checkpoint.get("model", checkpoint), 
                          strict=False)
"
But another issue arose when calling the "validate" function in finetune/lora.py.

**Comment by richardsun-voyager** [comment]
> 

Thank you! I used the code as follows,
"" with fabric.init_module(empty_init=True), quantization(quantize):
model = GPT(config)#.bfloat16()
checkpoint = torch.load(str(checkpoint_path), mmap=True)
model.load_state_dict(checkpoint.get("model", checkpoint),
strict=False)
"

**Comment by carmocca** [comment]
What is the pending issue?

**Comment by asimj1342** [comment]
same issue, pretrained a model using litgpt and trying to finetune that model passed GPT from lora and getting error:
`    self.lightning_module.load_state_dict(checkpoint["state_dict"], strict=strict)
  File "/home/miniforge3/envs/worker/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LlamaLMM:
        Missing key(s) in state_dict: "model._orig_mod.transformer.h.0.attn.attn.lora_A", "model._orig_mod.transformer.h.0.attn.attn.lora_B", "model._orig_mod.transformer.h.0.attn.proj.lora_A", "model._orig_mod.transformer.h.0.attn.proj.lora_B", "model._orig_mod.transformer.h.1.attn.attn.lora_A", "model._orig_mod.transformer.h.1.attn.attn.lora_B", "model._orig_mod.transformer.h.1.attn.proj.lora_A", "model._orig_mod.transformer.h.1.attn.proj.lora_B", "model._orig_mod.transformer.h.2.attn.attn.lora_A", "model._orig_mod.transformer.h.2.attn.attn.lora_B", "model._orig_mod.transformer.h.2.attn.proj.lora_A", "model._orig_mod.transformer.h.2.attn.proj.lora_B", "model._orig_mod.transformer.h.3.attn.attn.lora_A", "model._orig_mod.transformer.h.3.attn.attn.lora_B", "model._orig_mod.transformer.h.3.attn.proj.lora_A", "model._orig_mod.transformer.h.3.attn.proj.lora_B", "model._orig_mod.transformer.h.4.attn.attn.lora_A", "model._orig_mod.transformer.h.4.attn.attn.lora_B", "model._orig_mod.transformer.h.4.attn.proj.lora_A", "model._orig_mod.transformer.h.4.attn.proj.lora_B", "model._orig_mod.transformer.h.5.attn.attn.lora_A", "model._orig_mod.transformer.h.5.attn.attn.lora_B", "model._orig_mod.transformer.h.5.attn.proj.lora_A", "model._orig_mod.transformer.h.5.attn.proj.lora_B", "model._orig_mod.transformer.h.6.attn.attn.lora_A", "model._orig_mod.transformer.h.6.attn.attn.lora_B", "model._orig_mod.transformer.h.6.attn.proj.lora_A", "model._orig_mod.transformer.h.6.attn.proj.lora_B", "model._orig_mod.transformer.h.7.attn.attn.lora_A", "model._orig_mod.transformer.h.7.attn.attn.lora_B", "model._orig_mod.transformer.h.7.attn.proj.lora_A", "model._orig_mod.transformer.h.7.attn.proj.lora_B". 
`
