### ISSUE TITLE
Using multi-gpu to pre-train on Slurm

### ISSUE THREAD

**Issue by yuzc19** [Lightning-AI/lit-gpt#493]
Hi, I am using Slurm to run this fabric-based script pretrain/openwebtext.py and set the devices as 8.

<img width="928" alt="Screenshot 2023-09-03 at 12 12 57" src="https://github.com/Lightning-AI/lit-gpt/assets/53684662/51042fa8-3c6a-4292-b39d-1ee716e171c9">

However, there is only one GPU used (). I use torch.cuda.device_count() to count the accessible GPUs, which returns 8 as expected.

<img width="640" alt="Screenshot 2023-09-03 at 12 11 49" src="https://github.com/Lightning-AI/lit-gpt/assets/53684662/23176b73-0d19-42a7-af8e-e0d30854f3fd">

<img width="891" alt="Screenshot 2023-09-03 at 12 12 09" src="https://github.com/Lightning-AI/lit-gpt/assets/53684662/aa4c9058-4d7e-4ea5-8fbf-b59aa2d69d80">

So could anyone tell me what is happening and how to solve this problem? Thank you!

**Comment by rasbt** [comment]
Hm, I must admit that I don't know what's going on here. Maybe @awaelchli has a few ideas? Does it maybe require setting `cluster_environment` in `FSDPStrategy` and `world_size`?

**Comment by yuzc19** [comment]
Yeah, when I print fabric.world_size, it returns 1. It is really weird.

**Comment by awaelchli** [comment]
> Does it maybe require setting cluster_environment in FSDPStrategy and world_size?

No this is not needed and it is not documented anywhere that this should be set. 

@yuzc19 Your screenshot clearly shows that the devices flag is set to 1, and Fabric launches 1 process. You asked for 1 device, and it will use 1 device as expected (by default the first if multiple are available).

To run on slurm, simply follow this guide: https://lightning.ai/docs/fabric/stable/guide/multi_node/slurm.html#run-on-a-slurm-managed-cluster
You can find this guide simply by searching the term "slurm" in the docs search bar.

**Comment by yuzc19** [comment]
Thank you for the guide. I just need to set --ntasks-per-node the same as the devices when calling srun. It would be great if someone found it helpful.
