### ISSUE TITLE
Finetune LLAMA-2-70b with Lora on 8 A100(80G)

### ISSUE THREAD

**Issue by jiaaoc** [Lightning-AI/lit-gpt#506]
Hi, 

Is there a way to finetune LLAMA-2-70b using the lora scripts on 8 A100 GPUs?

**Comment by rasbt** [comment]
yeah, here in line 35 you could set `devices=8`:

https://github.com/Lightning-AI/lit-gpt/blob/e6ff37c03c39e6dcff6c41362eb16e5408b16186/finetune/lora.py#L35

If you run into OOM issues, you might find this guide useful: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/oom.md

**Comment by jiaaoc** [comment]
I have set the devices to 8. However, it still runs into OOM issues. 

Also, in the initialization, it shows

`Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes`

which seems to only use one of the GPUs?

And this might result in the OOM issue:

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.60 GiB. GPU 0 has a total capacty of 79.15 GiB of which 555.25 MiB is free. Including non-PyTorch memory, this process has 78.60 GiB memory in use. Of the allocated memory 78.10 GiB is allocated by PyTorch, and 96.47 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by rasbt** [comment]
Hm, that's strange. Based on the snippet your shared above, it looks like it's only using 1 GPU. 

you could try to insert a

```python
print("Devices available:", torch.cuda.device_count())
print("Devices specified:", devices)
```

to make sure these GPUs are indeed available and selected. It happened to me that I sometimes had too many local copies of the file and accidentally used the wrong file when changing the setting.

**Comment by jiaaoc** [comment]
This is the output when i am trying 6:

```
6
<lightning.fabric.strategies.fsdp.FSDPStrategy object at 0x7f92dd482550>
Devices available: 6
Devices specified: 6
{'eval_interval': 50, 'save_interval': 50, 'eval_iters': 100, 'log_interval': 1, 'devices': 6, 'learning_rate': 0.0003, 'batch_size': 128, 'micro_batch_size': 1, 'gradient_accumulation_iters': 128, 'max_iters': 20000, 'weight_decay': 0.01, 'lora_r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05, 'lora_query': True, 'lora_key': False, 'lora_value': True, 'lora_projection': False, 'lora_mlp': False, 'lora_head': False, 'warmup_steps': 100}
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
----------------------------------------------------------------------------------------------------

[rank: 0] Global seed set to 1337
```

**Comment by rasbt** [comment]
Hm, that's strange. It seems it's still somehow not using the multiple GPUs in your case somehow:

```
Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All distributed processes registered. Starting with 1 processes
``` 

Let me try this on my machine tomorrow; it used to work fine but maybe there was a recent change that somehow set this to 1 device somewhere.

**Comment by jiaaoc** [comment]
It should be something to do with slurm cluster. I can now utilize all the GPUs. 

However, I am having the cpu OOM issues when using 8 GPUs, similar to #456

**Comment by rasbt** [comment]
> It should be something to do with slurm cluster. I can now utilize all the GPUs.

Glad this part works at least now

**Comment by jiaaoc** [comment]
Yes, that part works!

Any updates on #456 ? My RAM is also around 1T. It fails to load the model (will kill some process probably due to the ram OOM) using fsdp when I use more than 4 A100(80G) for lora-finetuning with bf16-true.
