### ISSUE TITLE
Code Style: type annotations

### ISSUE THREAD

**Issue by Andrei-Aksionov** [Lightning-AI/lit-gpt#511]
Hi there 👋 

I have observed that in certain sections of the code, there are type annotations for functions/methods, whereas in other sections, there are either no annotations at all or no return type annotations present.
Perhaps for the uniformity, it's worth to add type annotations everywhere? Maybe everywhere except for tests.

If this issue is accepted, which style of type annotations should be used: the current one (`Optional[int]`) or a more modern one (`int | None`)?

**Comment by carmocca** [comment]
I'd accept sensible type annotations to the source code and scripts.
You can manually run mypy to see what's missing/failing, but there is no mypy job setup in CI and there are no plans to add one.

Since we support Python 3.8, the old notation needs to be used.

**Comment by Andrei-Aksionov** [comment]
> You can manually run mypy to see what's missing/failing, but there is no mypy job setup in CI and there are no plans to add one.

I use `ruff` in the editor, and then I can run `mypy`.

---

> Since we support Python 3.8, the old notation needs to be used.

Well, didn't know that. I don't see any mentioning on the main page that the oldest supported version is 3.8.
Maybe add a badge?
Like this one: https://github.com/Andrei-Aksionov/nanoGPTplus/blob/main/assets/readme/python_versions.svg
![image](https://github.com/Lightning-AI/lit-gpt/assets/58434077/7aa2efd2-16f7-406f-a601-a1ba0709cef3)
You can also tweak svg file to add 3.11 or can make it simpler: 3.8 +.

**Comment by carmocca** [comment]
I said it but I have no proof of it. CI is setup to use 3.10 only: https://github.com/Lightning-AI/lit-gpt/blob/main/.github/workflows/cpu-tests.yml#L24-L26
The reason I assumed so is because it's what `lightning` supports.

Feel free to add the badge. We already have some in the README.
