### ISSUE TITLE
Convert Lora Weights Port

### ISSUE THREAD

**Issue by ExcPoint** [Lightning-AI/lit-gpt#517]
The lit-llama repository has script for converting llora weights. This is crucial for converting the model to different formats to use in the wild. 

I propose porting this over into lit-gpt.

Reference:
https://github.com/Lightning-AI/lit-llama/blob/main/howto/convert_lora_weights.md

**Comment by rasbt** [comment]
Totally agree that we need that. I think what you are asking for is what I implemented here in #495?

It already works for finetuning btw. For some reason there is still an issue when using the merged model with `generate/base.py` though

**Comment by ExcPoint** [comment]
Incredible! I'll take a look at the generate/base.py file and see if there's anything I can make of it.
