### ISSUE TITLE
New sequence length error in LoRA script

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#541]
Originally when I added the LIMA dataset, I had a max_len setting to set the maximum sequence length. We removed it in favor of the `override_max_len` argument in e.g., `finetune/lora.py`

Now, when preparing LIMA:

```bash
python scripts/prepare_lima.py --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf/
```

and then finetuning with LoRA (after setting `override_max_seq_length=2048`) :

```bash
python finetune/lora.py --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf/ --data_dir data/lima/
```

the following error occurs:

```python
ValueError: Cannot forward sequence of length 2431, max seq length is only 2048.
```

I suspect this is maybe due to some recent changes. It's also probably not LIMA but affects all datasets.

**Comment by carmocca** [comment]
Yes, this is due to my recent changes which touched how this is handled. I think it's best that we add back a configurable `max_seq_length` to the `prepare_*` scripts for the case where the model's max_sequence_length is limited at runtime.
