### ISSUE TITLE
New precision issues when running with default settings

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#542]
There also seem to be new issues in LoRA finetuning when just using the default settings. I.e.,

```python
RuntimeError: index_copy_(): self and source expected to have the same dtype, but got (self) Float and (source) BFloat16
```

This also happens when using

```python
python scripts/prepare_lima.py --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf/

python finetune/lora.py --checkpoint_dir checkpoints/meta-llama/Llama-2-7b-hf/ --data_dir data/lima/
```

without specifying `--precision "bf16-true"`. 

This happens with other models as well, e.g., our default stablelm 3B model via

```python
python finetune/lora.py
```

**Comment by carmocca** [comment]
Thanks for reporting. I'll look into it. To clarify, it's only a problem with `--precision bf16-mixed` but not `--precision bf16-true`?
