### ISSUE TITLE
Regarding NeurIPS 2023 LLM Efficiency Challenge, when using devices greater than 1 and using fsdp, inference fails.

### ISSUE THREAD

**Issue by MrJungle1** [Lightning-AI/lit-gpt#547]
@aniketmaurya @rasbt  I use this code [https://github.com/Lightning-AI/lit-gpt/blob/aniket/helm/eval/helm/main.py]( https://github.com/Lightning-AI/lit-gpt/blob/aniket/helm/eval/helm/main.py)，but when the devices here are set to greater than 1 and strategy="fsdp", it will not work properly. Using curl to access 8080, the request cannot be made. uvicorn.run is executed twice when devices=2 when, resulting in the second ERROR: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8080): address already in use

**Comment by carmocca** [comment]
The challenge requires that a single device be used. See the challenge description here: https://llm-efficiency-challenge.github.io/challenge

**Comment by aniketmaurya** [comment]
hi @MrJungle1, are you looking into deploying Lit-GPT? May I ask the model size and GPU config you are using?

**Comment by MrJungle1** [comment]
I want to use the llama2-70b to use 8 GPUs on the A100 40g



发自我的iPhone


------------------ Original ------------------
From: Aniket Maurya ***@***.***&gt;
Date: Mon,Sep 18,2023 6:18 PM
To: Lightning-AI/lit-gpt ***@***.***&gt;
Cc: MrJungle1 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [Lightning-AI/lit-gpt] Regarding NeurIPS 2023 LLM EfficiencyChallenge, when using devices greater than 1 and using fsdp, inference fails.(Issue #547)





 
hi @MrJungle1, are you looking into deploying Lit-GPT? May I ask the model size and GPU config you are using?
