### ISSUE TITLE
Predicting sequences longer than model context length

### ISSUE THREAD

**Issue by nihalsid** [Lightning-AI/lit-gpt#556]
I'm trying to predict sequences longer than context size, e.g. greater than length 4096 for Llama7B. One way I can do this is by moving a window with context length - 1 tokens and keep predicting the next. However this is significantly slower than the key value caching used to predict the first 4096 tokens. 

Is there a way that the kv cache can be adapted to predict longer sequences as well (e.g. by rolling the caches, and instead of storing non-roped keys in the cache?)

**Comment by carmocca** [comment]
You could do this by reverting the changes in this PR: https://github.com/Lightning-AI/lit-gpt/commit/6384da18bde929a448582a60ab32076805c0d2d9
