### ISSUE TITLE
Import error in finetune/lora.py

### ISSUE THREAD

**Issue by bryfry** [Lightning-AI/lit-gpt#558]
While following the [`finetuning_lora.md`](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/finetune_lora.md) tutorial and at the  [finetuning step](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/finetune_lora.md#merging-lora-weights) the below command yields an import error.

```bash
python finetune/lora.py \
    --checkpoint_dir "checkpoints/tiiuae/falcon-7b" \
    --data_dir "data/alpaca" \
    --out_dir "out/lora/alpaca"
```

```
Traceback (most recent call last):
  File "/home/ubuntu/llm/git/lit-gpt/finetune/lora.py", line 29, in <module>
    from scripts.prepare_alpaca import generate_prompt
ModuleNotFoundError: No module named 'scripts.prepare_alpaca'
```

I found a similar [error thread](https://github.com/Lightning-AI/lit-gpt/issues/386#issuecomment-1722251171) and reported it there, but was informed that this was worth opening a new ticket.

### Potential solution

- `touch scripts/__init__.py`
- `cd finetune; ln -s ../scripts`

**Comment by tranxuantuyen** [comment]
Same with me, and I don't understand why

**Comment by carmocca** [comment]
Interesting, perhaps there are 2 lit_gpt versions in available in sys.path and that's where this strange issues comes from. If somebody is facing this issue and wants to verify, you can investigate what's in your sys.path by calling `python -m site`

**Comment by carmocca** [comment]
I found out the cause of this issue. The problem appears after installing https://github.com/EleutherAI/lm-evaluation-harness because it creates the directory `/home/carlos/venv/lib/python3.10/site-packages/scripts` which gets picked up before our local `scripts` directory. I'll see how we can fix it

cc @rasbt

**Comment by carmocca** [comment]
Opened https://github.com/EleutherAI/lm-evaluation-harness/issues/901
