### ISSUE TITLE
1.3 B Phi 1.5 checkpoints (better than Llama 2)

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#568]
We should probably add phi 1.5 checkpoints. It's an open-source 1.3B model from Microsoft that is on par with larger 7B models like Llama 2. It'd be especially nice for those who currently have OOM issues.

 It could also become our new default LLM replacing 3B StableLM.

- Paper: https://arxiv.org/abs/2309.05463
- Checkpoints: https://huggingface.co/microsoft/phi-1_5

**Comment by carmocca** [comment]
After a skim of https://huggingface.co/microsoft/phi-1_5/blob/main/modeling_mixformer_sequential.py, I don't see any big architectural different that would block this

**Comment by carmocca** [comment]
@rasbt Phi support is ready at #569. Would you like to address tutorial/README changes yourself?

**Comment by rasbt** [comment]
@carmocca  Added docs for that model. Btw do you think it's a good idea to modify all tutorials to use that model as the new default model then? I can do that but probably better to be done in a separate PR after merging. What do you think?

**Comment by carmocca** [comment]
I would be fine with this. It'll take a lot of effort to rerun everything though
