### ISSUE TITLE
lit-gpt error with quantize lib

### ISSUE THREAD

**Issue by QuyAnh2005** [Lightning-AI/lit-gpt#574]
I got this error in [block code](https://github.com/Lightning-AI/lit-gpt/blob/966646a428546360a9857ac7814869cc72ff6edb/lit_gpt/utils.py#L68C9-L72C94)  when I ran sample solution for **NeurIPS 2023 Large Language Model Efficiency Challenge: 1 LLM + 1 GPU + 1 Day**

```
from quantize.bnb import Linear4bit

class QuantizedLinear(Linear4bit):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, quant_type="nf4", compress_statistics=True, **kwargs)
```

![image](https://github.com/llm-efficiency-challenge/neurips_llm_efficiency_challenge/assets/80700452/ccf03786-e3d2-49be-a459-2991e38d0750)

but, how to fix?

**Comment by carmocca** [comment]
I opened #579 which will provide a better error message, note however that it will still error because you would only get this when `bitsandbytes` is not installed
