### ISSUE TITLE
Adding Persimmon 8B -- apparently the best LLM of that size at the moment

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#581]
According to some people (and the [official release](https://www.adept.ai/blog/persimmon-8b)) Persimmon 8B appears to be the most capable LLM of that size class at the moment. It's also fully open-source.

The base model might be particularly interesting to NeurIPS challenge participants. Here are the checkpoint files if we want to add this:

- [persimmon-8b-chat](https://huggingface.co/adept/persimmon-8b-chat)
- [persimmon-8b-base](https://huggingface.co/adept/persimmon-8b-base)

**Comment by carmocca** [comment]
The model definition is at https://github.com/huggingface/transformers/tree/main/src/transformers/models/persimmon

There are some key unimplemented things required:
- MLP dropout
- QK layernorm in attention
- Squared ReLU

We might want to gauge interest first before adding these just for this model.

**Comment by rasbt** [comment]
It's interesting, but maybe not a high priority. Thanks for looking into that!
