### ISSUE TITLE
LoRA: unexpected slowdown during backward pass when `self.lora_ind` is placed on a CUDA device 

### ISSUE THREAD

**Issue by Andrei-Aksionov** [Lightning-AI/lit-gpt#593]
Hi there 👋 

The problem is a part of my [performance study](https://github.com/Lightning-AI/lit-gpt/issues/461), yet it deserves a separate issue.

> [!NOTE]
> More details one can find in the [issue](https://github.com/Lightning-AI/lit-gpt/issues/461#issuecomment-1721613440).

> [!IMPORTANT]
> All numbers/profile traces were created on 1x Nvidia `T4`, `Pythia-410m` and `16-mixed` precision.

Currently, we store `self.lora_ind` as a python list and during each `zero_pad` call we create a tensor on the target device with these indices. 
https://github.com/Lightning-AI/lit-gpt/blob/cc190152085ac60fe708455b2df8877f82d37087/lit_gpt/lora.py#L293-L295

The problem is that it causes slowdowns because of the `CudaStreamSynchronize` that happens as we copy data from host to device.
<img width="1040" alt="Screenshot 2023-09-15 at 8 06 45 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/58434077/22603c45-863b-4dee-8f1e-bee2049b81f7">

If to create a tensor on a device with `self.lora_ind` during initialization, we can get rid of that bottleneck:
<img width="1110" alt="Screenshot 2023-09-27 at 3 44 26 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/58434077/d0bf8c22-41ee-439e-8f0b-d225538a2fe8">

Which results in `zero_pad` time decrease from `~ 4.1 ms` to `243 μs`, the whole forward pass time (for all blocks) decreases from `~175 ms` to `~85 ms`.

---- 

### So, what's the problem then?

While the forward pass time decreases, the backward pass time - increases: from `~85 ms` to `~ 141 ms`. 

> [!NOTE]
> Combined time `forward + backward` with the indices placed on a GPU during init method decreases from `~272 ms` to `~229 ms`; 1k iters LoRA fine-tune decreases from `166.7 seconds` to `158.2 seconds`.

### How significantly code was changed?

Not significantly. Here is the diff:
![image](https://github.com/Lightning-AI/lit-gpt/assets/58434077/36a63fb6-df0b-4ecf-a98f-5238ab53f1e6)

### What is the reason for it?

For now my suspect is that a lot of transpose generic kernels are used (`cudnn::ops::genericTranspose_kernel …`) - blue boxed at stream 13 and 14.
![image](https://github.com/Lightning-AI/lit-gpt/assets/58434077/5f47cf55-03b5-4ce6-802b-04eb76a03ffc)

And these generic transpose kernels are not used during backward pass (only during forward pass) with the code from the main branch (when during every zero_pad call the indices are copied to a tensor).
<img width="630" alt="Screenshot 2023-09-27 at 4 03 06 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/58434077/c89864ee-7411-41cf-83b8-374484743a1f">

Why it's happening I don't have a clue 🤷  (for now).

----

For anyone who is curious enough, here are the trace files:
[zero_pad_t4_main.json.gz](https://github.com/Lightning-AI/lit-gpt/files/12738891/zero_pad_t4_main.json.gz): trace for the code from the main branch
[zero_pad_t4_main_smallest_example.json.gz](https://github.com/Lightning-AI/lit-gpt/files/12738892/zero_pad_t4_main_smallest_example.json.gz): code from the main with only `lora_ind` placed on a device and no new tensor creation during each `zero_pad` call.

These trace files are intended to be opened in a Google Chrome: type `chrome://tracing` and drag-and-drop those traces there.

**Comment by Andrei-Aksionov** [comment]
For now my plan is to try out [Holistic Trace Analysis](https://github.com/facebookresearch/HolisticTraceAnalysis) which I found out from this [pytorch.org/blog](https://pytorch.org/blog/trace-analysis-for-masses/).

**Comment by Andrei-Aksionov** [comment]
I tried HTA (Holistic Trace Analysis), used its functionality to compare two traces and put my findings in the [notebook](https://github.com/Andrei-Aksionov/lit-gpt/blob/a5bc5b022a2ecf01b2d0c0e04a342135d56a4687/notebooks/HolisticTraceAnalysis/trace_diff.ipynb).

There are some strange things.
If to compare count decrease of operators, we see:
- On CPU: decrease in `aten:to`, `aten:copy_`, `aten:to_copy`, ...
- On GPU: decrease in `Memcpy HtoD (Pageable -> Device)`

and they are reduced by 24 which makes sense, as the profiling was done on `Pythia-410m` that has 24 blocks and thus 24 `zero_pad` calls.

But if to take a look at the change in the duration of operators we can see that there is a significant change in `backward`, `cudaLaunchKernel`, `SliceBackward`, `aten:item`, ... and it's on a CPU! And it's a significant one, by a factor of ~2-3.
There is a difference on a GPU also, mainly with `cudnn:ops:genericTranspose_kernel`, but it's much less pronounced.

Also take a look in the notebook at the number of changes in CPU kernels: a lot were added, deleted, increased and decreased.
On a GPU there is only one change: deletion of `Memcpy HtoD (Pageable -> Device)` kernel, which totally makes sense.

What I also don't understand is why on CPU `cudaDeviceSynchronize` operator and kernel were added? There is no reason why it should have happened.

*So it looks like the slowdown is happening on a CPU and that, given the changes to the code that were made, makes me very frustrated (and curious).*

----

I've read online that each CUDA stream has a limit of operators it can handle, some sort of queue, some maybe by eliminating host-to-device copying this queue was overflowed 🤷.
Before there was a `cudaDeviceSynchronize` call that, quite possibly, gave some time for a GPU to free up that queue.
Luckily HTA provides a tool to measure it, so I'll add info about it a bit later.

**Comment by rasbt** [comment]
Thanks for doing this! This is a bit above my head but I can confirm that LoRA is slightly slower now than it was a few months back. 

In July, I got the following for 50k Falcon 7B iterations with a batch size of 1 on an A100:

- Falcon 7B with LoRA: 69 min
- Falcon 7B with Adapter v1: 69 min

Now LoRA is behind Adapter and the original scores:

- Falcon 7B with LoRA: 93 min
- Falcon 7B with Adapter v1: 66 min

**Comment by Andrei-Aksionov** [comment]
HTA provides ability to measure memory bandwidth and CUDA stream queue length: [docs](https://hta.readthedocs.io/en/latest/source/features/augmented_counters.html).

> Memory bandwidth counters measure the memory copy bandwidth used while copying the data from H2D, D2H and D2D by memory copy (memcpy) and memory set (memset) events. HTA also computes the number of outstanding operations on each CUDA stream. We refer to this as queue length. When the queue length on a stream is 1024 or larger new events cannot be scheduled on that stream and the CPU will stall until the events on the GPU stream have processed.

### Memory bandwidth

Let's first start with memory bandwidth between `control` (code from the main branch) and `test` (indices on GPU).
<img width="883" alt="Screenshot 2023-10-04 at 6 45 23 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/58434077/2b057961-8ee4-4d39-82ea-6bb346d98bc1">

The only significant change is in `Memcpy HtD (Host-to-Device)` count - a decrease from 52 to 4. The remaining 4 is, as I understand, for copying training data from CPU to GPU (micro-batch size of 4 was used). 
The most interesting part here is that despite the significant change in the count of such operations, the bandwidth itself is not that different. That shows that the biggest issue with `HtD` copying is not that we need to copy something, but the fact that the `CudaStreamSynchronize` is called every time, and it might be really-really costly (though it is situation specific).

### CUDA stream queue length

<img width="883" alt="Screenshot 2023-10-04 at 6 53 01 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/58434077/ab5f252b-2ee3-4a7f-bfd1-905eebeb8d7b">

That is the difference that might explain the slowdown.
Quite a significant change on streams 13, 14 and especially on 7. 
On stream 7 the count is actually decreased from 11904 to 11808 (delta is 96), but the mean queue length increased from 203 to 672 (3.3x). This can be explained by my assumption that previously there was a `cudaStreamSynchronize` call, caused by `HtD` copying during new tensor creation out of `self.lora_ind`, and that gave the stream time to free up it a little bit.

### CUDA stream queue length (traces visualization)

Let's take a look at the `control` profile trace (code from the main).
<img width="770" alt="Screenshot 2023-10-04 at 7 02 50 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/58434077/c284bfd3-0a5f-4ebc-9b1e-25d0919f26bd">

Here streams 13 and 14 are mostly busy (ever so slightly) during forward pass, while 7, 29 and 30 - during backward.
Note: "thread 6782 (python)" is for backward pass, so this should indicate for you where forward stops and backward starts.

And this is how `test` profile trace (indices are placed on GPU) looks like.

<img width="770" alt="Screenshot 2023-10-04 at 7 04 08 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/58434077/74cd2088-1ac0-40c1-a8a9-81d20cce7336">

Here we see that all the stream are much more saturated.

The stream 7 is maxed out - just take a look at the plateau:
<img width="1192" alt="Screenshot 2023-10-04 at 7 16 19 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/58434077/93aa2292-dfc1-4f4d-8403-7de75f9e5cda">

And what's more interesting is that this max saturation happens exactly during the backward pass.

-----

### Result

So I guess this is the answer: the slowdown is happening because the **stream # 7** (its queue length) **is maxed out** during backward pass, which means that it cannot start processing what CPU is already prepared for it and thus **CPU is waiting till GPU (the stream) is freed up**.

----

#### Resources

- [Notebook](https://github.com/Andrei-Aksionov/lit-gpt/blob/4aa0e0ef48944806888f96dc82af1e64bb404af3/notebooks/HolisticTraceAnalysis/augmented_counters.ipynb) with the summary.
- Traces with queue length of each stream:
   -  [zero_pad_t4_main_with_counters.json.gz](https://github.com/Lightning-AI/lit-gpt/files/12805894/zero_pad_t4_main_with_counters.json.gz): with the code from the main (`control`)
   - [zero_pad_t4_main_smallest_example_with_counters.json.gz](https://github.com/Lightning-AI/lit-gpt/files/12805928/zero_pad_t4_main_smallest_example_with_counters.json.gz): indices on a GPU (`test`)

**Comment by Andrei-Aksionov** [comment]
Now the question is why it's happening. 🤔 

Here is my checklist:
1. Try different versions of PyTorch (I used nightly version).
2. Try to eliminate fabric to see if the vanilla PyTorch will do the same.
3. ....
4. Profit.

In all seriousness, I almost exhausted my ideas/assumptions of why it is happening.
It's time to ask for a help: @awaelchli @carmocca @robieta 

![image](https://github.com/Lightning-AI/lit-gpt/assets/58434077/b194bea6-bb7b-4e7a-9874-f994f7d0665a)

**Comment by Andrei-Aksionov** [comment]
Ladies and Gentlemen, we have the solution. 🍻 
The problem was, as I stated before, is that CUDA for some reason couldn't properly manage the per-stream workload and as a result they were overflowed and thus CPU was stalling/idling.

The solution is quite simple: upgrade from CUDA 11.8 (that was used before) to CUDA 12.1 (the newest one).
As a result, with indices placed on a GPU the forward pass is faster than the code from the main branch, while the backward takes the same time (as expected). 
There are no CUDA stream overflows:
<img width="759" alt="Screenshot 2023-10-06 at 3 00 59 PM" src="https://github.com/Lightning-AI/lit-gpt/assets/58434077/911803c4-171a-41af-a3fc-ebab986fbb40">
and no usage of generic transpose kernels was noticed.

Given that the current main uses the latest PyTorch with the latest CUDA we are all set.

**Comment by rasbt** [comment]
> Ladies and Gentlemen, we have the solution. 🍻
The problem was, as I stated before, is that CUDA for some reason couldn't properly manage the per-stream workload and as a result they were overflowed and thus CPU was stalling/idling.

> The solution is quite simple: upgrade from CUDA 11.8 (that was used before) to CUDA 12.1 (the newest one).
As a result, with indices placed on a GPU the forward pass is faster than the code from the main branch, while the backward takes the same time (as expected).
There are no CUDA stream overflows:


Awesome glad to hear that it got automatically fixed with a version update. Thanks so much for all your work here @Andrei-Aksionov !
