### ISSUE TITLE
LoRA merging fails with OOM if model is too large even though models train fine on a single GPU

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#600]
You can train a large model like Falcon 40B on a single GPU if you use low-precision and quantization. However, it is not possible to merge the weights with the base model because it will cause OOM issues. 

So, in a sense, training large models with LoRA is currently useless because you can't merge the weights and hence not use the models in eval & inference. I think I added a `--quantize` setting in the original `merge_lora.py` script as a workaround but now notice that it is gone. 

Is there a plan to bring it back? Or, if not, what would be another suggested workaround for merging?

**Comment by carmocca** [comment]
Adding quantization support to `merge_lora` makes sense. But https://github.com/Lightning-AI/lit-gpt/issues/513 will need to be resolved first
