### ISSUE TITLE
FSDP strategy spawns multiple processes (beyond GPU)

### ISSUE THREAD

**Issue by GrauleM** [Lightning-AI/lit-gpt#605]
First, thanks for the great work on this project!

I am facing an issue when running inference on 2+ GPUs using the FSDP strategy following your examples (using LLaMA2 models): doing this seems to spawn multiple processes, each of which runs the entire code (instead of what I would have expected - only model inference is distributed across multiple GPUs). 

One way to reproduce this behavior is by adding a print statement in generate/base.py after `L.seed_everything()`; the statement will be executed num_proc times. 

Fyi, the issue does not just occur with print statements; for example, you can try to establish a TCP socket right after `L.seed_everything()` at a pre-specified port and you will get an error indicating that the socket address is already in use from num_proc-1 processes. 

This may be related to some of the OOM / memory leak issues with FSDP; e.g. #571 #592

**Comment by konstantinjdobler** [comment]
I think this is expected behavior, e.g. native PyTorch DDP will also create multiple processes (one for each device) that run the entire code.

**Comment by GrauleM** [comment]
Hmmm, I see. I think for easy integration of Lit-GPT within custom applications it would be really useful to have a clean way to separate multi-device GPU inference from the main process (which may contain other compute-heavy tasks). I would appreciate any pointers on how to best achieve this.

**Comment by GrauleM** [comment]
Ok, thank you!
