### ISSUE TITLE
Can you provide an instruction llm finetune tutorial?

### ISSUE THREAD

**Issue by universewill** [Lightning-AI/lit-gpt#615]
Can you provide an instruction llm finetune tutorial or python script?

**Comment by rasbt** [comment]
The instruction-finetuning examples are here:

- Full (all parameters): [tutorials/finetune_full.md](tutorials/finetune_full.md)
- LoRA: [tutorials/finetune_lora.md](tutorials/finetune_lora.md)
- Adapter: [tutorials/finetune_adapter.md](tutorials/finetune_adapter.md)

Let me know if you have any questions, happy to discuss.
