### ISSUE TITLE
question about lora layer target in finetune/lora.py

### ISSUE THREAD

**Issue by gyuwon12** [Lightning-AI/lit-gpt#636]
Loading 'model.layers.34.mlp.gate_proj.weight' into RAM
Loading 'model.layers.34.mlp.up_proj.weight' into RAM
Loading 'model.layers.34.mlp.down_proj.weight' into RAM
Loading 'model.layers.34.input_layernorm.weight' into RAM
Loading 'model.layers.34.post_attention_layernorm.weight' into RAM

A total of 7 things can be considered when riding the layer to which lora is applied in llama2 (q,k,v, attn output, up, gate, down). It can be displayed like this in the mlp layer during the loading process of the model, but I don't think the lora.py file can be more detailed targets as shown below, so how can I make this possible? Or I wonder what each means.

lora_query = False
lora_key = False
lora_value = False
lora_projection = False
lora_mlp = True
lora_head = False

======================================
GPT(
  (lm_head): QuantizedLinear(in_features=5120, out_features=32000, bias=False)
  (transformer): ModuleDict(
    (wte): Embedding(32000, 5120)
    (h): ModuleList(
      (0-39): 40 x Block(
        (norm_1): RMSNorm()
        (attn): CausalSelfAttention(
          (attn): QuantizedLinear(in_features=5120, out_features=15360, bias=False)
          **(proj): QuantizedLinear(in_features=5120, out_features=5120, bias=False)**
        )
        (norm_2): RMSNorm()
        (mlp): LLaMAMLP(
          (fc_1): QuantizedLinear(in_features=5120, out_features=13824, bias=False)
          **(fc_2): QuantizedLinear(in_features=5120, out_features=13824, bias=False)**
          (proj): QuantizedLinear(in_features=13824, out_features=5120, bias=False)
        )
      )
    )
    (ln_f): RMSNorm()
  )
)

In this case, I want to target (fc_2) layer and (proj) layer

**Comment by Andrei-Aksionov** [comment]
Hello @gyuwon12 

As I understand, you are wondering:
1. What each LoRA parameter in fine-tuning script means.
2. How to apply LoRA to a specific layer of an MLP class.

### 1.

`lora_query`, `lora_key`, `lora_value` applies LoRA to corresponding weight matrices in causal self-attention layer.
`lora_projection` applied LoRA to the projection layer of the output of causal self-attention:
https://github.com/Lightning-AI/lit-gpt/blob/1ec6b75d4bc0484e998a56d4c61f1f9a1df23915/lit_gpt/model.py#L231-L232
`lora_mlp` applies LoRA to **all** layers inside MLP class.
`lora_head` applies LoRA to the layer that maps network's output to vocab's dimensional space:
https://github.com/Lightning-AI/lit-gpt/blob/1ec6b75d4bc0484e998a56d4c61f1f9a1df23915/lit_gpt/model.py#L92-L93


### 2.
The code applies LoRA to all layers of the MLP class.
But it's easy to change, as it is controlled by `r` (rank) parameter:
https://github.com/Lightning-AI/lit-gpt/blob/1ec6b75d4bc0484e998a56d4c61f1f9a1df23915/lit_gpt/lora.py#L613-L623
If it's equal to zero - LoRA is disabled. So one of the solutions might be to apply LoRA to MLP class and manually set `r` to zero for the layer that you don't want LoRA be applied to.

**Comment by gyuwon12** [comment]
I really thank you about your comment!!!

**Comment by Andrei-Aksionov** [comment]
@gyuwon12 You are welcome.
Can we then close this issue?
