### ISSUE TITLE
Using flash attention

### ISSUE THREAD

**Issue by gyuwon12** [Lightning-AI/lit-gpt#637]
I want to use flash attachment, which document should I look at? I installed it, but I don't see any examples or codes, so I'm asking you a question.

**Comment by Andrei-Aksionov** [comment]
Hello @gyuwon12 

There are 2 versions of Flash Attention as of right now.
v1 is supported in the latest version of PyTorch (2.1) and is used inside `torch.nn.functional.scaled_dot_product_attention`. You can see it in the [docs](https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html).
And it is used automatically here:
https://github.com/Lightning-AI/lit-gpt/blob/1ec6b75d4bc0484e998a56d4c61f1f9a1df23915/lit_gpt/model.py#L251-L253

v2 will be supported in PyTorch 2.2, but as of right now you have to install it manually. Instructions can be found in [Readme](https://github.com/Lightning-AI/lit-gpt#setup).
If it's installed – it will be used automatically:
https://github.com/Lightning-AI/lit-gpt/blob/1ec6b75d4bc0484e998a56d4c61f1f9a1df23915/lit_gpt/model.py#L234-L250

**Comment by Andrei-Aksionov** [comment]
In other words if everything is installed it should work automagically 😄.
