### ISSUE TITLE
Include Mistral Models

### ISSUE THREAD

**Issue by windprak** [Lightning-AI/lit-gpt#638]
Will Mistral Models be supported? https://huggingface.co/docs/transformers/main/model_doc/mistral
Performance seems to be quite impressive compared to its size.

**Comment by carmocca** [comment]
See https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/download_mistral.md

**Comment by Jeronymous** [comment]
I opened this issue already : https://github.com/Lightning-AI/lit-gpt/issues/597

Now I note that the support is not complete.

The conversion transformers -> lit_gpt is implemented.
But Mistral does seem to be supported in https://github.com/Lightning-AI/lit-gpt/blob/main/scripts/convert_lit_checkpoint.py#L214

Should I open another issue to suggest supporting more models in `convert_lit_checkpoint.py`?
