### ISSUE TITLE
Multi-GPU training 

### ISSUE THREAD

**Issue by je-santos** [Lightning-AI/lit-gpt#641]
Dear lightning friends,

I'm trying to run the following script on 4 GPUS:

`python finetune/lora.py   --checkpoint_dir checkpoints/mistralai/Mistral-7B-Instru`

I'm getting the following warning:

> /home/user/.conda/envs/llm/lib/python3.11/site-packages/lightning/fabric/wrappers.py:176: You are calling the method `GPT.set_kv_cache()` from outside the model. This will bypass the wrapper from the strategy and result in incorrect behavior in `.backward()`. You should pass your inputs through `GPT.forward()`.

The training is insanely slow.

I have the full log in case that helps:

server:3745001:3745001 [0] NCCL INFO Bootstrap : Using enp66s0f0:128.165.232.96<0>
server:3745001:3745001 [0] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
server:3745001:3745001 [0] NCCL INFO NET/Plugin : No plugin found, using internal implementation
server:3745001:3745001 [0] NCCL INFO cudaDriverVersion 12010
NCCL version 2.18.5+cuda12.1
server:3745040:3745040 [1] NCCL INFO cudaDriverVersion 12010
server:3745042:3745042 [3] NCCL INFO cudaDriverVersion 12010
server:3745041:3745041 [2] NCCL INFO cudaDriverVersion 12010
server:3745042:3745042 [3] NCCL INFO Bootstrap : Using enp66s0f0:128.165.232.96<0>
server:3745040:3745040 [1] NCCL INFO Bootstrap : Using enp66s0f0:128.165.232.96<0>
server:3745041:3745041 [2] NCCL INFO Bootstrap : Using enp66s0f0:128.165.232.96<0>
server:3745042:3745042 [3] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
server:3745041:3745041 [2] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
server:3745042:3745042 [3] NCCL INFO NET/Plugin : No plugin found, using internal implementation
server:3745041:3745041 [2] NCCL INFO NET/Plugin : No plugin found, using internal implementation
server:3745040:3745040 [1] NCCL INFO NET/Plugin : Plugin load (libnccl-net.so) returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory
server:3745040:3745040 [1] NCCL INFO NET/Plugin : No plugin found, using internal implementation
server:3745001:3745235 [0] NCCL INFO NET/IB : No device found.
server:3745001:3745235 [0] NCCL INFO NET/Socket : Using [0]enp66s0f0:128.165.232.96<0>
server:3745001:3745235 [0] NCCL INFO Using network Socket
server:3745040:3745236 [1] NCCL INFO NET/IB : No device found.
server:3745042:3745237 [3] NCCL INFO NET/IB : No device found.
server:3745040:3745236 [1] NCCL INFO NET/Socket : Using [0]enp66s0f0:128.165.232.96<0>
server:3745042:3745237 [3] NCCL INFO NET/Socket : Using [0]enp66s0f0:128.165.232.96<0>
server:3745040:3745236 [1] NCCL INFO Using network Socket
server:3745042:3745237 [3] NCCL INFO Using network Socket
server:3745041:3745238 [2] NCCL INFO NET/IB : No device found.
server:3745041:3745238 [2] NCCL INFO NET/Socket : Using [0]enp66s0f0:128.165.232.96<0>
server:3745041:3745238 [2] NCCL INFO Using network Socket
server:3745041:3745238 [2] NCCL INFO comm 0x5efadcd0 rank 2 nranks 4 cudaDev 2 nvmlDev 2 busId 81000 commId 0xc3b7a5f312eb25a - Init START
server:3745040:3745236 [1] NCCL INFO comm 0x63090eb0 rank 1 nranks 4 cudaDev 1 nvmlDev 1 busId 41000 commId 0xc3b7a5f312eb25a - Init START
server:3745001:3745235 [0] NCCL INFO comm 0x788db4e0 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 1000 commId 0xc3b7a5f312eb25a - Init START
server:3745042:3745237 [3] NCCL INFO comm 0x62489430 rank 3 nranks 4 cudaDev 3 nvmlDev 3 busId c1000 commId 0xc3b7a5f312eb25a - Init START
server:3745040:3745236 [1] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
server:3745040:3745236 [1] NCCL INFO Setting affinity for GPU 1 to ffffffff,ffffffff,ffffffff,ffffffff
server:3745040:3745236 [1] NCCL INFO NVLS multicast support is not available on dev 1
server:3745001:3745235 [0] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC                                                                                 server:3745001:3745235 [0] NCCL INFO Setting affinity for GPU 0 to ffffffff,ffffffff,ffffffff,ffffffff
server:3745001:3745235 [0] NCCL INFO NVLS multicast support is not available on dev 0
server:3745041:3745238 [2] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
server:3745041:3745238 [2] NCCL INFO Setting affinity for GPU 2 to ffffffff,ffffffff,ffffffff,ffffffff
server:3745041:3745238 [2] NCCL INFO NVLS multicast support is not available on dev 2
server:3745042:3745237 [3] NCCL INFO NCCL_P2P_LEVEL set by environment to LOC
server:3745042:3745237 [3] NCCL INFO Setting affinity for GPU 3 to ffffffff,ffffffff,ffffffff,ffffffff
server:3745042:3745237 [3] NCCL INFO NVLS multicast support is not available on dev 3
server:3745041:3745238 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1 [2] 3/-1/-1->2->1 [3] 3/-1/-1->2->1
server:3745041:3745238 [2] NCCL INFO P2P Chunksize set to 131072
server:3745040:3745236 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0 [2] 2/-1/-1->1->0 [3] 2/-1/-1->1->0
server:3745042:3745237 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2 [2] -1/-1/-1->3->2 [3] -1/-1/-1->3->2
server:3745040:3745236 [1] NCCL INFO P2P Chunksize set to 131072
server:3745001:3745235 [0] NCCL INFO Channel 00/04 :    0   1   2   3
server:3745042:3745237 [3] NCCL INFO P2P Chunksize set to 131072
server:3745001:3745235 [0] NCCL INFO Channel 01/04 :    0   1   2   3
server:3745001:3745235 [0] NCCL INFO Channel 02/04 :    0   1   2   3
server:3745001:3745235 [0] NCCL INFO Channel 03/04 :    0   1   2   3
server:3745001:3745235 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 1/-1/-1->0->-1
server:3745001:3745235 [0] NCCL INFO P2P Chunksize set to 131072
server:3745040:3745236 [1] NCCL INFO Channel 00 : 1[1] -> 2[2] via SHM/direct/direct
server:3745001:3745235 [0] NCCL INFO Channel 00 : 0[0] -> 1[1] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 00 : 2[2] -> 3[3] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 01 : 1[1] -> 2[2] via SHM/direct/direct
server:3745001:3745235 [0] NCCL INFO Channel 01 : 0[0] -> 1[1] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 01 : 2[2] -> 3[3] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 02 : 1[1] -> 2[2] via SHM/direct/direct
server:3745001:3745235 [0] NCCL INFO Channel 02 : 0[0] -> 1[1] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 00 : 3[3] -> 0[0] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 02 : 2[2] -> 3[3] via SHM/direct/direct
server:3745001:3745235 [0] NCCL INFO Channel 03 : 0[0] -> 1[1] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 01 : 3[3] -> 0[0] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 02 : 3[3] -> 0[0] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 03 : 2[2] -> 3[3] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 03 : 1[1] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 03 : 3[3] -> 0[0] via SHM/direct/direct
server:3745001:3745235 [0] NCCL INFO Connected all rings
server:3745041:3745238 [2] NCCL INFO Connected all rings
server:3745042:3745237 [3] NCCL INFO Connected all rings
server:3745042:3745237 [3] NCCL INFO Channel 00 : 3[3] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 01 : 3[3] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 02 : 3[3] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 03 : 3[3] -> 2[2] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Connected all rings
server:3745041:3745238 [2] NCCL INFO Channel 00 : 2[2] -> 1[1] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 01 : 2[2] -> 1[1] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 01 : 3[3] -> 0[0] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 02 : 3[3] -> 0[0] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 03 : 2[2] -> 3[3] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 03 : 1[1] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 03 : 3[3] -> 0[0] via SHM/direct/direct
server:3745001:3745235 [0] NCCL INFO Connected all rings
server:3745041:3745238 [2] NCCL INFO Connected all rings
server:3745042:3745237 [3] NCCL INFO Connected all rings
server:3745042:3745237 [3] NCCL INFO Channel 00 : 3[3] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 01 : 3[3] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 02 : 3[3] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 03 : 3[3] -> 2[2] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Connected all rings
server:3745041:3745238 [2] NCCL INFO Channel 00 : 2[2] -> 1[1] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 01 : 2[2] -> 1[1] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 02 : 2[2] -> 1[1] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 03 : 2[2] -> 1[1] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 00 : 1[1] -> 0[0] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 01 : 1[1] -> 0[0] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 02 : 1[1] -> 0[0] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 03 : 1[1] -> 0[0] via SHM/direct/direct
server:3745001:3745235 [0] NCCL INFO Connected all trees
server:3745001:3745235 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
server:3745001:3745235 [0] NCCL INFO 4 coll channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
server:3745042:3745237 [3] NCCL INFO Connected all trees
server:3745042:3745237 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
server:3745042:3745237 [3] NCCL INFO 4 coll channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
server:3745040:3745236 [1] NCCL INFO Connected all trees
server:3745040:3745236 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
server:3745041:3745238 [2] NCCL INFO Connected all trees
server:3745040:3745236 [1] NCCL INFO 4 coll channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
server:3745041:3745238 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
server:3745041:3745238 [2] NCCL INFO 4 coll channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
server:3745042:3745237 [3] NCCL INFO comm 0x62489430 rank 3 nranks 4 cudaDev 3 nvmlDev 3 busId c1000 commId 0xc3b7a5f312eb25a - Init COMPLETE
server:3745040:3745236 [1] NCCL INFO comm 0x63090eb0 rank 1 nranks 4 cudaDev 1 nvmlDev 1 busId 41000 commId 0xc3b7a5f312eb25a - Init COMPLETE
server:3745001:3745235 [0] NCCL INFO comm 0x788db4e0 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 1000 commId 0xc3b7a5f312eb25a - Init COMPLETE
server:3745041:3745238 [2] NCCL INFO comm 0x5efadcd0 rank 2 nranks 4 cudaDev 2 nvmlDev 2 busId 81000 commId 0xc3b7a5f312eb25a - Init COMPLETE
[rank: 2] Seed set to 1339
[rank: 1] Seed set to 1338
[rank: 0] Seed set to 1337
[rank: 3] Seed set to 1340
The longest sequence length in the train data is 1242, the model's maximum sequence length is 1242 and context length is 4096server:3745042:3745237 [3] NCCL INFO Channel 01 : 3[3] -> 0[0] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 02 : 3[3] -> 0[0] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 03 : 2[2] -> 3[3] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 03 : 1[1] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 03 : 3[3] -> 0[0] via SHM/direct/direct
server:3745001:3745235 [0] NCCL INFO Connected all rings
server:3745041:3745238 [2] NCCL INFO Connected all rings
server:3745042:3745237 [3] NCCL INFO Connected all rings
server:3745042:3745237 [3] NCCL INFO Channel 00 : 3[3] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 01 : 3[3] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 02 : 3[3] -> 2[2] via SHM/direct/direct
server:3745042:3745237 [3] NCCL INFO Channel 03 : 3[3] -> 2[2] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Connected all rings
server:3745041:3745238 [2] NCCL INFO Channel 00 : 2[2] -> 1[1] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 01 : 2[2] -> 1[1] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 02 : 2[2] -> 1[1] via SHM/direct/direct
server:3745041:3745238 [2] NCCL INFO Channel 03 : 2[2] -> 1[1] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 00 : 1[1] -> 0[0] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 01 : 1[1] -> 0[0] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 02 : 1[1] -> 0[0] via SHM/direct/direct
server:3745040:3745236 [1] NCCL INFO Channel 03 : 1[1] -> 0[0] via SHM/direct/direct
server:3745001:3745235 [0] NCCL INFO Connected all trees
server:3745001:3745235 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
server:3745001:3745235 [0] NCCL INFO 4 coll channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
server:3745042:3745237 [3] NCCL INFO Connected all trees
server:3745042:3745237 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
server:3745042:3745237 [3] NCCL INFO 4 coll channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
server:3745040:3745236 [1] NCCL INFO Connected all trees
server:3745040:3745236 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
server:3745041:3745238 [2] NCCL INFO Connected all trees
server:3745040:3745236 [1] NCCL INFO 4 coll channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
server:3745041:3745238 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
server:3745041:3745238 [2] NCCL INFO 4 coll channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
server:3745042:3745237 [3] NCCL INFO comm 0x62489430 rank 3 nranks 4 cudaDev 3 nvmlDev 3 busId c1000 commId 0xc3b7a5f312eb25a - Init COMPLETE
server:3745040:3745236 [1] NCCL INFO comm 0x63090eb0 rank 1 nranks 4 cudaDev 1 nvmlDev 1 busId 41000 commId 0xc3b7a5f312eb25a - Init COMPLETE
server:3745001:3745235 [0] NCCL INFO comm 0x788db4e0 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 1000 commId 0xc3b7a5f312eb25a - Init COMPLETE
server:3745041:3745238 [2] NCCL INFO comm 0x5efadcd0 rank 2 nranks 4 cudaDev 2 nvmlDev 2 busId 81000 commId 0xc3b7a5f312eb25a - Init COMPLETE
[rank: 2] Seed set to 1339
[rank: 1] Seed set to 1338
[rank: 0] Seed set to 1337
[rank: 3] Seed set to 1340
The longest sequence length in the train data is 1242, the model's maximum sequence length is 1242 and context length is 4096

**Comment by rasbt** [comment]
Hi there,

unfortunately, I can't help much here and have never seen this exact info or error message before. But if I were to guess, it kind of looks like some issue with the GPU communication related to the NVIDIA drivers. I wonder if it's maybe related to the PyTorch CUDA version you are using in combination with your GPU drivers.

Do you know if you have similar NCCL messages/issues with regular distributed data parallelism and/or single GPU training?

If yes, perhaps trying the cuda 11.8 PyTorch version could help with debugging (pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118)

But @awaelchli or @carmocca may know more and could have some more advice here.

**Comment by je-santos** [comment]
Thanks a lot Sebastian. I'll try to diagnose the issue.
Thanks for your great fine-tuning guides :)

**Comment by windprak** [comment]
I see this warning everytime. I don't think it affected my training speed though
