### ISSUE TITLE
phi-1.5 lm_head bias is not loaded with LoRA/Adapter-v2 fine-tuning

### ISSUE THREAD

**Issue by rlebret** [Lightning-AI/lit-gpt#662]
Unlike other LLMs, phi-1.5 model has bias in the LM head. The pretrained bias is not loaded when fine-tuning phi-1.5 with LoRA or Adapter-v2. It doesn't raise an error when fine-tuning the model as `strict=False` is passed to `load_state_dict()`. However, an error is raised when generating or merging phi-1.5 with LoRA/Adapter-v2 parameters as `strict=True` is used. The following error is raised:

```
RuntimeError: Error(s) in loading state_dict for GPT:
        Missing key(s) in state_dict: "lm_head.linear.bias".
        Unexpected key(s) in state_dict: "lm_head.bias".
```

**Comment by rlebret** [comment]
I've fixed the issue by adding `lm_head.bias` in `_load_from_state_dict` of both `lit_gpt.lora.GPT` and `lit_gpt.adapter_v2.GPT`:

```python
def _load_from_state_dict(self, state_dict: Dict, prefix: str, *args: Any, **kwargs: Any) -> None:
        """For compatibility with base checkpoints."""
        mapping = {
            "lm_head.weight": "lm_head.linear.weight",
            "lm_head.bias": "lm_head.linear.bias"
        }
        state_dict = map_old_state_dict_weights(state_dict, mapping, prefix)
        super()._load_from_state_dict(state_dict, prefix, *args, **kwargs)

```

I'd be happy to create a PR.

**Comment by aniketmaurya** [comment]
@rlebret please feel free to create the PR
