### ISSUE TITLE
[question] NotImplementedError: max_seq_length needs to be ...

### ISSUE THREAD

**Issue by nevermet** [Lightning-AI/lit-gpt#665]
Dear all,

While I was running lora.py, I encountered this message:
 raise NotImplementedError(f"max_seq_length {model.max_seq_length} needs to be >= {max_returned_tokens - 1}")
NotImplementedError: max_seq_length 115 needs to be >= 152

Could you tell me how I can resolve this?

Thanks in advance.

**Comment by carmocca** [comment]
See this comment! https://github.com/Lightning-AI/lit-gpt/issues/559#issuecomment-1723406620
