### ISSUE TITLE
Are the “input” and “output” must be string？ How about json？

### ISSUE THREAD

**Issue by universewill** [Lightning-AI/lit-gpt#670]
Hello，my input is a json-like string, can it be used as the "input" to fine tune the llm models?

For example, can the dataset sample be like:
```
[
    {
        "instruction": "change the given coords",
        "input": {
                            "x":1,
                            "y":1.5
                },
        "output": {
                            "x":1.1,
                            "y":2
                },
    },
    ...
]
```

**Comment by universewill** [comment]
Any help here？ @carmocca

**Comment by carmocca** [comment]
@rasbt or @aniketmaurya Do you have a suggestion here for which preparation script to use? Or any relevant blog link?

**Comment by aniketmaurya** [comment]
I think the easiest way is to convert the JSON into CSV and then use the [prepare_csv.py](https://github.com/Lightning-AI/lit-gpt/blob/main/scripts/prepare_csv.py) script. You can change the `input` and `output` to string.

```bash
>>> x
[{'instruction': 'change the given coords', 'input': {'x': 1, 'y': 1.5}, 'output': {'x': 1.1, 'y': 2}}]

>>> pd.DataFrame(x)
               instruction               input              output
0  change the given coords  {'x': 1, 'y': 1.5}  {'x': 1.1, 'y': 2}

python scripts/prepare_csv.py --csv_path CSV_PATH
```
