### ISSUE TITLE
Allow model configs to have a name  separate from HF hub

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lit-gpt#672]
Currently, the model names in our config.py dictionary need to match exactly an org and checkpoint name of a model on the HF hub. This is probably fine if all our finetuning and inference checkpoints come from the HF hub. But we also have examples where you might want to pretrain a model from scratch, and there you don't need a checkpoint at all. 

In #671 I'm adding tiny-llama, and I intend to add a pretraining script too. I'd like to have the config saved so that it can be easily used to instantiate the tiny llama 1.1B model. Currently, we need to specify a name like this:

```py
config = Config.from_name("TinyLlama-1.1B-intermediate-step-480k-1T")
```

I propose to make the HF hub association optional, and change back to the original purpose of the Config being a short-hand way to quickly instantiate a model by a nickname, like

```py
config = Config.from_name("tiny-llama-1b")
```

For example, the Config could be rewritten like this:

```py
config = {
    name: "short-name-I-remember-2b"
    hf_config: {org: "org-name", name: "long complicated hf name nobody cares"}  # <-- this is optional!
    n_layer: ...
}
```

cc @carmocca

**Comment by carmocca** [comment]
I agree. It would also aid in deduplicating the configs since, for instance, most of the llama-2 based checkpoints have the same config settings with different org names.

Special things to consider are:
- How is a config selected by name vs hf name? What if they are the same? What if they are different?
- Backwards compatibility with saved configuration files

**Comment by awaelchli** [comment]
I think this could help:
- we make the two the same for all existing models
- when loading by name, we first look at "name", then if it doesn't exist we search for the hf-name.
