### ISSUE TITLE
probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by kannangce** [Lightning-AI/lit-gpt#693]
I tried fine-tuning open-llama 3b with quantization using the below command,

```
python finetune/lora.py --precision 16-true --quantize bnb.nf4 --checkpoint_dir checkpoints/$MODEL --out_dir output/code-gen-ui --data_dir data/csv
```

And ran into the error,

> probability tensor contains either `inf`, `nan` or element < 0

Gone through other tickets with same error and got the below suggestions,

- To use the precision as `16-mixed` - This is not possible as I'm using quantization.
- To use `bf16-true` - This is not possible as I'm using T4. And I also don't want to go for a costlier machine if there is a way to make this work.

Is there a way out of this error apart from the above 2 solutions?

**Comment by Andrei-Aksionov** [comment]
Hello @kannangce 

The third option might be to use `32-true` precision, but I am not aware whether it will fit into T4 even with a microbatchsize of 1. 
Could you please give it a try and then report here?

**Comment by kannangce** [comment]
`32-true` worked with T4. But the memory consumption(2X) and time-taken(3X) for each step was high.

**Comment by Andrei-Aksionov** [comment]
Thanks for the report.
For now this is the only what I can suggest given the available graphics card.
