### ISSUE TITLE
flash attention and compile dont stack. 

### ISSUE THREAD

**Issue by artnoage** [Lightning-AI/lit-gpt#695]
It appears that compiling the model in some cases (see Karpathy's Nanogpt, [llama2.c](https://github.com/karpathy/llama2.c)) can make training even faster. Apparently this doesnt stack with flash attentions and some other libraries. 

More specifically I get this error : [rank2]:[2023-10-09 15:38:00,808] [4/0] torch._dynamo.variables.higher_order_ops: [WARNING] speculate_subgraph: while introspecting the user-defined autograd.Function, we were unable to trace function trampoline_autograd_fwd into a single graph. This means that Dynamo was unable to prove safety for this API and will fall back to eager-mode PyTorch, which could lead to a slowdown.
[rank2]:[2023-10-09 15:38:00,809] [4/0] torch._dynamo.variables.higher_order_ops: [ERROR] call_method UserDefinedObjectVariable(fwd) call [TensorVariable(), TensorVariable(), TensorVariable(), ConstantVariable(NoneType), ConstantVariable(float), ConstantVariable(float), ConstantVariable(bool), ConstantVariable(bool), ConstantVariable(NoneType)] {}

The issue has been opened also https://github.com/pytorch/pytorch/issues/93468#issuecomment-1748774273 and in https://github.com/Dao-AILab/flash-attention/issues/596 . I am just opening it so people are aware. If someone finds anything please post.

**Comment by carmocca** [comment]
Hi @artnoage. I recently removed the `flash-attn` code path (#668) since PyTorch 2.2 already vendors the v2 version and it seems performant from my experiments.

The repo also includes a test for `torch.compile`: https://github.com/Lightning-AI/lit-gpt/blob/main/tests/test_model.py#L396-L417.

I strongly recommended that you install PyTorch 2.2 nightly (see README instructions) if you want to run `torch.compile`

**Comment by artnoage** [comment]
@carmocca I tried it. It works and it speeds things a lot...at least for the model I am training.

**Comment by carmocca** [comment]
Where would you suggest to put it precisely? PRs are welcome

**Comment by artnoage** [comment]
I know PRs are welcome but I dont feel confident yet. I personally put it after line 82, like this
        model = GPT(config)
        model.apply(model._init_weights)
        model=torch.compile(model)

Maybe you make it with an if-statement like in Karpathy's repo. So you add a compile=False/True (false being the default) in the beginning and an if-statement before 82. And make a comment in the tutorial that this speed things up (20-30% in my case), although it may not be compatible with future libraries  (I tried to use it with the tiny-llama codebase too after changing the flash-attention part but it still didnt work because of xformers, so I will be cautious about possible future conflicts.)  

I just want to say at this point that you are doing very good job. Congratz.

**Comment by carmocca** [comment]
Ah I thought you were talking about Flash attention 2.

Yes, we will eventually add a compile flag. If you are interested about TinyLlama, we are working on adding a script for it (#677) which will include compilation.

Closing!
