### ISSUE TITLE
A memory issue when you resume

### ISSUE THREAD

**Issue by artnoage** [Lightning-AI/lit-gpt#696]
I noticed that some times when I resume training (without changing anything at all), I get a not enough memory error. If I decrease the batch, it runs normally but then the memory used is as expected ("if I half the batch memory usage is halfed"). Is there any chance that something is not optimized in the resuming process?

**Comment by Andrei-Aksionov** [comment]
Hey @artnoage 

Thanks for reporting.
Could you also provide additional info, so it's easier to repeat the issue:
1. How many graphics cards did you use
2. Did you recreate the venv before submitting the issue (and what version of PyTorch and CUDA you used)
3. What scripts did you use
4. It would be great if you put here the CLI commands that you used

Thanks

**Comment by artnoage** [comment]
I can't reproduce the error at the moment, so I will close the issue.
