### ISSUE TITLE
import lightening as L isn't working

### ISSUE THREAD

**Issue by sanyalsunny111** [Lightning-AI/lit-gpt#700]
I have used this until last week and there was no issue today geting this weird error. May be caused by some new update.

![image](https://github.com/Lightning-AI/lit-gpt/assets/36811567/8d5c4111-d836-49c8-8cfa-2dd74d8e91f2)

**Comment by carmocca** [comment]
That is strange because there hasn't been any torchmetrics release recently.

`pip uninstall -y matplotlib` should fix it

**Comment by sanyalsunny111** [comment]
Thank you very much for responding. Tried that but seems some more cuda issue.

![image](https://github.com/Lightning-AI/lit-gpt/assets/36811567/82718360-0a1b-4db5-9b29-c467c2c124c6)

**Comment by carmocca** [comment]
Try upgrading CUDA if possible. It'll also run faster

**Comment by sanyalsunny111** [comment]
Thank you very much.
