### ISSUE TITLE
[Question] mistral error

### ISSUE THREAD

**Issue by nevermet** [Lightning-AI/lit-gpt#705]
Dear all,

I tried to run mistral model as I did with Llama 2 but it fails with the message while running generate/base.py:
File ... lit-gpt/generate/base.py" , line 76, in generate
    Idx_next = torch.multinomial(probs, num_samples=1).to(dtype=dtype)
RuntimeError: probability tensor contains either 'inf', 'nan' or element < 0

I searched the error but couldn't find the right solution. I followed the instructions in tutorial pages as I did for Llama 2. So, I wonder what I should be careful about running Mistral and what could go wrong.

Thank you in advance.

**Comment by Andrei-Aksionov** [comment]
Hello @nevermet 

I just tried to run `Mistral` model like it's described in the [Tutorial](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/download_mistral.md).
Also tried generation script:
```bash
python generate/base.py --checkpoint_dir checkpoints/mistralai/Mistral-7B-Instruct-v0.1
```

Everything worked ok. It was on a single T4, PyTorch 2.1, CUDA 12.1.

Try to recreate the venv, do all the steps that are listed in the tutorial.

After that, please, report here.
