### ISSUE TITLE
'QuantState' object is not subscriptable

### ISSUE THREAD

**Issue by kannangce** [Lightning-AI/lit-gpt#707]
I tried fine-tuning `mistralai/Mistral-7B-Instruct-v0.1`.

And getting the below exception

> {'eval_interval': 100, 'save_interval': 100, 'eval_iters': 100, 'eval_max_new_tokens': 100, 'log_interval': 1, 'devices': 1, 'learning_rate': 0.0003, 'batch_size': 128, 'micro_batch_size': 4, 'gradient_accumulation_iters': 32, 'max_iters': 50000, 'weight_decay': 0.01, 'lora_r': 8, 'lora_alpha': 16, 'lora_dropout': 0.05, 'lora_query': True, 'lora_key': False, 'lora_value': True, 'lora_projection': False, 'lora_mlp': False, 'lora_head': False, 'warmup_steps': 100}
Loading model 'checkpoints/mistralai/Mistral-7B-Instruct-v0.1/lit_model.pth' with {'org': 'mistralai', 'name': 'Mistral-7B-Instruct-v0.1', 'block_size': 4096, 'vocab_size': 32000, 'padding_multiple': 512, 'padded_vocab_size': 32000, 'n_layer': 32, 'n_head': 32, 'n_embd': 4096, 'rotary_percentage': 1.0, 'parallel_residual': False, 'bias': False, 'lm_head_bias': False, 'n_query_groups': 8, 'shared_attention_norm': False, '_norm_class': 'RMSNorm', 'norm_eps': 1e-05, '_mlp_class': 'LLaMAMLP', 'gelu_approximate': 'none', 'intermediate_size': 14336, 'rope_condense_ratio': 1, 'rope_base': 10000, 'r': 8, 'alpha': 16, 'dropout': 0.05, 'to_query': True, 'to_key': False, 'to_value': True, 'to_projection': False, 'to_mlp': False, 'to_head': False, 'head_size': 128, 'rope_n_elem': 128}
Number of trainable parameters: 3,407,872
Traceback (most recent call last):
  File "/content/llm-finetune/finetune/lora.py", line 338, in <module>
    CLI(setup)
  File "/content/llm-finetune/myenv/lib/python3.10/site-packages/jsonargparse/_cli.py", line 96, in CLI
    return _run_component(components, cfg_init)
  File "/content/llm-finetune/myenv/lib/python3.10/site-packages/jsonargparse/_cli.py", line 181, in _run_component
    return component(**cfg)
  File "/content/llm-finetune/finetune/lora.py", line 96, in setup
    fabric.launch(main, data_dir, checkpoint_dir, out_dir, quantize)
  File "/content/llm-finetune/myenv/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 834, in launch
    return self._wrap_and_launch(function, self, *args, **kwargs)
  File "/content/llm-finetune/myenv/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 920, in _wrap_and_launch
    return to_run(*args, **kwargs)
  File "/content/llm-finetune/myenv/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 925, in _wrap_with_setup
    return to_run(*args, **kwargs)
  File "/content/llm-finetune/finetune/lora.py", line 133, in main
    fabric.print(f"Number of non trainable parameters: {num_parameters(model, requires_grad=False):,}")
  File "/content/llm-finetune/lit_gpt/utils.py", line 32, in num_parameters
    total += math.prod(p.quant_state[1])
TypeError: 'QuantState' object is not subscriptable

I'm running this command in collab container via CLI with 2 Nvidia-T4 GPU.

```
MODEL="mistralai/Mistral-7B-Instruct-v0.1"
python scripts/download.py --repo_id $MODEL
python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/$MODEL

python scripts/prepare_csv.py --csv_path data.csv --destination_path $MODEL/data/csv --checkpoint_dir checkpoints/$MODEL --test_split_fraction 0.1 --seed 42 --mask_inputs false --ignore_index -1

python finetune/lora.py --precision 32-true --quantize bnb.nf4 --checkpoint_dir checkpoints/$MODEL --out_dir output/code-gen-ui --data_dir $MODEL/data/csv 
```

And all the commands until `prepare_csv.py` succeeds. Any idea what am I missing?

**Comment by nicola-v** [comment]
That seems to be caused by the latest `bitsandbytes`. I had v0.41.2 installed: downgrading to v.0.41.0 fixed it.

**Comment by kannangce** [comment]
You saved my day. Thanks @nicola-v !

**Comment by Andrei-Aksionov** [comment]
Hello @kannangce 

Could you try this fix? https://github.com/Lightning-AI/lit-gpt/pull/715
