### ISSUE TITLE
[error] Eval not working with any generation tasks such as coqa or truthfulqa_gen etc

### ISSUE THREAD

**Issue by sanyalsunny111** [Lightning-AI/lit-gpt#709]
Here is the error which is occurring everytime I am trying to evaluate using a generation task such as coqa or truthfulqa_gen etc.

![image](https://github.com/Lightning-AI/lit-gpt/assets/36811567/4cf243f6-67af-48fe-b0a4-49519a032768)

**Comment by sanyalsunny111** [comment]
so, to put things in perspective I have tried to set_kv_cache, but it dodn't work. I have also tried to run the same experiment using the original lm_eval harness and it worked [attached]. So, the problem lies in the lit-gpt/eval.

![image](https://github.com/Lightning-AI/lit-gpt/assets/36811567/510eee27-469a-4f2f-9bec-6e9d055d0591)

**Comment by sanyalsunny111** [comment]
Hey @carmocca @rasbt I tried this piece and it worked but then this is showing some other error. I am trying to solve this issue.

This is what I added to eval/lm_eval_harness.py

 ```
 with fabric.init_tensor():
        # enable the kv cache
        model.set_kv_cache(batch_size=1)
```
Here is the new error

![image](https://github.com/Lightning-AI/lit-gpt/assets/36811567/bbf2cc2a-e883-47d0-9f7f-682f70fc7194)

**Comment by carmocca** [comment]
Could you share exactly which command you ran?
