### ISSUE TITLE
Does Lit-gpt support batch inference?

### ISSUE THREAD

**Issue by dat-nguyen-thanh** [Lightning-AI/lit-gpt#714]
Hi, I'm quite new to lit-gpt and wondering if there is a way to do naive batch inference. As far as I understand, the function `generate` does not support batch inference, but at the same time, I see that we have to set `batch_size` to `model.set_kv_cache`.
![image](https://github.com/Lightning-AI/lit-gpt/assets/136060222/91d854db-9b44-473e-824f-01539aebfb36)

Does this mean there is a way to do batch inference with lit-gpt? If no, then what is the meaning of `batch_size` that feeds into `set_kv_cache`?

**Comment by carmocca** [comment]
The generation code is the piece that doesn't support batched inference. There's an issue tracking this in #345. I'll be implementing this soon. Closing as a duplicate

**Comment by madhurapande19** [comment]
Is the batch inferencing implemented now?

**Comment by madhurapande19** [comment]
Is the batch inferencing implemented now?

**Comment by jinulee-v** [comment]
https://github.com/Lightning-AI/lit-gpt/issues/345#issuecomment-1831087272

For anyone looking for a solution, here is a **very naive (and thus slow)** version of batch inference.
