### ISSUE TITLE
[Suggestion] Remove hardcoding

### ISSUE THREAD

**Issue by MatteoRaso** [Lightning-AI/lit-gpt#716]
All the files in finetune/ are hardcoded to use stabilitylm and alpaca, which makes it difficult to use. Ideally, there would be some sort of way for the user to input what directory they want to use without having to manually adjust the files.

**Comment by Andrei-Aksionov** [comment]
Hello @MatteoRaso 

These arguments aren't hardcoded, these are just defaults.
You can easily change them by providing CLI args.
```bash
python finetune/lora.py --help
```
will show you want can be changed. Basically all the arguments inside `setup` function. 
(That is true for all the scripts).
