### ISSUE TITLE
[Question] is it ok to use all huggingface llm models with lit-gpt?

### ISSUE THREAD

**Issue by nevermet** [Lightning-AI/lit-gpt#717]
Dear all,

I wonder if I can use other huggingface llm models not described in the tutorials here. Can we use only the llms in the tutorials?

Thank you in advance.

**Comment by Andrei-Aksionov** [comment]
Hello @nevermet 

Lit-GPT supports majority of popular LLM building blocks.
So it's the matter of a config file. If the model isn't in the tutorial then it's not in the `lit-gpt/config.py` file.
But usually it's fairly easy to add a new config. [Here](https://github.com/Lightning-AI/lit-gpt/issues/427) you can find examples how some configs were added. If you want you can create a PR with the new config too.
