### ISSUE TITLE
Pretrain - No such file or directory: lit_config.json

### ISSUE THREAD

**Issue by melang982** [Lightning-AI/lit-gpt#718]
I'm following redpajama tutorial, and prepare_redpajama.py fails with  
No such file or directory: <my checkpoint path>lit_config.json

Is the tutorial missing something, should I convert the checkpoint to lit format first?

**Comment by Andrei-Aksionov** [comment]
Hello @melang982 

Could you provide more details?
What commands did you use, what is the error stack trace.
I'm looking at the code of `prepare_redpajama.py` and don't see where `lit_config.json` is required. So I need your help here 😄.
The more info the better.

**Comment by melang982** [comment]
line 150 of prepare_redpajama.py: config = Config.from_json(checkpoint_dir / "lit_config.json")

**Comment by Andrei-Aksionov** [comment]
I'm so blind 🤦. Sorry for that.
Apparently yes, you need to convert to Lit format the downloaded model first:
```bash
python scripts/convert_hf_checkpoint.py --checkpoint_dir ...
```

Could please you try this out and report here back?

**Comment by melang982** [comment]
After converting it works 👍
By the way, does it use multithreading when tokenizing to binaries? Just wanted to check before creating a suggestion. It seems slower than preparing dataset with llama2c (it uses multithreading)

**Comment by Andrei-Aksionov** [comment]
From what I can see, yes, it's a single-threaded process. Plus checked it on a machine with 32 cores just to be on a safe side.
