### ISSUE TITLE
How to transform SantaCoder model from Huggingface to lit-gpt checkpoint?

### ISSUE THREAD

**Issue by THULiusj** [Lightning-AI/lit-gpt#719]
SantaCoder link: https://huggingface.co/bigcode/santacoder
Any experts can give me some guidance of how to transform this HF model to lit-gpt format? So I can try to inference this model on TPU....

**Comment by carmocca** [comment]
SantaCoder seems to use dropout. But Lit-GPT doesn't implement it so this is not a supported checkpoint at the moment.

**Comment by AshishMittal** [comment]
Hi, is this supported or planned to be supported?

**Comment by rasbt** [comment]
@carmocca Supporting dropout some time may not be a bad idea since this would allow us to also support GPT-2 etc.

**Comment by carmocca** [comment]
Dropout adds a lot of uglyness for very little value. I would only add it if the strongest models start using it
