### ISSUE TITLE
scaled_dot_product_attention() got an unexpected keyword argument 'scale' Error

### ISSUE THREAD

**Issue by ChangeNext** [Lightning-AI/lit-gpt#763]
python generate/base.py --prompt "Hello, my name is" --checkpoint_dir checkpoints/stabilityai/stablelm-base-alpha-3b

occur error this

TypeError :scaled_dot_product_attention() got an unexpected keyword argument 'scale' Error

my torch version = 2.0.1+cu117

**Comment by Andrei-Aksionov** [comment]
Hello @ChangeNext 
The current codebase relies on PyTorch >= 2.1:
https://github.com/Lightning-AI/lit-gpt/blob/21c1c5941fd56216875a250fb2c03053ba649793/requirements.txt#L1

Could you upgrade it?
Ideally upgrade all the packages in a freshly created virtual environment.
