### ISSUE TITLE
Out of CUDA memory on A100 40GB when trying to run the LORA example

### ISSUE THREAD

**Issue by mrticker** [Lightning-AI/lit-gpt#781]
I run out of CUDA memory on A100 40GB when trying to run the LORA example on a Mistral-7B model:

> 		'python scripts/download.py --repo_id mistralai/Mistral-7B-Instruct-v0.1 \
> 			--checkpoint_dir /pretrained/checkpoints',
> 	
> 		'python scripts/convert_hf_checkpoint.py --checkpoint_dir \
> 			/pretrained/checkpoints/mistralai/Mistral-7B-Instruct-v0.1',
> 			
> 		'python scripts/prepare_alpaca.py --checkpoint_dir \
> 			/pretrained/checkpoints/mistralai/Mistral-7B-Instruct-v0.1 \
> 			--destination_path /pretrained/data/alpaca',
> 			
> 		'python finetune/lora.py \
> 	  		--checkpoint_dir /pretrained/checkpoints/mistralai/Mistral-7B-Instruct-v0.1/ \
> 	  		--data_dir /pretrained/data/alpaca \
> 	  		--out_dir /results/lit \
>   			--precision bf16-true'

I guess this is not to be expected, what might be the reason?

**Comment by theQuert** [comment]
Same here, any ideas?

**Comment by Andrei-Aksionov** [comment]
> I guess this is not to be expected,

Sorta expected, though, unfortunately, I don't have access to A100, so cannot validate that exact model.
From the [resource table](https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/resource-tables.md) you can see that LlaMa2-7b with microbatch size of 4 (the default value) the model doesn't fit into a single A100 40GB. With Mistral-7B it should be the same. With microbatch size of 2 it fits without problem. So try to play with it.
https://github.com/Lightning-AI/lit-gpt/blob/6b3a32c51f53461ab9cb4a28fcfc09e4821ce654/finetune/lora.py#L40
