### ISSUE TITLE
Support input_ids OR input_embs

### ISSUE THREAD

**Issue by MF-FOOM** [Lightning-AI/lit-gpt#785]
Huggingface `transformers`' `forward` impl supports passing either `input_ids` (like `idx` in `lit-gpt`) OR `input_embs` (so you can pass embeddings directly instead of just token ids). This is useful for a lot of AI research where you want to pass raw latent data to a model, like for [soft prompting](https://blog.research.google/2022/02/guiding-frozen-language-models-with.html) or multi-modal applications.

Would be pretty trivial to support this in `lit-gpt`, though, might require a breaking change depending on how it's done?

see: https://github.com/huggingface/transformers/blob/ce315081340fdf6846f16c321eb53878b6272d53/src/transformers/models/llama/modeling_llama.py#L860-L868

**Comment by carmocca** [comment]
I want to avoid this change in the interest of simplicity. As you pointed out, supporting this is trivial, but targeting everything that HF transforms supports is not a goal. This might be revisited in the future if it becomes necessary for the scripts that are implemented in the repo.

If you are forking the project, you can copy the file and make this change. I also suggest dropping the embeddings entirely to avoid the extra memory usage. Beware of checkpoint loading, as you will need `strict=False`.

**Comment by MF-FOOM** [comment]
mmm that's too bad, I think having `input_embs` is really nice for research, but I understand the desire for simplicity 

>  I also suggest dropping the embeddings entirely to avoid the extra memory usage. 

Can you explain this a bit more? I don't think I follow... do you mean delete wte from the transformer ModuleDict?

**Comment by carmocca** [comment]
Yes, exactly. The HF implementation seems wasteful because https://github.com/huggingface/transformers/blob/ce315081340fdf6846f16c321eb53878b6272d53/src/transformers/models/llama/modeling_llama.py#L825 is unused if you pass `inputs_embeds` argument.
