### ISSUE TITLE
Function calling LLaMa 2 not working as intended

### ISSUE THREAD

**Issue by Fran-98** [Lightning-AI/lit-gpt#789]
Hi! I'm trying to use lit-gpt to run this model: [https://huggingface.co/Trelis/Llama-2-7b-chat-hf-function-calling-v2](url), but I'm having no luck. I got it running but when it does the inference it returns nonsense. Just random text like this:
`M
The
Lects)
Podk
LucasS
Procts
M#s
If you cans
Thes's
L
Ins
M5, or hyds
Ins Lucas`

I don't know what else to tweak to have it running properly, maybe it's a problem with my configuration, as this model is not supported yet.

Model config
```

llama_2_function_calling = dict(
        name="Llama-2-7b-chat-hf-function-calling-v2",
        hf_config=dict(org="Trelis", name="Llama-2-7b-chat-hf-function-calling-v2"),
        padding_multiple=64,
        n_layer=32,
        rotary_percentage=1.0,
        parallel_residual=False,
        bias=False,
        _norm_class="RMSNorm",
        _mlp_class="LLaMAMLP",
        intermediate_size=11008,
        norm_eps=1e-6,
        block_size = 4096,
        vocab_size= 32000,
        n_head = 64,
        n_embd = 4096,
        rope_base = 10000,
    )
```

Prompt config
```
b_inst, e_inst = "[INST]", "[/INST]"
b_sys, e_sys = "<<SYS>>\n", "\n<</SYS>>\n\n"
b_func, e_func = "<FUNCTIONS>", "</FUNCTIONS>\n\n"

system_prompt = f"{b_func}{function_list.strip()}{e_func}{b_inst}{b_sys}{system_prompt.strip()}{e_sys}{user_prompt.strip()}{e_inst}\n\n
```

**Comment by Fran-98** [comment]
Hey @Andrei-Aksionov !
Now it's working, it was the number of heads, I don't know how I didn't saw it, it was right under my nose, and I was busy searching the horizon 😅. Sometimes it's necesary a quick look from someone from outside the problem to find the solution.
Thank you! 😁

**Comment by StainlessStlRat** [comment]
Hey @Fran-98, sorry to ping you but can't seem to find much about this.

I don't understand how we're supposed to achieve function calling on any of the function calling models that LitGPT plays well with. From my understanding, litGPT uses its own format.

How does the API above interplay with the litgpt API?
