### ISSUE TITLE
Add support for StableLM Zephyr 3B

### ISSUE THREAD

**Issue by lantiga** [Lightning-AI/lit-gpt#799]
Here's the announcement https://stability.ai/news/stablelm-zephyr-3b-stability-llm

**Comment by Andrei-Aksionov** [comment]
Hey @lantiga 
I'll add this checkpoint.

It will be my break from trying to marry HF-optimized AutoGPTQ with Lit-GPT 😄.

**Comment by lantiga** [comment]
ahah love it!
