### ISSUE TITLE
StableLM: support updated models

### ISSUE THREAD

**Issue by Andrei-Aksionov** [Lightning-AI/lit-gpt#802]
Hi there 👋 

It looks like Stability.ai updated existing models with v2 version and added some new ones: [StableLM collection](https://huggingface.co/collections/stabilityai/stable-lm-650852cfd55dd4e15cdcb30a).

Most noticeable difference is that now models are shipped in `safetensor` format. 
In addition there might be differences in the model architecture, so the conversion script might fail.

**Comment by carmocca** [comment]
This includes the just released https://huggingface.co/stabilityai/stable-code-3b (https://stability.ai/news/stable-code-2024-llm-code-completion-release)

**Comment by carmocca** [comment]
These should all be supported since https://github.com/Lightning-AI/lit-gpt/pull/801 was merged. We need to add the config dictionaries.

**Comment by ARROGANT666** [comment]
> 嘿，你好 👋
> 
> 看起来 Stability.ai 使用 v2 版本更新了现有模型并添加了一些新模型：[StableLM 集合](https://huggingface.co/collections/stabilityai/stable-lm-650852cfd55dd4e15cdcb30a)。
> 
> 最明显的区别是现在模型是以格式发货的。此外，模型体系结构可能存在差异，因此转换脚本可能会失败。`safetensor`

When will the code supporting the safetensor format be released?

**Comment by ARROGANT666** [comment]
> Collaborator

When will the code supporting the safetensor format be released?

**Comment by ARROGANT666** [comment]
> Hi there 👋
> 
> It looks like Stability.ai updated existing models with v2 version and added some new ones: [StableLM collection](https://huggingface.co/collections/stabilityai/stable-lm-650852cfd55dd4e15cdcb30a).
> 
> Most noticeable difference is that now models are shipped in `safetensor` format. In addition there might be differences in the model architecture, so the conversion script might fail.

When will the code supporting the safetensor format be released?

**Comment by Andrei-Aksionov** [comment]
Hello @ARROGANT666 
I'll take a look at it only next week.
