### ISSUE TITLE
Checkpoint is not a checkpoint directory

### ISSUE THREAD

**Issue by Rishabh250** [Lightning-AI/lit-gpt#861]
--checkpoint_dir '/Users/rishabhbansal/Report Generation Model/lit-gpt/checkpoints/stabilityai/stablelm-base-alpha-3b' is not a checkpoint directory.
Find download instructions at https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials

**Comment by carmocca** [comment]
Try following this tutorial: https://github.com/Lightning-AI/lit-gpt/blob/main/tutorials/download_stablelm.md

**Comment by TheGermanEngie** [comment]
I am running into this problem, but now it's after following the instructions for downloading a fine-tuned Phi-2 model from HF, which downloaded successfully and are in the right directories and such. I even tried specifying the full path to each file/directory to no avail.

**Comment by TheGermanEngie** [comment]
<img width="951" alt="Screenshot 2024-03-26 at 15 47 49" src="https://github.com/Lightning-AI/litgpt/assets/75632861/1af683a5-7064-44f6-8bd8-0022832cd425">

**Comment by TheGermanEngie** [comment]
<img width="760" alt="Screenshot 2024-03-26 at 15 51 17" src="https://github.com/Lightning-AI/litgpt/assets/75632861/9a742afc-455e-46d1-bb79-23820a4c2b01">

**Comment by TheGermanEngie** [comment]
This was also after downloading with lit-gpt's download script, which I assumed would download the right files automatically

**Comment by Andrei-Aksionov** [comment]
@TheGermanEngie Have you tried this: https://github.com/Lightning-AI/litgpt/blob/main/tutorials/download_model_weights.md#finetunes-and-other-model-variants ?

**Comment by TheGermanEngie** [comment]
Yes, of course, that's how I downloaded this specific fine-tuned version.

**Comment by Andrei-Aksionov** [comment]
Ok, got it.
If the model on HF, could you provide it's repo id?
I want to reproduce the error on my machine

**Comment by TheGermanEngie** [comment]
mobiuslabsgmbh/aanaphi2-v0.1

**Comment by Andrei-Aksionov** [comment]
For me this command did the trick:
```bash
python litgpt/scripts/download.py --repo_id mobiuslabsgmbh/aanaphi2-v0.1 --model_name phi-2
```

I also ran a quick fine-tuning
```bash
python litgpt/finetune/lora.py --checkpoint_dir checkpoints/mobiuslabsgmbh/aanaphi2-v0.1 
```

and all worked without issues.

Basically I created a new Studio (https://lightning.ai/), cloned repo, installed all the required dependencies and ran two commands that are listed above.

**Comment by TheGermanEngie** [comment]
Ok, I will try that with the Lightning studio, I was using a Ubuntu cloud instance because I need a 3090 GPU. What GPU does lightning studio allow for their free credits?

**Comment by Andrei-Aksionov** [comment]
A single T4 or A10G.

**Comment by TheGermanEngie** [comment]
Noted, I'll try and use the A10G. I did do every step suggested, but in the cloud instance. Why do you think it's not working in the cloud? I have everything correctly installed of course, and it also wouldn't take my .json dataset as-is, I had to manually split it in order for it to accept it. Following the tutorial verbatim on Github was not working.

**Comment by Rishabh250** [comment]
Hi guys, please remove me from CC.
I think you have added me by mistake and I am not the person for this chat.

**Comment by rasbt** [comment]
Hm, I never bumped into this issue. Top off my head, three things come to mind:

- did you perhaps start with a Studio template that was based on an older version of LitGPT
- have you used the `--model_name phi-2` as suggested by @Andrei-Aksionov ?
- what operating system where you using when running this locally? Perhaps there's something particular about the json encoding that is handled differently in Ubuntu

> Hi guys, please remove me from CC.
I think you have added me by mistake and I am not the person for this chat.

Sorry about that! I don't think we can do that ourselves, but you could click the "Unsubscribe" button or either in the email or on the top of this page:

<img width="353" alt="Screenshot 2024-03-26 at 10 37 31 AM" src="https://github.com/Lightning-AI/litgpt/assets/5618407/f9b30630-1cef-4b13-965e-a58816bfee55">

**Comment by Rishabh250** [comment]
Sorry buddy my mistake, I have forgot that I have opened issue in GitHub.

Again sorry about that

**Comment by TheGermanEngie** [comment]
did you perhaps start with a Studio template that was based on an older version of LitGPT

No, I downloaded it right from the github repo. 

have you used the --model_name phi-2 as suggested by @Andrei-Aksionov?

Yes, I used that after others didn't work. 

what operating system where you using when running this locally? Perhaps there's something particular about the json encoding that is handled differently in Ubuntu

I am on a 22.04 instance.

**Comment by Andrei-Aksionov** [comment]
@TheGermanEngie Did the model download/conversion work this time? I assume that now the only problem is with custom json file.

**Comment by carmocca** [comment]
This looks to me like an issue with the paths. If you look at the image in the top post it says:

![image](https://github.com/Lightning-AI/litgpt/assets/11067892/f38b067f-891e-4be0-a4b5-699098ca1071)

Notice how litgpt found a checkpoint in the one starting with `/workspace/home` but the user passed `/home`

**Comment by Andrei-Aksionov** [comment]
@carmocca An eagle eyed 😄 
That should explain why locally it did work, but not in the cloud: locally you, most likely, don't have `workspace`.

**Comment by TheGermanEngie** [comment]
> This looks to me like an issue with the paths. If you look at the image in the top post it says:
> 
> 
> 
> ![image](https://github.com/Lightning-AI/litgpt/assets/11067892/f38b067f-891e-4be0-a4b5-699098ca1071)
> 
> 
> 
> Notice how litgpt found a checkpoint in the one starting with `/workspace/home` but the user passed `/home`
> 
> 
> 
> I would expect that passing the right path would work then

I did notice that as well, the "workspace" thing is a weird folder created by the hosting service I use. I did check the directories when I saw that error but there is nothing in /workspace/. Starting to think it's the host's fault with their funky default paths.

**Comment by TheGermanEngie** [comment]
And the checkpoint is not in /workspace/home/user etc, it's just in /home/user/litgpt etc.

**Comment by TheGermanEngie** [comment]
Update: for some reason both checkpoints are in both /workspace/home/user/litgpt/checkpoints as well as /home/user/litgpt/checkpoints. Changing the syntax to include /workspace/ made no difference. Thinking this is a deeper bug.

<img width="947" alt="Screenshot 2024-03-26 at 18 19 05" src="https://github.com/Lightning-AI/litgpt/assets/75632861/f3c05fcf-8c83-4935-822d-1dac1c94dc72">

**Comment by TheGermanEngie** [comment]
I have just noticed something nobody has pointed out: a super small minute typo. I have been calling the ending model "aanaphi-2-v0.1", when there's no "-" in "aanaphi-2" - it's just aanaphi2-v0.1". Loading from /workspace/home/user vs /home/user/ doesn't make a difference. The model loaded, and was about to start training, and has now given me this error.

<img width="949" alt="Screenshot 2024-03-26 at 18 25 33" src="https://github.com/Lightning-AI/litgpt/assets/75632861/64c8386b-38ec-483f-b8bd-a7c345898a6e">

**Comment by carmocca** [comment]
Looks like the data wasn't tokenized properly. What command did you run exactly?

**Comment by TheGermanEngie** [comment]
Here is the command. It does this for both adapter_v2 and LoRA. If I can't fix this in the next hour I'm just going to do a lightning.ai instance

<img width="924" alt="Screenshot 2024-03-26 at 18 37 49" src="https://github.com/Lightning-AI/litgpt/assets/75632861/ae2f2451-0481-4434-9b16-6a566179a749">

**Comment by TheGermanEngie** [comment]
After fixing the paths issue, it no longer yells at me about the .json file, but even linking it as directed in lit-gpt (--data JSON --data.json_path /home/user/Litgpt/Litgpt/data/all_merged.json) now throws this error

<img width="956" alt="Screenshot 2024-03-26 at 18 44 45" src="https://github.com/Lightning-AI/litgpt/assets/75632861/65d56d23-ea3f-4e3e-9b74-829552e67e42">

**Comment by carmocca** [comment]
@TheGermanEngie Can you open a new issue and share a slice or a mock of your JSON data there so that we rerun it on our end to see if we can reproduce your issues?

**Comment by TheGermanEngie** [comment]
> @TheGermanEngie Can you open a new issue and share a slice or a mock of your JSON data there so that we rerun it on our end to see if we can reproduce your issues?

Sure. I'll make one that links back to this issue just in case. I will also shut down my cloud instance and try lightning.ai tomorrow.
