### ISSUE TITLE
Mistral-7B-Instruct-v0.2 to lit-gpt format

### ISSUE THREAD

**Issue by Chasapas** [Lightning-AI/lit-gpt#865]
Hello i tried to convert the Mistral-7B-Instruct-v0.2 checkpoint to the lit-gpt format, and it seems that is not supported.
`ValueError: 'Mistral-7B-Instruct-v0.2' is not a supported config name`.
Any idea?

**Comment by Andrei-Aksionov** [comment]
Hello @Chasapas 

That's because Lit-GPT's config only has v0.1:
https://github.com/Lightning-AI/lit-gpt/blob/ad6554911951768b1db275a9b911e767faaa9aa7/lit_gpt/config.py#L1174-L1193

PRs are welcome.

**Comment by carmocca** [comment]
Note to self, seems like v0.2 additionally does not use sliding window attention: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2/blob/main/config.json#L19
