### ISSUE TITLE
The Phi model definition has changed, conversion fails

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lit-gpt#868]
The Phi-1.5 model definition on HF has changed recently, and makes our tests fail:
https://huggingface.co/microsoft/phi-1_5/commit/d3ba318b780bfb92942c28853066fe4036d1b496

**Comment by carmocca** [comment]
We already had to pin it once: https://github.com/Lightning-AI/lit-gpt/pull/762. I'll do this again and leave this issue open until it is updated

**Comment by Andrei-Aksionov** [comment]
I can fix the issue tomorrow.

**Comment by awaelchli** [comment]
That would be great, thanks! I briefly looked, but they made quite a few changes 😅

**Comment by carmocca** [comment]
Phi 2 will need to be updated too. Pinning it in https://github.com/Lightning-AI/lit-gpt/pull/875

**Comment by carmocca** [comment]
Should be fixed by #876
