### ISSUE TITLE
Our Phi-2 training doesn't include dropout

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lit-gpt#885]
We support the Phi-2 model architecture, however, it uses dropout during training: https://huggingface.co/microsoft/phi-2/blob/main/config.json#L26, https://huggingface.co/microsoft/phi-2/blob/main/modeling_phi.py#L674

Since there's no plan to add dropout to the model definition, we can choose between:
- Remove the model config
- Add a note to the Phi tutorial that training will not be equivalent

**Comment by Andrei-Aksionov** [comment]
Btw, why there is no plan to add support for dropout?

**Comment by carmocca** [comment]
To reduce the model's implementation complexity

**Comment by Andrei-Aksionov** [comment]
> Add a note to the Phi tutorial that training will not be equivalent

I like this option more.
