### ISSUE TITLE
Small change in the scripts/download.py

### ISSUE THREAD

**Issue by UYousafzai** [Lightning-AI/lit-gpt#919]
Currently besides the safetensors and bin files the script only downloads:

download_files = ["tokenizer*", "generation_config.json"]

i think it would be beneficial to download all .json files such as config.json, vocab.json as they can be often necessary for converting these models to GGUF formats, what I noticed was that convert.py script from the llama cpp guys requires the config.json of the original repo and upon its absence it guesses the params which somehow doesn't fail the conversion but it fails at the inference load time.

I made the change to the above line to this all of my auto train to auto conversion pipelines are running without any issues. 

### Change suggested
download_files = ["tokenizer*", "*.json"]

with limited understanding of the entire repo not sure if this poses any risks with some of the config files generated by the training code like lit_config.json etc hence not improving this myself and rather suggesting it here.

**Comment by carmocca** [comment]
Hi. I understand your issue. I think instead of this, in the future we will include the model hub URL so that the files can be downloaded if necessary for the steps that need them

**Comment by UYousafzai** [comment]
awesome, I guess I'll keep this open until you guys close it.

Best Regards,
K.
