### ISSUE TITLE
Automatically convert checkpoint after downloading

### ISSUE THREAD

**Issue by awaelchli** [Lightning-AI/lit-gpt#953]
We can download models from the hub with the `scripts/download.py` CLI, but we always have to convert it with `scripts/convert_lit_checkpoint.py` too to use it in lit-gpt. I don't see a use case where you only want to download but not convert to lit-gpt. 

I propose that we simply convert the checkpoint automatically at the end of the download. This would remove an extra step from getting started.

**Comment by Andrei-Aksionov** [comment]
Sounds good.

**Comment by rasbt** [comment]
I like this idea, and it would streamline the Lit-GPT usage for many users. Personally, I sometimes also forget the conversion step before preparing a dataset or finetuning the model, which throws an error etc. I bet many users bump into that as well.

**Comment by adithya-s-k** [comment]
I would like to take this up. 
@rasbt @Andrei-Aksionov how do i get assigned this issue

**Comment by carmocca** [comment]
Yes, we had this already prepared: https://github.com/Lightning-Universe/lit-llm/blob/main/lit/download_model.py

My suggestion is to have:

```python
python download.py from_hub --repo_id foo/bar
```

That does what's currently implemented

and

```python
python download.py and_convert --repo_id foo/bar 
```

That does both as you are proposing.

There'll need to be some careful management of arguments.

For the `and_convert` command, we could also consider deleting the HF copy of the weights after conversion

**Comment by carmocca** [comment]
I personally use just-download a lot for cases where I want to download on a fast network machine but convert and tinker elsewhere. There's also the `--tokenizer_only` flag that is useful during pretraining and doesn't require conversion

**Comment by awaelchli** [comment]
Yes but your are the developer of lit-gpt who needs to tinker with this stuff when a new model architecture is added. Everyone else just wants to download the model and use it immediately, isn't that a common workflow?

**Comment by adithya-s-k** [comment]
I think having argument parsers like `--no-convert` and `--tokenizer_only` in the `download.py` file would create a more user-friendly workflow for me. I often forget the conversion step.

**Comment by adithya-s-k** [comment]
> @adithya-s-k Since you might not be familiar with jsonargparse, I went ahead and wrote a basic implementation:
> 
> ```diff
> diff --git a/scripts/download.py b/scripts/download.py
> index b1a1a78..db31058 100644
> --- a/scripts/download.py
> +++ b/scripts/download.py
> @@ -3,7 +3,7 @@
>  import os
>  import sys
>  from pathlib import Path
> -from typing import Optional
> +from typing import Any, Optional
>  
>  import torch
>  from lightning_utilities.core.imports import RequirementCache
> @@ -18,7 +18,7 @@ _SAFETENSORS_AVAILABLE = RequirementCache("safetensors")
>  _HF_TRANSFER_AVAILABLE = RequirementCache("hf_transfer")
>  
>  
> -def download_from_hub(
> +def from_hub(
>      repo_id: Optional[str] = None,
>      access_token: Optional[str] = os.getenv("HF_TOKEN"),
>      from_safetensors: bool = False,
> @@ -93,5 +93,21 @@ def download_from_hub(
>              os.remove(safetensor_path)
>  
>  
> +def and_convert(
> +    repo_id: Optional[str] = None,
> +    checkpoint_dir: Path = Path("checkpoints"),
> +    tokenizer_only: bool = False,
> +    dtype: Optional[str] = None,
> +    **from_hub_kwargs: Any,
> +):
> +    from scripts.convert_hf_checkpoint import convert_hf_checkpoint
> +
> +    from_hub(repo_id=repo_id, checkpoint_dir=checkpoint_dir, tokenizer_only=tokenizer_only, **from_hub_kwargs)
> +    if repo_id is None or tokenizer_only:
> +        return
> +    directory = checkpoint_dir / repo_id
> +    convert_hf_checkpoint(checkpoint_dir=directory, dtype=dtype)
> +
> +
>  if __name__ == "__main__":
> -    CLI(download_from_hub)
> +    CLI([from_hub, and_convert])
> ```
> 
> It would still be useful if you could open a PR with this and update all the tutorials and usages of the `download.py` script to use this new feature

Thank you very much it will be very help full


if we are going the only `download.py` route then i will update in the tutorials as well

**Comment by carmocca** [comment]
> Yes but your are the developer of lit-gpt who needs to tinker with this stuff when a new model architecture is added. Everyone else just wants to download the model and use it immediately, isn't that a common workflow?

I don't disagree that it's the most common workflow. We are arguing over:

`python download.py and_convert foo` vs `python download.py --no_convert`.

Ultimately everybody is going to copy-paste whatever we put in the tutorials. I prefer the first approach because then you have two separate functions that each do small pieces of work than putting the conversion logic directly in the current `download_from_hub`. For anybody or any layer on top that intends to import and call these functions directly it seems more flexible whilst still exposing both options from command line for the devs like me.
