### ISSUE TITLE
Reference lit-gpt integration in official `bitsandbytes` docs

### ISSUE THREAD

**Issue by Titus-von-Koeller** [Lightning-AI/lit-gpt#955]
Hi, I'm Titus, one of the maintainers of `bitsandbytes`. Great work with the BNB integration!

We would like to reference your integration in the [official new docs](https://huggingface.co/docs/bitsandbytes/main/en/integrations) that we're slowly building up.

Would one of you maintainers be willing to do a PR on BNB and write a short section [here](https://github.com/TimDettmers/bitsandbytes/blob/main/docs/source/integrations.mdx) referencing your docs and preferably give a TLDR on how to use it?

That would be super helpful :) and give some more exposure to your work.

**Comment by rasbt** [comment]
Thanks for reaching out, and sure, that sounds good! Will do a small PR and then reference here so others can take a peak, too.

**Comment by carmocca** [comment]
It would be best to link directly to the Fabric/PL docs which is what lit-gpt uses:

https://lightning.ai/docs/pytorch/stable/common/precision_intermediate.html#quantization-via-bitsandbytes
https://lightning.ai/docs/fabric/stable/fundamentals/precision.html#quantization-via-bitsandbytes

**Comment by Titus-von-Koeller** [comment]
Perfect, PR is looking great, already merged. Thanks everyone!

**Comment by carmocca** [comment]
And thank you @Titus-von-Koeller for the suggestion! :heart:
