### ISSUE TITLE
Change `merge_lora.py` output path name

### ISSUE THREAD

**Issue by rasbt** [Lightning-AI/lit-gpt#966]
This is a suggestion for making the documentation and user experience to make it more finetuning-script agnostic.

So, currently, 

- `finetune/lora.py` writes a `.../lit_model_lora_finetuned.pth` file 
- `finetune/full.py` writes a `.../lit_model_finetuned.pth` file
- `scripts/merge_lora.py` writes a `.../lit_model.pth` file.

If we want to simplify the documentation and user experience to make it more finetuning-script agnostic, I think it would make sense to have 

- `scripts/merge_lora.py` write a `.../lit_model_finetuned.pth` file.

---

For example, right now:

1. Finetune

```bash
export finetuned_dir=out/lit-finetuned-model

python finetune/lora.py \
   --io.checkpoint_dir checkpoints/$repo_id \
   --io.train_data_dir data/alpaca \
   --io.val_data_dir data/alpaca \
   --train.epochs 1 \
   --io.out_dir $finetuned_dir
```

2. Merge LoRA weights:

Note that this step only applies if the model was finetuned with `lora.py` above and not when `full.py` was used for finetuning.

```bash
python scripts/merge_lora.py \
    --checkpoint_dir checkpoints/$repo_id \
    --lora_path $finetuned_dir/lit_model_lora_finetuned.pth \
    --out_dir $finetuned_dir/
```

3. Convert the finetuning model back into a HF format:

```bash
python scripts/convert_lit_checkpoint.py \
   --checkpoint_path $finetuned_dir/lit_model.pth \
   --output_path out/hf-tinyllama/converted_model.pth \
   --config_path checkpoints/$repo_id/lit_config.json 
```

(If you used `full.py` instead of `lora.py` to finetune your model, 
replace `$finetuned_dir/lit_model.pth` with `$finetuned_dir/lit_model_finetuned.pth`.)

---

If we make this change, we can simplify step 3 to

3. Convert the finetuning model back into a HF format:

```bash
python scripts/convert_lit_checkpoint.py \
   --checkpoint_path $finetuned_dir/lit_model_finetuned.pth \
   --output_path out/hf-tinyllama/converted_model.pth \
   --config_path checkpoints/$repo_id/lit_config.json 
```

**Comment by awaelchli** [comment]
@rasbt When finishing up #984, I decided to put the final checkpoint under a "final" directory name in all scripts. So `.../lit_model_finetuned.pth` is now `.../final/lit_model.pth`. I should have mentioned this, I forgot to discuss it with you and @carmocca. But it should help with the streamlined, standardized loading. And I think it also helps here, because now the `merge_lora.py` script can assume the filename to be `lit_model.pth`. Wdyt?

**Comment by rasbt** [comment]
I think using `lit_model.pth` everywhere is maybe easier than `lit_finetuned_model.pth` in case where `lit_model.pth` is hardcoded. The `.../final` directory will still contain all config + json files and should be standalone, right?

**Comment by rasbt** [comment]
Another thing comes to mind: if the name is `lit_model.pth` then we can also more easily run another finetuning round on it without having to rename it. E.g, if you first finetune on Alpaca, and then on LIMA etc.

**Comment by awaelchli** [comment]
Yes exactly. The checkpoint directory can have any name, and as long as it's contents are in the standardized format containing config files and `lit_model.pth`, it will always work.

**Comment by rasbt** [comment]
Actually, right now having LoRA write `lit_model.pth` might be a bit confusing because it currently only writes the adapter weights. 

So, right now, it's

```bash
python finetune/lora.py \
   --checkpoint_dir checkpoints/$repo_id \
   --data Alpaca \
   --train.epochs 1 \
   --train.max_steps 5 \
   --out_dir $finetuned_dir

mv $finetuned_dir/final/lit_model.pth $finetuned_dir/final/lit_lora_weights.pth

python scripts/merge_lora.py \
    --checkpoint_dir checkpoints/$repo_id \
    --lora_path $finetuned_dir/final/lit_lora_weights.pth \
    --out_dir $finetuned_dir/final

python chat/base.py --checkpoint_dir $finetuned_dir/final
```

### I have a new proposal, what do you think about

1. Adding a `--merge_lora_weights false` flag to the lora script. 
2. Change the output filename `lit_model.pth` -> `lit_lora_weights.pth`

This will then be a similar default behavior as above:

```bash
python finetune/lora.py \
   --checkpoint_dir checkpoints/$repo_id \
   --data Alpaca \
   --train.epochs 1 \
   --train.max_steps 5 \
   --out_dir $finetuned_dir

mv $finetuned_dir/final/lit_model.pth $finetuned_dir/final/lit_lora_weights.pth

python scripts/merge_lora.py \
    --checkpoint_dir checkpoints/$repo_id \
    --lora_path $finetuned_dir/final/lit_lora_weights.pth \
    --out_dir $finetuned_dir/final

python chat/base.py --checkpoint_dir $finetuned_dir/final
```

In addition, for example to minimize the tutorial steps in certain documentations, we can have

```bash
python finetune/lora.py \
   --checkpoint_dir checkpoints/$repo_id \
   --data Alpaca \
   --train.epochs 1 \
   --train.max_steps 5 \
   --out_dir $finetuned_dir \
   --merge_lora_weights true # NEW!

python chat/base.py --checkpoint_dir $finetuned_dir/final
```

I think lots of people love the fact that LoRA doesn't save a whole model by default, so it's easier on storage.

Any thoughts @awaelchli @carmocca

**Comment by rasbt** [comment]
Btw for the `chat` example we could also use `python chat/lora.py`, so merging is not essential here. But the merging is still important in general for

a) people who care about inference speed more than storage
b) using our the evaluation harness adapter script in `eval`

**Comment by awaelchli** [comment]
@rasbt I thought we wanted to automatically merge weights when loading (e.g. in chat or generate.py). Soon we will have all the information saved in the checkpoint to know. I thought it is preferred to save only the lora weights to save space.

Soon we will also have all lora hyperparameters automatically saved to the checkpoint #1012, so error-prone merging with wrong hyperparameters will be gone. I am convinced we can make merging fully automatic on-the-fly.

**Comment by rasbt** [comment]
> I thought we wanted to automatically merge weights when loading (e.g. in chat or generate.py). 

That's actually better. In that case, we would get rid of the separate `generate/lora.py` and `generate/adapter.py` scripts? Yes, that would simplify things and we would have to maintain less duplicated code.

I wasn't sure if `generate/lora.py` merges the weights with the model or if it applies the lora weights on the fly. I.e., in pseudocode:

```python
class LinearWithLoRAMerged(nn.Module):
    def __init__(self, linear, rank, alpha):
        super().__init__()
        self.linear = linear
        self.lora = LoRALayer(
            linear.in_features, linear.out_features, rank, alpha
        )

    def forward(self, x):
        lora = self.lora.A @ self.lora.B
        combined_weight = self.linear.weight + self.lora.alpha*lora.T
        return F.linear(x, combined_weight, self.linear.bias)
```

vs


```python
class LinearWithLoRA(nn.Module):
    def __init__(self, linear, rank, alpha):
        super().__init__()
        self.linear = linear
        self.lora = LoRALayer(
            linear.in_features, linear.out_features, rank, alpha
        )

    def forward(self, x):
        return self.linear(x) + self.lora(x)
```


>  I thought it is preferred to save only the lora weights to save space.

Yes for sure. Then let's do that. But we still need to keep the `merge_lora_weights.py` script because it will be useful for generating models for continued training.
