### ISSUE TITLE
Move scripts inside the package

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lit-gpt#982]
So that it can be called with `python -m litgpt.pretrain` ...

**Comment by awaelchli** [comment]
To avoid cluttering the `lit_gpt` folder, and to avoid name clashes (like lora.py (finetuning) and lora.py (model definition)), we should probably move either the core files into a subfolder core, or move the "training scripts" into a subfolder.

**Comment by carmocca** [comment]
Closing this in favor of https://github.com/Lightning-AI/lit-gpt/issues/996 since they should happen together.
