### ISSUE TITLE
Incremental learning support

### ISSUE THREAD

**Issue by visanth-techconative** [Lightning-AI/lit-gpt#988]
Hello,
Is it possible to train models through incremental learning using lit-gpt?

**Comment by awaelchli** [comment]
There is no explicit support for this in Lit-GPT, but if you just mean continuing to train from a checkpoint then yes, this can certainly be done. There is one template for this here using TinyLlama:
https://lightning.ai/lightning-ai/studios/continued-pretraining-with-tinyllama-1-1b?view=public&section=all

**Comment by visanth-techconative** [comment]
Okay, I'll look into the template. 
Thanks for the response.
