### ISSUE TITLE
Update gemma to use tanh approximation

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lit-gpt#999]
also not in `gemma_pytorch`... so strange. clearly the keras and pytorch folks were different teams entirely lol

_Originally posted by @carmocca in https://github.com/Lightning-AI/lit-gpt/pull/941#discussion_r1498434236_

The reference implementation was recently updated: https://github.com/google/gemma_pytorch/commit/324cb185aa3fe60f43dad4b7ce5096ffdd513cb1

**Comment by carmocca** [comment]
@Andrei-Aksionov would you like to do this change?

**Comment by Andrei-Aksionov** [comment]
Interesting.
Sure, I'll do it.
